fuse-open/fuselibs

- CHANGELOG.md
- Source/Fuse.Nodes/Input/Gesture.uno
Because `Gesture.Handler`, `Gesture.Type` and `Gesture.Target` needs
to create a functional object (otherwise, we'll end up crashing
later), it was already impossible to create a meaningful
`Gesture`-object from external code.
So let's just make this explicitly clear, and throw some exceptions
on incorrect API-usage.
> Fuse.Nodes: give Fuse.Input.Gestures an internal constructor

- Source/Fuse.Reactive/Fuse.Reactive.unoproj
This isn't awesome, but should allow Fabric and Fuse.Charting to work again after `IObservable` was made public.
> Fuse.Reactive: expose internals to Fuse.Charting and Fabric

- CHANGELOG.md
- Source/Fuse.ImageTools/DotNet.uxl
- Source/Fuse.ImageTools/DotNetImageUtils.uno
- Source/Fuse.ImageTools/Fuse.ImageTools.unoproj
- Source/Fuse.ImageTools/ImageTools.uno
- Source/Fuse.ImageTools/Tests/Fuse.ImageTools.Test.unoproj
- Source/Fuse.ImageTools/Tests/ImageTools.Test.uno
Now this will work on DotNet platforms: 
```
<App>
<JavaScript>
var ImageTools = require("FuseJS/ImageTools");
var Observable = require("FuseJS/Observable");
var imagePath = Observable();
var base64Image =	"iVBORw0KGgoAAAANSUhEUgAAAA8AAAAPAQMAAAABGAcJAAAABlBMVEX9//wAAQATpOzaAAAAH0l" +
"EQVQI12MAAoMHIFLAAYSEwIiJgYGZASrI38AAAwBamgM5VF7xgwAAAABJRU5ErkJggg==";
ImageTools.getImageFromBase64(base64Image)
.then(function(image) {
imagePath.value = image.path;
ImageTools.getBase64FromImage(image).then(function(b64){
console.log(b64);
});
});
module.exports = { test: new Date().toString(), image: imagePath };
</JavaScript>
<Image File="{image}" />
</App>
```
Previously this was unsupported. This is a first PR to add full DotNet compatibility for image tools
> DotNet support for base64 operations in ImageTools 

- Source/Fuse.ImageTools/Tests/ImageTools.Test.uno
Seems the test wasn't MSVC-proof. Dunno why, really.
> Fuse.ImageTools: use MSVC || CMake instead of native

- CHANGELOG.md
- Source/Fuse.Android/AndroidApp.uno
- Source/Fuse.Android/AppRoot.uno
- Source/Fuse.iOS/iOSApp.uno
While profiling apps using `NativeViewHost` in the root I observed that a significant amount of cpu time was spent in [`EndDraw`](https://github.com/fusetools/fuselibs-public/blob/master/Source/Fuse.Controls.Native/iOS/GraphicsView.uno#L108-L112). I guess we are stuck waiting for swap buffers.
Disabling the implicit `GraphicsView` yielded visible performance improvements on both iOS and Android.
This feature is in our backlog and will at some point be an option in `unoproj`
> Feature toggle for implicit GraphicsView

- Source/Fuse.Reactive/Fuse.Reactive.unoproj
Premiumlibs contains a fork of FuseTest from master, which already
have this change. So let's back-port this to the release-branch.
> Fuse.Reactive: add InternalsVisibleTo FuseTest

- Source/Fuse.Elements/Caching/ElementBatch.uno
fixes https://github.com/fusetools/fuselibs/issues/4176
All I did was use the full transform to translate the points of the atlas item. This seems like the right thing to do, but it seems unlikely this was forgotten previously -- am I missing something?  I'm also uncertain how the previous items managed to be rotated at all without this transform multiplication.
This will also break if there are non-flat transforms, but I think the caching excludes those anyway (though it doesn't really have to, since the element's visuals are still flat). Note, this would be broken before as well, so no further problem here.
> Fix for Atlas issue

- CONTRIBUTING.md
We now have a CLA in order, which should be the last hurdle against
allowing external pull-requests. So let's remove this section, so
people won't be scared away.
> CONTRIBUTING: allow external pull-requests

- .travis.yml
- appveyor.yml
Sometimes when CI fails, it's useful to get a stack-trace. So let's ask uno for them.
> CI tracing

- pack.sh
Suffixes that starts with a digit are invalid, and when unlucky, we
can easily get a SHA-1 that does this. So let's add a dev-prefix to
show clearly that this is a development-version of the package.
> pack.sh: add a dev-prefix to unknown branches

- Source/Fuse.Nodes/NameRegistry.uno
- Source/Fuse.Reactive.Bindings/DataBinding.uno
- Source/Fuse.Reactive.Bindings/Instance.uno
A few isolated changes from my memory improvement branch.
Note, the delegate issue (in Instance.uno) is a real problem with our memory manager. We shouldn't need to make this type of change, otherwise our code will become very ugly everywhere delegates are used. I'm including it here as an example, and because it makes a significant difference when profiled.
> Memory improvements

- .travis.yml
This gives us stack-traces when tests fail on osx, which is really useful for debugging failures.
> Travis stacktraces

- appveyor.yml
This argument is bogus, and leads to a couple of warnings like this:
> WARNING: Package 'Source' was not found
So let's drop it. We're not using this arument on Travis CI either.
> appveyor: drop bogus Source-argument

- CHANGELOG.md
- Source/Fuse.Controls.Video/Android/VideoPlayer.uno
Live-streams does not support seeking nor pausing, and Android will
get all mad at us and stuff if we try. Luckily, MediaPlayer.getDuration()
will report -1 for live-streams (and possibly other non-seekable nor
pausable video sources), so we can use that information to stay on
Android's good side.
> Fuse.Controls.Video: do not seek or pause live-streams

- Source/Fuse.Elements/Caching/Cache.uno
A small detail from the stack-trace in fusetools/fuselibs#4211 is
that we seem to fail extra badly here, because of exception-unsafe
code.
Let's fix that part, as we can easily use try-finally for this.
There's no real changelog or docs needed here, as this just cleans
up the error-reporting when there's already something else gone
wrong; users shouldn't usually see this.
> Fuse.Elements: restore state when CompositEffects fail

- Source/Fuse.Controls.Native/iOS/GraphicsView.uno
Calling display on a GLKView will make it immediately draw. Calling setNeedsDisplay will make iOS call display when it decied its the right time (typically when iOS redraws native UI). This also showed up during profiling, maybe this just results in the same time being spent somewhere else. Atleast this cooperates better with iOS
> GraphicsView: Let iOS decide when to call display

- README.md
This adds a short section about how to configure fuse/uno to always pick up the checked-out fuselibs.
I'm not in love with this, but we need this information in some form. Some feedback would be greatly appreciated.
One of the big lacks, is that this doesn't really mention where to put the unoconfig-file, might be confusing to people who aren't used to dealing with unoconfig-files (which is probably most users). But I don't really know what the best advice would be.
We used to have something like this at the root of the repo, which made things work when using `Stuff/uno` from inside the fuselibs-repo. But that was removed by @mortend when the package-manager was introduced. We could consider adding it back...
> README: add section on how to integrate with fuse

- Source/Experimental.TextureLoader/TextureLoaderImpl.cpp.uxl
Bitmaps that are larger than the maximum supported texture-size of
the GPU currently fails to load, producing an OpenGL error, and a
seemingly black texture.
To at least get something related to the image on-screen, let's
down-sample such images until they fit in a texture. We still lie
to the rest of the system about the texture-size later, so layout
etc will use the real size rather than the down-sampled size.
This is only implemented for C++-targets. That might be acceptable
for now, as all our mobile targets, which are the ones that are
likely to have low max-texture sizes. Modern desktop GPUs can do
16k x 16k textures, many mobile phones only support 4096 x 4096.
This is a forward-port from an identical change in the unolibs-repository.
> Experimental.TextureLoader: downsample large bitmaps

- Source/Fuse.Controls.Native/Android/TextEdit.uno
- Source/Fuse.Controls.Primitives/TextControls/MobileTextEdit.uno
Revert the android implementation of https://github.com/fusetools/fuselibs-public/pull/14. As discussed in that PR this feature was sketchy on Android.
Resulting in regressions:
https://github.com/fusetools/ManualTestApp/issues/354
https://github.com/fusetools/ManualTestApp/issues/356
Reverting this feature since there are no easy fix for these issues
> Revert android update caret position feature

- CHANGELOG.md
- Source/Fuse.Controls.Video/iOS/VideoImpl.mm
We currently fail hard on HLS-streams on iOS, where we get a video
size of zero instead of the actual size.
As a half-measure, let's wait for the first resize-event until we
report the video as loaded. This allows us to correctly render HLS
streams that never change the resolution, which is better than
nothing.
> Fuse.Controls.Video: fix video-size for HLS-streams on iOS

- Source/Fuse.Nodes/AppBase.uno
Because rendering happens independently of Update on desktop, desktop would get inconsistent FrameIndex where you would update with frame N, and render with frame N+1. This messes up cache heuristics etc. and causes slow and jittery rendering on desktop.
> Move IncreaseFrameIndex to prior to Update to make it consistent across platforms

- Source/Fuse.Controls.Native/iOS/GraphicsView.uno
This reverts commit 727dc9b9fd621efe6241c0372ca88cd6f91fce04.
I have two cases where this breaks down, at app startup and on device rotation.
1. If the app is very simple (I guess something does not cause invalidations after the first frame), the app will not draw.
2. On device rotation the app will not draw until next invalidation
I read the docs and tried figure out whats causing this, but could not find any easy fix. Lets revert until I can find out whats going on
> Revert "GraphicsView: Let iOS decide when to call display"

- CHANGELOG.md
- Source/Fuse.Common/Tests/FuseTest/TestImageSource.uno
- Source/Fuse.Controls.Primitives/Image.ScriptClass.uno
- Source/Fuse.Controls.Primitives/Tests/Image.Test.uno
- Source/Fuse.Controls.Primitives/Tests/UX/Image.RetryReload.ux
- Source/Fuse.Elements/Resources/HttpImageSource.uno
Fixes https://github.com/fusetools/fuselibs/issues/4227
Adds Image.reload/retry functions
> Reload failed images

- Source/Fuse.Reactive.JavaScript/Docs/JavaScriptRemarks.md
As requested in a ticket: fusetools/fuse-docs#744
> remove a broken link to a stale example

- CHANGELOG.md
- Source/Fuse.Controls.ScrollView/Tests/ScrollingAnimation.Test.uno
- Source/Fuse.Controls.ScrollView/Tests/UX/ScrollingAnimation.FromTo.ux
- Source/Fuse.Controls.ScrollView/Triggers/ScrollingAnimation.uno
We have to update the animation state if From or To changes, if not the animation can get out of sync since it only updates when the scrollview is scrolls.
> ScrollingAnimation: Update animation if From or To changes

- Source/Fuse.Controls.ScrollView/Scroller.uno
If there is no gesture present, I assume that the GestureRequest should be Ignore
> Scroller: Fix nullref in OnPointerMoved

- CHANGELOG.md
- Source/Fuse.Elements/Caching/ElementAtlas.uno
- Source/Fuse.Elements/Tests/Caching.Test.uno
- Source/Fuse.Elements/Tests/UX/Caching.BorderIssue.ux
If a batched element has ClipToBounds=True, but contents that overflow
it, we didn't set up the scissor-box. This lead to rendering outside the
allocated part of the element-atlas, and could corrupt the rendering of
other elements.
Add a test-case to make sure this doesn't regress in the future.
> Fuse.Elements: set scissor-box if ClipToBounds

- CHANGELOG.md
- Source/Fuse.Controls.ScrollView/Scroller.uno
> Scroller: Fix possible nullref when capture is lost

- CHANGELOG.md
- Source/Fuse.Controls.Panels/GraphicsView.ux.uno
One some Android devices we observe that the app is invisible when it enters forground. I guess we hit the rotation issue, setting rotationHackRedrawCount fixes the issue...
> GraphicsView: Make sure App redraws when entering foreground

- Source/Fuse.Nodes/DrawContext.uno
This TODO comment seems like it is not supposed to be documentation.
> Change unintentional doc-comment to regular comment

- .travis.yml
This seems to make travis-builds quite a bit faster:
|            | cold cache    | warm cache    |
|-----------:|:--------------|:--------------|
| **before** | 33 min 54 sec | 19 min 58 sec |
| **after**  | 43 min 58 sec | 14 min 59 sec |
Unfortunately, the numbers above are quite unreliable, as variations in builders and builder-load seems to fluctuate wildly. Especially the cold cache numbers seems questionable.
> travis builtin-ccache

- Source/Fuse.Triggers/Docs/StateGroup.md
- Source/Fuse.Triggers/State.ScriptClass.uno
- Source/Fuse.Triggers/State.uno
- Source/Fuse.Triggers/StateGroup.uno
- Consolidate State and StateGroup docs into a single article (that lives on StateGroup, linked to in State)
- Add a more tutorial-y introduction
- Add example of using the `TransitionState` action
- Add example of the JavaScript APIs of `State` and `StateGroup`.
> Rewrite StateGroup docs

- Source/Fuse.Controls.Video/iOS/VideoImpl.mm
> iOS: Fix crashes caused by ObjC reference loop

- Source/Fuse.Elements/Caching/ElementAtlas.uno
- Source/Fuse.Elements/Caching/ElementBatch.uno
- Source/Fuse.Elements/Caching/ElementBatcher.uno
While working to fix https://github.com/fusetools/fuselibs/issues/4213 (fixed proper in https://github.com/fusetools/fuselibs/issues/4213), @kusma and I found a bunch of code that could use some clarification/small optimizations.
Particularly we renamed a `_rect` to `AtlasRect` on `Fuse.Elements.ElementBatchEntry` for clarity, introduced the `DrawingOffset` field, and moved some duplicated calculation out of `ElementBatch`, as we already had done these calculations when placing elements inside their atlases, and could just pass the data along with these fields.
We also realized that we had an extra half-pixel more padding around all of the batched elements than we needed, so I went ahead and choked up on that. This is both a minor speed optimization and an additional safety net in case we …
> Adjust batched element rect padding and some small cleanups/optimizations

- CHANGELOG.md
- Source/Fuse.Launcher.Email/Email/EmailLauncher.uno
- Source/Fuse.Launcher.Maps/Maps/JS.uno
- Source/Fuse.Launcher.Maps/Maps/MapsLauncher.uno
- Tests/ManualTests/ManualTestingApp/MainView.ux
- Tests/ManualTests/ManualTestingApp/ManualTestingApp.unoproj
- Tests/ManualTests/ManualTestingApp/Singles/Launchers.ux
The launchers doesn't always encode URIs correctly, which cause issues on iOS. See #126 for more details.
Unfortunately, I don't have an iOS-device at hand now, but I've verified that things still works as it should on Android. So if someone else could test this on iOS, that would be great.
This also fixes fusetools/fuse-docs#790
> Launcher encoding issues

- Source/Fuse.Maps/Docs/Brief.md
Our markdown renderer seems to not handle code blocks inside blockquotes.
This works around the issue by removing the blockquote.
> Unbork MapView docs

- CHANGELOG.md
- Source/Fuse.ImageTools/iOS/ImagePicker.m
This PR fixes a crash introduced with iOS 10.1 where modal view controller invoke and dismiss *must* happen on UI thread. Fixes #128 
> Fuse.Camera iOS 10.1+ crash fix

- CHANGELOG.md
- Source/Fuse.Animations/Attract.uno
- Source/Fuse.Animations/Fuse.Animations.unoproj
- Source/Fuse.Animations/Tests/Attract.Test.uno
- Source/Fuse.Animations/Tests/Fuse.Animations.Test.unoproj
- Source/Fuse.Animations/Tests/UX/Attract.Test.ux
- Source/Fuse.Motion/DestinationBehavior.uno
- Source/Fuse.Motion/DestinationMotion.uno
- Source/Fuse.Motion/Fuse.Motion.unoproj
`attract` was always meant for fuselibs but due to release timing ended up in premiumlibs. This moves it to the correct place now.
> migrated `attract` from premiumlibs into fuselibs

- CHANGELOG.md
- Source/Fuse.ImageTools/Android/ImageUtils.java
This PR reimplements handling for the KEEP_ASPECT resize mode in ImageUtils that I apparently overlooked at some point when trying to fix OOM crashes. Fixes https://github.com/fusetools/ManualTestApp/issues/358
> Feature android camera buffer fix

- Source/Fuse.Selection/Docs/example.md
Here: https://www.fusetools.com/docs/fuse/selection/selection#section-examples
The example treats list Observable as a single-value Observable, and that's wrong.
It also relies on the Selection API replacing the first value every time the selection changes, which might currently be true, but probably isn't correct either.
> fixing the example for working with Selection API

- CHANGELOG.md
- Source/Fuse.Elements/Caching/ElementAtlas.uno
PinAndValidate sets rendertarget and calls FillFramebuffer, but often nothing is actually drawn. This postpones setting the rendertarget until actually needed.
Causes significant speedups on some platofrms.
> ElementAtlas: Don't set rendertarget redundantly

- CHANGELOG.md
- Source/Fuse.Controls.Panels/NativeViewHost.uno
- Source/Fuse.Controls.Panels/SingleViewHost.uno
- Source/Fuse.Nodes/Visual.Transform.uno
- Source/Fuse.Nodes/Visual.WorldTransformInvalidated.uno
- Source/Fuse.Nodes/Visual.uno
Optimized invalidation strategy for transforms, to avoid subtree traversion. This improves performance generally when animating large subtrees (e.g. scrollviews).
This required a new implementation strategy for emitting the WorldTransformInvalidated event, as we are no longer traversing the subtree eagerly to generate these events.
@mortoray - please evaluate carefully whether we have enough test coverage to safely make this optimization. If not, any help to extend the test coverage is highly appreciated.
> Optimized how WorldTransform is invalidated

- Source/Fuse.Common/Tests/Fuse.Common.Test/FastMatrix.Test.uno
I wrote these tests a few weeks ago in preparation for an optimization effort for our FastMatrix implementation. Maybe it would be nice to just merged them now since it looks like there are PRs coming in that touch this area
> FastMatrix: Add tests covering its interface

- CHANGELOG.md
- Source/Fuse.Common/FastMatrix.uno
- Source/Fuse.Nodes/Visual.Transform.uno
The WindowToLocal function is called frequently while processing pointer events for hit testing. The old implementation did a full float4x4 vector transform for each node in the view heirarchy. This optimization delegates to FastMatrix to transform the vector, taking a fast path in the common case of translation-only.
> Optimize WindowToLocal by using FastMatrix to transform vectors

- Source/Fuse.Drawing.Surface/Android/Surface.uno
Fixes an issue with imagefill on Android when using a stroke. Visible in the Manual test app on the "strokes and fills" page.
> revert changes to imagefill on Android to ensure strokes are obeyed

- CHANGELOG.md
- Source/Fuse.Nodes/DrawContext.uno
These GL errors should never trigger (indicates bugs in fuselibs, or custom user GL code messing up things). Introduced `-DDEBUG_GL` if the user wants the old behavior or to enable debugging in the future.
Achieves a 0.5-1.0ms speedup on my android phone per frame in the test case (a big app), and ~5ms speedup on my desktop (!!)
> Optimization: Don't check for GL errors all the time

- CHANGELOG.md
- Source/Fuse.Controls.Panels/NativeViewHost.uno
- Source/Fuse.Controls.Panels/SingleViewHost.uno
- Source/Fuse.Nodes/Visual.Transform.uno
- Source/Fuse.Nodes/Visual.WorldTransformInvalidated.uno
- Source/Fuse.Nodes/Visual.uno
Avoids subtree traversion on world transform invalidation. This improves performance generally when animating large subtrees (e.g. scrollviews).
This is a restoration of what was reverted in https://github.com/fusetools/fuselibs-public/commit/da640d44aa6633c51ea8578a09ae92a1404dc4f5
Fixes https://github.com/fusetools/fuselibs-public/issues/154
> (restored) Optimized invalidation strategy for transforms

- Source/Fuse.Desktop/DesktopApp.uno
- Source/Fuse.Nodes/AppBase.uno
Doing things like InvalidateVisual in response to input requires that
the UpdateManager.FrameIndex was increased right after drawing, because
otherwise the frame index will be the same when the input happens,
causing elements that were validated the same frame to not be
invalidated.
This problem was introduced in 81eae3e, where another similar issue
was worked around. This should fix both cases.
Fixes issue #182
Unfortunately, this doesn't seem to be possible to write a test-case for,
because the logic happens in AppBase, and we don't have an instance
of that during `uno test`.
> make sure IncreaseFrameIndex happens right after draw

- Source/Fuse.Controls.Native/iOS/InputDispatch.uno
- Tests/ManualTests/ManualTestingApp/Multitouch/Multitouch.ux.uno
There is no public API on iOS that will tell us how many simultanious touches are supported. When writing this code I believed that 10 fingers were the max, but when testing this on iPad I found that iPad supports 11 simultanious touches. Also according to the internet iPhone supports only 5 simultanious touches.
Refactoring to just use a list instead so that we can support an arbitrary number of active pointers
> iOS: Make InputDispatch expand number of activePointers

- Source/Fuse.Reactive.Bindings/Instance.API.uno
- Source/Fuse.Reactive.Bindings/Tests/EachTest.uno
- Source/Fuse.Reactive.Bindings/Tests/UX/Each.TemplateSource.ux
Charting depended on a particular initialization order (bad), this would correct that, but I also fixed Charting. This feature is not strictly required but it costs nothing to add (it may also address a very unlikely backwards incompatilbe issue with my fix for the memory loop on TemplateSource)
- [-] Changelog : No effective change for users, addressed internal issue.
> allows TemplateSource change post rooting. 

- CHANGELOG.md
- Source/Fuse.Share/Fuse.Share.unoproj
- Source/Fuse.Share/ShareModule.uno
- Source/Fuse.Share/ios/iOSShareImpl.uno
iOS design guidelines requires a point of reference for use as the popover spawn origin. Added an optional argument to the share api for passing a UX element for use as the spawn origin. If the user does not provide this, emit a UserError and the popover will spawn in a default location
Not to happy about this fix. Makes the share API clunky. I think the Share API should be UX based instead of JS
> Fuse.Share: Fixed iPad crash bug

- CHANGELOG.md
- Source/Fuse.Controls.Panels/LayoutControl.uno
- Source/Fuse.Controls.Panels/Panel.Freeze.uno
- Source/Fuse.Elements/Element.Effects.uno
When LayoutControl and Panel were split back in the days, it seems the FastTrackDrawWithOpacity was forgotten. The result has been that e.g. images don't use the fast track when they have nontrivial opacity, resulting in a redundant framebuffer allocation and render to texture.
This fixes it.
> Feature repair fast track draw with opacity

- CHANGELOG.md
- Source/Fuse.Marshal/Marshal.Cast.uno
- Source/Fuse.Marshal/Marshal.Compute.uno
- Source/Fuse.Marshal/Marshal.Vector.uno
- Source/Fuse.Reactive.Expressions/VarArgFunction.uno
- Source/Fuse.Reactive.Expressions/VectorFunctions.uno
- Source/Fuse.Reactive.JavaScript/Tests/UX/VarArgs.ux
- Source/Fuse.Reactive.JavaScript/Tests/VarArgsTest.uno
- Stuff/uno.stuff
Inheriting  from the `Fuse.Reactive.VarArgFunction` class gives variable argument support.
The classes `Vector2`, `Vector3` and `Vector4` in `Fuse.Reactive` are now removed and replaced with the general purpose, variable-argument version `Vector` instead. This ensures vectors of any length are treated the same way. These changes are covered by lots of existing tests.
Needs new Uno stuff with https://github.com/fusetools/uno/pull/1223
> Support for variable arguments to UX functions.

- CHANGELOG.md
- Source/Fuse.Common/Json.Parse.uno
- Source/Fuse.Common/NameValuePair.uno
- Source/Fuse.Reactive.Expressions/NameValuePair.uno
- Source/Fuse.Reactive.JavaScript/Tests/UX/NameValuePair.ux
- Source/Fuse.Reactive.JavaScript/Tests/Various.uno
Adds support for Name-value pairs.
Requires new Uno stuff with https://github.com/fusetools/uno/pull/1222
This feature enables things like `<Button Clicked="goto('settings', {enabled: true})" />`
> UX expressions name-value pairs

- CHANGELOG.md
- Source/Fuse.Controls.Primitives/Image.uno
If the ImageContainer emits any of its events we want to know, must move the IsRooted = true to after subscribing to the events since that might make it emit events.
Fixes https://github.com/fusetools/fuselibs-public/issues/164. Caused by the SourceChanged event firing before we had subscribed
> Image: set container IsRooted to true after subscribing for events

- Source/Fuse.Reactive.JavaScript/JavaScript.uno
- Source/Fuse.Testing/JavaScriptTest.uno
Since RootableScriptModule is `internal` i made JavaScript._scriptModule `protected internal`.
The unodoc backend complains otherwise even though the uno compiler doesn't for some reason.
> fixed visibility error on JavaScript member

- CHANGELOG.md
- Source/Fuse.Nodes/Node.ScriptClass.uno
- Source/Fuse.Reactive.JavaScript/Tests/Various.uno
This seems to happen during shutdown in some tests, if enough
objects are being disposed. So let's try to survive in this case.
This was noticed while adding some disposing to a test, so let's
add that here also, so we have a chance to notice similar regressions
in this functionality in the future.
> Fuse.Nodes: survive if there's no DataWatcher

- Source/Fuse.Reactive.Bindings/DataBinding.uno
- Source/Fuse.Reactive.Bindings/EventBinding.uno
This allows new features to use `IExpression` as data type for properties without hitting the legacy code path that always interprets those expressions in data space
This must be merged along with https://github.com/fusetools/uno/pull/1224
> Made DataBinding.Key UXVerbatim to interpret in data space

- appveyor.yml
This is a dirty work-around for a current incident on Appveyor,
and should be removed again once the problem has been solved in
their end.
For more information, see:
http://status.appveyor.com/incidents/m2vdvw39kdk8
> appveyor: temporarily direct azure CDN to europe

- Source/Fuse.Reactive.Expressions/LookUp.uno
- Source/Fuse.Reactive.JavaScript/Tests/UXExpressionsTest.uno
Some subscriptions (like constant values that cannot change) simply
return a null-pointer, to avoid having to create needless objects.
This is considered legal by the expression-system.
However, the newly added array-lookup expression didn't take this
into account. Let's do this, by simply not disposing null-pointers.
This was discovered while adding test-disposal to the test for this
feature, which triggers the issue. So let's add that disposal around
this test now, so we'll detect if this regresses in the future. Some
minor clean-ups are also included.
> Fuse.Reactive: survive Dispose after null-subscriptions

- Source/Fuse.Scripting.V8/V8SimpleExtensions.uno
It's nice to have methods that return a reference to the object it
works on so you can chain operations. However, release should never
be used like that, because it's effectively a free-method. Chaining
it like that will effectively be a use-after-free.
Luckily, nobody uses the return-value of the method, but let's just
get rid of it so nobody thinks this is a good idea in the future.
> Fuse.Scripting.V8: do not encourage use-after-free

- Source/Fuse.Scripting.V8/Array.uno
- Source/Fuse.Scripting.V8/Context.uno
- Source/Fuse.Scripting.V8/Function.uno
- Source/Fuse.Scripting.V8/Object.uno
- Source/Fuse.Scripting/Tests/Scripting.uno
Sometimes when releasing JS-values after a context has been disposed,
we get an `AccessViolationException`, probably due to using different
contexts (or rather, null-contexts) than the actual context used.
the `_context == null`-case seems to be a similarly mis-guided attempt
at surviving, where we just end up releasing in a collected context.
Since disposing sets the _context-member to the same value as the
`_context == null`-case fudged it with, these two cases should actually
be the same, and just as potentially crashy.
Let's instead assume that disposing a context correctly destroy all of
its resources. There's no way we can do any better, because the handle
to the context is lost at this point.
This fixes #237
Unfortuantely, I was unable to come up with a way of testing this, as
it …
> Fuse.Scripting.V8: do not release on the wrong context

- Source/Fuse.Controls.ScrollView/ScrollView.Layout.uno
The problem was that an internal enum was made visible through a protected
member which takes that type as an argument. Changing the visibility of
the member to internal instead.
Note: This only caused an issue for the docs generator.
> Fix a visibility error

- Source/Fuse.Controls.Native/Android/TextEdit.uno
All android builds are now gradle builds. 
Also uno will soon be removing the GRADLE declaration and at that point this code would break.
No changelog, documentation or tests as there is no change to current functionality
> Remove use of GRADLE declaration

- Source/Fuse.Reactive.Expressions/LookUp.uno
The subscription-fields vs subscribe-calls were swapped. In reality
this doesn't matter, because they are only kept around to be disposed.
But let's clean up this in case it becomes significant in the future.
Or just for clarity.
> Fuse.Reactive.Expressions: correct typo

- CHANGELOG.md
- Source/Fuse.Nodes/VisualBounds.uno
Takes advantage of FastMatrix to avoid a ridiculous amount of float4x4 * float4 transforms of trivial matrixes.
Unrolls min/max of vectors to avoid lots of redundant compares.
Large performance gains in cases with many Children on a visual.
- [-] Tests
> Optimizes VisualBounds.BoxTransform

- Source/Fuse.Reactive.Bindings/Instance.WindowItems.uno
The move command is slower, so for Each users that don't require move this will avoid some of the overhead introduced by 1.2.
- [-] Changelog - no public change
- [-] Documentation - no api change
- [-] Tests -- covered by existing tests
> Optmize call to InsertNodes or InsertOrMoveNodes

- README.md
This just cleans up a couple of things in our readme-file:
- explain what the scripts does rather than how
- wrap long lines like is already done elsewhere
> readme-cleanups

- Source/Fuse.Nodes/Node.Bindings.uno
- Source/Fuse.Nodes/Tests/Fuse.Nodes.Test/Node.Test.uno
We unroot if there's only one, so it would be reasonable to expect
that we unroot if there's more.
This was found by code-inspection, and seems to have been like this
for a long time.
I also can't find a call-site for this, so it's probably never triggered
in practice. This is why I decided not to include a changelog-entry.
> Fuse.Nodes: unroot binding when removing

- Source/Fuse.Elements/Caching/ElementAtlas.uno
- Source/Fuse.Elements/Caching/ElementBatch.uno
- Source/Fuse.Elements/Tests/ElementBatcher.Test.uno
- Source/Fuse.Elements/Tests/UX/ElementBatcher.MoveAfterFirstDraw.ux
These changes lead to a bad situation where things ended up drawn in
the wrong location.
Fixes issue #296
This reverts parts of commit 7f89944faa3ddfa906a79ce980ba2f7742eaa3d6.
> Fuse.Elements: revert ill-adviced DrawingOffset changes

- Tests/ManualTests/ManualTestingApp/PointerAndMouse/PointerAndMouse.ux.uno
`DateTime.Now` now returns a DateTime-struct, not a ZonedDateTime as
it did before. And our DateTime-struct doesn't (yet) support the
`Milliseconds`-property.
Having this test randomize based on time serves no real purpose, we
can just randomize with some constant instead. Having different
colors per run isn't a big plus.
Another alternative would be to use the LocalDateTime-class, but the
plan is to make that one obsolete at some later point. So it doesn't
feel like it's worth the hassle just for a rather useless feature.
> ManualTestingApp: do not randomize with time

- Tests/ManualTests/ManualTestingApp/Clock/Clock.ux.uno
We've changed the Uno API for DateTime.Now from returning a
ZonedDateTime to returning a struct DateTime, which is severely
limited. This is so we can add DateTime to our public UX-visible
API without pulling in a lot of timezone-stuff for all future.
So, until DateTime is a bit more capable, we need to use
ZonedDateTime instead.
In the great future, this will probably have to get reverted.
> ManualTestingApp: use ZonedDateTime.Now instead of DateTime.Now

- Documentation/CodingStyle.md
We're far from consistent in how we're writing things like this, but
there's already a pretty clear presedence set:
```
$ git grep "[a-zA-Z0-9_]\+ + [a-zA-Z0-9_]\+" -- *.uno | wc -l
675
$ git grep "[a-zA-Z0-9_]\++[a-zA-Z0-9_]\+" -- *.uno | wc -l
147
$ git grep "if ([^ ]" -- *.uno | wc -l
5855
$ git grep "if([^ ]" -- *.uno | wc -l
273
$ git grep "if( [^ ]" -- *.uno | wc -l
35
$ git grep "if ( [^ ]" -- *.uno | wc -l
28
```
So, the 'a + b' pattern is more than 4 times as popular as the 'a+b'
pattern, and the 'if (foo)'-pattern is more than 20 times(!) as popular
as the second most popular alternative.
The same patterns repeats itself as the by-far more popular for other
operators (at least for '*', see notice below) and keywords (like
'while', 'for' and 'switch') as well. So this pretty much …
> Documentation: add point about spaces around operators

- CHANGELOG.md
- Source/Fuse.Text/icu/i18n/unicode/uconfig.h
- Source/Fuse.Text/icu/iOS.stuff
When using both -DUSE_HARFBUZZ and -DCOCOAPODS and some particular
pods, we end up linking to the wrong, AppStore banned symbols
instead of our bundled copy of ICU.
The approach of providing multiple copies of the same symbols, is
fragile, and some Cocoapods project re-writing ends up biting us
here. So let's get out of the "same symbols"-business, and use
ICUs built-in symbol-renaming mechanism instead.
Since we're using the system-provided copy of ICU on macOS, we
need to only do this for iPhone-builds.
The scripts to build and package ICU can be found here (sorry in
advance to people outside the fusetools organization, this repo
is currently private):
https://github.com/fusetools/uno-base/tree/build-icu
> Fuse.Text: fix problem with ICU-clashing symbols

- README.md
Some Markdown parsers don't deal well with parens inside an URL, so
let's just URL-encode these (like they should have been in the first
place).
> README: urlencode parens in TeamCity badge

- Source/Fuse.Reactive.JavaScript/ThreadWorker.uno
While debugging some other issues, I was instrumenting CheckAndThrow to be able to see an inner exception's stack trace. While in there I noticed the logic behaves a bit strangely. CheckAndThrow is supposed to check for pending JS thread exceptions and report them, if any. If there's a single exception, it should be thrown; if there are multiple, the last one will be thrown, and the rest reported. With the current logic, since we report `next`, it looks like we'll report _all_ exceptions _and_ throw the last one, rather than only reporting the first ones and throwing the last one, _if_ there are multiple exceptions. I'm guessing this was a simple mistake when writing the code originally, so let's fix that.
> Fix logical error in ThreadWorker.CheckAndThrow

- Source/Fuse.Reactive.JavaScript/ThreadWorker.Wrapping.uno
Currently we're trying to keep our DateTime API surface as minimal as possible, which means not exposing ways of dealing with/converting times/dates that aren't in UTC. While assuming UTC makes some of our impl's simpler, we should try to at least document where fuselibs code should change if/when the API gets filled in more to ensure correctness, and since I'm in the area while working on similar features, I thought I'd add this here.
> Add note about DateTime/Date conversion

- CHANGELOG.md
- Source/Fuse.Controls.Primitives/TextControls/MobileTextEdit.uno
- Tests/ManualTests/ManualTestingApp/Singles/TextInputPage.ux
Text alignment always broke the first time drawing due to the internal text alignment state in TextView not being valid. The previous workaround was to align the text ourselves with a grid. This aligned the text correct as long as it did not overflow its layout bounds. By reading the source code for TextView I figured out what to do to make the internal state update appropriately. See the code for more details.
> Android.TextEdit: fix TextEditRenderer alignment issues

- Source/Fuse.Reactive.JavaScript/Tests/DateMarshalTest.uno
- Source/Fuse.Reactive.JavaScript/Tests/UX/DateMarshal.UnixEpochDateRoundTrip.ux
- Source/Fuse.Reactive.JavaScript/ThreadWorker.Wrapping.uno
Previously, this code would assume the result of `getTime` on a JS `Date` object would be a `double`. However, one critical value does not satisfy this assumption: the Unix epoch. This is because the result is 0, which is representable as an integer.
The fix is to wrap the value from `getTime`. We can assume the wrapped value is a `double`, so we cast to that from the resulting object, then cast its value to `long`.
I was sure I had tested this initially, and I probably did when writing the code, but since I wrote tests after, that case was likely not covered when adjusting the casting logic a bit while cleaning up. Whoops!
> Wrap JS Date time value when marshalling to DateTime

- appveyor.yml
The azure CDN-problem has been fixed a while back, so let's
remove this horrible hack ;)
This reverts commit 31748b90c4e11389d8f446dc592f144090d94d37.
> Revert "appveyor: temporarily direct azure CDN to europe"

- Source/Fuse.Reactive.JavaScript/ThreadWorker.ScriptClass.uno
Not to familiar with this code, but it seems obvious that a return is missing here? Also, this fixed my ScriptMethods that always returned undefined :)
> ThreadWorker.ScriptClass: Add missing return

- Source/Fuse.Reactive.JavaScript/ThreadWorker.Wrapping.uno
Came up while writing tests for Fuse.Scripting that Scripting.Object's and Scripting.Array's gets wrapped as external objects
> ThreadWorker: Add missing if tests in Unwrap

- .travis.xcconfig
- .travis.yml
So far, we haven't been building manual testing app on pull-requests, because we had issues with too long build times. Now that this has been solved, we should be able to do this.
Note that building ManualTestingApp doesn't actually work right now, due to a uno-bug. But another uno-bug cancels that one out, so uno doesn't report an error. Both of these bugs are in the process of being fixed in uno master.
> travis: build manual testing app

- .travis.yml
We need to use Mono 4.4.2 to build ManualTestingApp for iOS. The only reason
why this seemed to work when the PR was pulled, was that there was a uno-bug
that prevented the build-error from being reported.
This PR also gets rid of ccache, as it's no longer needed (and cause issues).
Sadly, it makes the build a bit slower. I'll experiment a bit more with the caching
later to try to mitigate this a bit. But for now, I'd prefer a master that actually
builds.
> Travis: use Mono 4.4.2

- Source/Fuse.Marshal/Marshal.Convert.uno
- Source/Fuse.Marshal/Tests/MarshalTest.uno
Add support to the marshal for supporting conversion to whatever type the object already is, and add a small optimization for reference types that can skip many of the value type-specific typechecks.
> Make Fuse.Marshal.TryConvertTo able to convert to self

- CHANGELOG.md
- Source/Fuse.Elements/Caching/ElementAtlas.uno
- Source/Fuse.Elements/Tests/ElementBatcher.Test.uno
- Source/Fuse.Elements/Tests/UX/ElementBatcher.ZeroSizeAfterFirstDraw.ux
In 7f89944, we incorrectly assumed that this could never happen.
If you look at the callsite, you can see that this exact behavior
is expected.
This is not ideal behavior, but let's restore the old behavior for
now. We can rework this mechanism later for master.
While we're at it, add a test that picks up this breakage.
Fixes issue #375
> Fuse.Elements: revert bad change

- Tests/auto-test-app.sh
- Tests/build_test_apps.sh
- Tests/compile-packages.sh
- performance.sh
- test.sh
The "Create Manual Testing Apps" build step in TeamCity stopped working when we switched to using Xamarin.Mac in Uno. Running 64-bit mono makes this work again.
> use 64-bit mono in scripts

- CHANGELOG.md
- Source/Fuse.Reactive.Expressions/StringFunctions.uno
- Source/Fuse.Reactive.Expressions/Tests/StringFunctions.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/UX/StringFunctions.Simple.ux
toUpper and toLower UX-expression functions would crash if they were
given null-input. Other UX-expressions seems to generally return null
on null-input, rather than crashing. So let's follow that example.
This fixes issue #367.
> Fuse.Reactive.Expressions: do not crash on null-input

- CHANGELOG.md
- Source/Fuse.Common/FastMatrix.uno
- Source/Fuse.Elements/Caching/ElementBatch.uno
- Source/Fuse.Nodes/VisualBounds.uno
This is a back-port of @Duckers's render bounds optimisations for the ElementBatcher. This targets release-1.2 instead of master.
This contains the changes in #280 as well as #289
> optimize calc render bounds backport

- Source/Fuse.Elements/Caching/ElementBatch.uno
- Source/Fuse.Elements/Tests/ElementBatch.Test.uno
- Source/Fuse.Elements/Tests/Fuse.Elements.Test.unoproj
We need to actually take the union of all elements, not element
zero every time.
While we're at it, add a test-case that triggers in this case.
Fixes issue #399
> Fuse.Elements: fix a typo-bug

- Source/Experimental.TextureLoader/CIL/CilTextureLoader.uno
- Source/Fuse.Common/Tests/FuseTest/TestFramebuffer.uno
- Source/Fuse.Controls.Native/NativeRenderer.uno
- Source/Fuse.Controls.Video/CIL/VideoImpl.uno
- Source/Fuse.Drawing.Surface/Android/GraphicsSurface.uno
- Source/Fuse.Drawing.Surface/CoreGraphics/CoreGraphicsSurface.uno
- Source/Fuse.Drawing.Surface/CoreGraphics/GraphicsSurface.uno
- Source/Fuse.Drawing.Surface/DotNetSurface.uno
- Source/Fuse.iOS.TextRenderer/TextRenderer.uno
We need to make sure that unpack/pack alignments are set to 1 when uploading / downloading images to GL, otherwise corruption can occur.
Seems we we've been lucky and had one of the code-sites that sets these ran before every upload, but I don't think this is guaranteed.
Fixes fusetools/fuselibs#3888.
> GL pack/unpack alignment

- Source/Fuse.Common/Tests/FuseTest/TestFramebuffer.uno
- Source/Fuse.Elements/Tests/ElementBatcher.Test.uno
- Source/Fuse.Elements/Tests/Rendering.Test.uno
All other assert-functions take their expected value as the first
one, so let's switch around the arguments to
TestFramebuffer.AssertSolidRectangle to make it consistent.
> Fuse.Common: make assert signature consistent

- Source/Fuse.Reactive.JavaScript/FuseJS/Http.uno
Due to mono throwing a NotImplentedException when trying to set cache behavior, the FuseJS/Http module disables caching for mono targets.
However, it only checks if we're running in preview, resulting in a crash when running dotnet build on osx, as well as disabling cache on non-mono platforms that actually support it.
This PR replaces the check for preview with a check for `HOST_OSX && DOTNET`, which should only trigger when running in mono on OSX.
> Fix incorrect check for mono

- Source/Fuse.Common/Tests/FuseTest/TestRootNode.uno
- Source/Fuse.Controls.Panels/Tests/Grid.Test.uno
- Source/Fuse.Controls.ScrollView/ScrollViewPager.uno
- Source/Fuse.Controls/Tests/Panel.Test.uno
- Source/Fuse.Nodes/Visual.ZOrder.Obsolete.uno
- Source/Fuse.Nodes/Visual.ZOrder.uno
- Source/Fuse.Reactive.Bindings/Tests/EachTest.uno
- Source/Fuse.Reactive.Bindings/Tests/MatchCaseTest.uno
- Source/Fuse.Reactive.JavaScript/Tests/Various.uno
Here's a few patches to reduce warnings when building tests.
This also un-obsolete Visual.GetZOrderChild, because it's needed sometimes, and there's non-internal replacement.
> Reduce warnings

- test.sh
This fixes the script on macOS after it broke in 952a37ba33c939f7bae29a2b3e1dd148ece1f78f.
> test.sh: remove .exe to call x-platform wrapper, fixes issue on macOS

- Tests/Benchmark/Benchmark.unoproj
- Tests/Benchmark/MainView.ux
- Tests/Benchmark/Utils/FrameIndex.uno
- Tests/Benchmark/Utils/ProfilePanel.uno
- Tests/Benchmark/Utils/TestRunner.uno
It's often useful to keep track of some performance cases over time,
so let's add a framework where it's easy to add cases and run them.
This is a pretty basic app, and we should probably need to both add
counters and tweak current functionality before this is very useful.
But at least it's a start.
> add benchmark application

- test.sh
A long time ago, in a galaxy fa... Well, about a year ago, this
script was replaced, and nobody updated this reference. Somehow
nobody noticed until now, go figure.
> fixup test.sh

- Source/Fuse.Scripting/Tests/ScriptClass/ScriptPromiseTests.uno
They could fail due to test-setup after calling TestRootPanel.CreateWithChild(). That could end up running the JS code before the whole test was hooked up
> ScriptPromise: Fix randomly failing test

- Source/Fuse.FileSystem/FileSystemModule.uno
The `copy` method had mistakenly be called `move` in the comments section, so it never appeared on the docs. Fixed that.
> Fix filesystem docs: copy

- CHANGELOG.md
- Source/Fuse.Drawing.Primitives/Rectangle.uno
Use a scale to deal with FP16 shader precision in the Rectangle renderer
> Rectangle: deal with FP16 shader precision errors

- CHANGELOG.md
- Source/Fuse.Common/Internal/AndroidSystemFont.uno
`Default` returns null when `_families.Count == 0`, however
`GetFallback` always passed the result of `Default` straight to
`AddRange` which on some devices (Android Oreo in this case) caused
the app to crash.
Havent added a changelog as this as a bugfix. However it may be worth one as it fixes Fuse builds for android 8
> Handle AndroidSystemFont Default being null

- CHANGELOG.md
- Source/Fuse.Reactive.JavaScript/JavaScript.uno
- Source/Fuse.Reactive.JavaScript/ModuleInstance.uno
- Source/Fuse.Reactive.JavaScript/RootableScriptModule.uno
- Source/Fuse.Reactive.JavaScript/Tests/Fuse.Reactive.JavaScript.Test.unoproj
- Source/Fuse.Reactive.JavaScript/Tests/OptionalExplicit.js
- Source/Fuse.Reactive.JavaScript/Tests/UX/OptionalExplicit.ux
- Source/Fuse.Reactive.JavaScript/Tests/Various.Test.uno
- Source/Fuse.Scripting/ScriptModule.Evaluate.uno
- Source/Fuse.Scripting/ScriptModule.Require.uno
Symbols declared with ux:Name, ux:Dependency or dep are in this PR also available to require() for <JavaScript> modules using a `ux:` prefix.
>  JavaScript: optional explicit require() of UX symbols

- CHANGELOG.md
- Source/Fuse.Common/Tests/FuseTest/ObservableList.uno
- Source/Fuse.Controls.Navigation/NavigationControl.Pages.uno
- Source/Fuse.Controls.Navigation/NavigationControl.uno
- Source/Fuse.Controls.Navigation/Navigator.uno
- Source/Fuse.Controls.Navigation/PageControl.Pages.uno
- Source/Fuse.Controls.Navigation/Tests/Router.Test.uno
- Source/Fuse.Controls.Navigation/Tests/UX/Router.ObservableGoBack.ux
- Source/Fuse.Navigation/Fuse.Navigation.unoproj
- Source/Fuse.Navigation/IRouterOutlet.uno
- Source/Fuse.Navigation/PageData.uno
- Source/Fuse.Navigation/Router.uno
- Source/Fuse.Nodes/Node.DataContext.uno
- Source/Fuse.Reactive/Fuse.Reactive.unoproj
- Source/Fuse.Reactive/ObserverMap.uno
- Source/Fuse.Reactive/Tests/Fuse.Reactive.Test.unoproj
- Source/Fuse.Reactive/Tests/ObserverMap.Test.uno
This allows GoBack and WhileCanGoBack to work with a model bound to `NavigationControl.PageHistory`. The full functionality is incomplete, but this represents a useful first step and makes the most invasive parts of the changes.
- [-] Documentation -  no visible API changes. This will require extensive documentation once the Model stuff is released.
> Two-way binding of Router/Model pages. GoBack support

- Source/Fuse.Scripting/ScriptClass.uno
- Source/Fuse.Scripting/Tests/ScriptClass/ScriptPromise.Test.uno
This should have been there in the firstplace. Its needed for Wrapping/Unwrapping incoming arguments from JS.
`ScriptPromise` is not released yet, so we are not breaking any APIs
> ScriptPromise: add Context as argument on FutureFactory

- CHANGELOG.md
- Source/Fuse.Reactive.JavaScript/ThreadWorker.ScriptClass.uno
- Source/Fuse.Scripting/ScriptClass.uno
- Source/Fuse.Scripting/Tests/ScriptClass/ScriptReadonlyProperty.Test.uno
- Source/Fuse.Scripting/Tests/ScriptClass/UX/ScriptReadonlyPropertyTest.ux
This feature enables users to expose readonly data from a scriptclass
> ScriptClass: implement ScriptReadonlyProperty

- CHANGELOG.md
- Source/Fuse.Controls.Primitives/Tests/Curve.Test.uno
- Source/Fuse.Controls.Primitives/Tests/UX/Curve.LineRendering.ux
- Source/Fuse.Drawing.Surface/DotNetSurface.uno
This is an alternative to #470 to fix issue #270. I believe this takes the bull by its horns a bit more than the original fix, as it avoids the specific thing that cause a crash under Mono instead of caring about zero-bounds paths before expanding.
> Fix axis-aligned lines

- Source/Fuse.Common/Tests/FuseTest/TestFramebuffer.uno
- Source/Fuse.Controls.Primitives/Tests/Circle.Test.uno
- Source/Fuse.Elements/Tests/ElementBatcher.Test.uno
When running tests on macOS with AMD hardware, we see some failures that we don't usually see. This PR should fix those.
I also found some other nits in the testing-code while digging, so some other smaller fixes are also included.
> Macos test failures

- Source/Fuse.GeoLocation/iOS/IOSLocationProvider.uno
- Source/Fuse.GeoLocation/iOS/LocationManagerDelegate.h
- Source/Fuse.GeoLocation/iOS/LocationManagerDelegate.mm
2 problems were addressed in the fix.
- Authorization Popup was not triggered by `GetLocation.getLocation` JS call in iOS
- Provided timeout for `GetLocation.getLocation` was starting before user clicks `Allow` button on popup
> Fixed #427 iOS GeoLocation Authorization Popup added

- Source/Fuse.Common/Tests/FuseTest/TestRootNode.uno
Android / iOS testing was broken, this fix is analogous to
17faa1cb183d9746b2555a64a181d786bee2bbfa.
> FuseTest: do not use non-existent base-constructor

- Source/FuseJS/Environment.uno
- Tests/AutomaticTestApp/App/Parts/WebSocket.ux
Workaround for #467, fixes #485
This makes the auto test app work in preview on macOS, by disabling the `WebSocket` test.
> Make the auto test app work in preview on macOS

- Source/Fuse.Text/icu/Windows.stuff
download.icu-project.org is having problems lately, and we don't
want dependencies hosted in places where we have no control. So
let's move this dependency to files.fusetools.com.
> Fuse.Text: do not use download.icu-project.org for dependencies

- CHANGELOG.md
- Source/Fuse.Nodes/ViewHandle.iOS.uno
The properties frame, bounds and center should all point to the same property behind the scenes. Looks like this is not the case in thirdparty libraries. For example setting a frame on Ad views from firebase has no effect on the view position.
Fixing this by always setting center to 0,0.
Fixes https://github.com/fuse-compound/Fuse.Firebase/issues/51
> ViewHandle.iOS: fix translation bug

- CHANGELOG.md
- Source/Fuse.Controls.Native/Android/TextView.uno
The previous behavior was to set max lines to 1 in the case of
Wrapping="NoWrap". This proved to not give the right behavior, as the
TextView should still be multiline even though it shouldn't wrap
automatically. Changing this to setting horizontally scrolling to false
gives the correct behavior.
Fixes fusetools/fuselibs#4010
> Fix TextWrapping="NoWrap" on Android TextView

- CHANGELOG.md
- Source/Experimental.TextureLoader/TextureLoader.uno
Even though 'image/jpg' is not an IANA registered content-type, it
seems there's mis-configured servers out there using this. So let's
be a bit more fault-tolerant, and accept this variation.
Fixes issue #510
> Experimental.TextureLoader: tolerate image/jpg as content-type

- Source/Fuse.Controls.Navigation/Tests/Navigator.Test.uno
- Source/Fuse.Controls.Navigation/Tests/Router.Test.uno
- Source/Fuse.Controls.Navigation/Tests/Transition.Test.uno
- Source/Fuse.Navigation/Router.uno
- Source/Fuse.Navigation/Tests/Activated.Test.uno
- Source/Fuse.Navigation/Tests/FindRouter.Test.uno
- Source/Fuse.Navigation/Tests/Navigation.Test.uno
- Source/Fuse.Navigation/Tests/RouterModify.Test.uno
- Source/Fuse.Navigation/Tests/WhileHistory.Test.uno
- Source/Fuse.Navigation/Tests/WhileNavigation.Test.uno
- Source/Fuse.Nodes/PreviewState.uno
- Source/Fuse.Nodes/RootViewport.uno
- Source/Fuse.Nodes/Tests/Preview.Test.uno
- Source/Fuse.Nodes/Tests/UX/Preview.State.ux
Implements the state migration interface to allow Preview to save/restore the state.
For preview you need to call the `SavePreviewState` prior to unrooting the old nodes and then `RestorePreviewState` prior to creating/adding the new nodes:
- `var store = app.RootViewport.SavePreviewState()`
- Unroot/cleanup
- `app.RootViewport.RestorePreviewState(store)`
- add new children
> State migration for Preview

- Source/Fuse.Drawing.Primitives/Circle.uno
On Mali-400, the fragment-shader does not support highp floats, but
the vertex-shader does.
And since we set the default-precision to highp for all floats when
supported, we end up with different default-precision in the shader
stages. This cause issues when two uniforms have the same name in
both stages.
To side-step this, pre-calculate 1 / radius on the CPU, and use that
instead in the vertex-shader. This is a very minor optimization, but
is worth it simply due to avoiding using the same uniform-name.
Fixes fusetools/fuselibs#4266
> Fuse.Drawing.Primitives: avoid differing uniform precision

- Source/Fuse.Drawing.Surface/DotNetSurface.uno
In 6bed36f, we dropped the incorrect IsEmptyPath-hack because we
had a more directed fix. However, this doesn't seem to cover all
cases. So let's reintroduce a less broken version of this check
(e.g one that checks if *both* width and height is zero) just to
be safe.
We should probably try to get rid of this at the benefit of a more
targetted fix later, but let's not try to deal with that right now.
This fixes a crash on startup in ManualTestingApp on dotnet-targets.
> Fuse.Drawing.Surface: re-introduce IsEmptyPath-hack

- Source/Fuse.Nodes/Tests/Rooting.Test.uno
- Source/Fuse.Nodes/Tests/UX/Rooting.RemoveAll.ux
- Source/Fuse.Nodes/Tests/UX/Rooting.ScrollViewScenario.ux
- Source/Fuse.Nodes/Visual.Children.uno
fixes https://github.com/fusetools/fuselibs-public/issues/518
InProgress: I want to get a test added here before we merge. This was something that wasn't caught during the Childre/LinkedList changes but should have been. It only exhibits in ScrollView since that's the one of two places that use the API in question.
> Fix incorrect Remove called in RemoveAllChildren (ScrollView breaking)

- Source/Fuse.Drawing.Surface/DotNetSurface.uno
This cleans up the conservative work-around in #517 to be a bit more targeted to the actual problem.
With this change, we should in theory be able to stroke a single point on .NET, but sadly
this only seems to work on mono (no stroke generated on Windows).
> Dotnet surface empty path

- Source/Fuse.Nodes/Tests/UX/Visual.ChildrenClear.ux
- Source/Fuse.Nodes/Tests/Visual.Test.uno
- Source/Fuse.Nodes/Visual.Children.LinkedList.uno
We can't null out _nextSibling and then attempt to look it up right
after. This means we effectively only unlinked the first child,
leading to trouble if the following children were ever attempted
inserted into some other child-list.
Fixes #528.
> Fuse.Nodes: fix linked-list usage in Visual.Children.Clear

- Source/Fuse.ImageTools/ImageTools.uno
The declaration in uno code is as following:
`AddMember(new NativePromise<Image, Scripting.Object>("getImageFromBuffer", ImageFromBufferInterface, Image.Converter));`
So documentation is incorrect on the method name. Plus method returned string is wrapped in `ImagePromiseCallback` so result of the method is an `Image`
> Fixed a typo in ImageTools getImageFromBuffer Docs

- CHANGELOG.md
- Source/Fuse.Controls.DatePicker/Android/DatePicker.uno
- Source/Fuse.Controls.DatePicker/iOS/DatePicker.uno
- Source/Fuse.Controls.Native/Android/DateTimeConverterHelpers.uno
- Source/Fuse.Controls.Native/Fuse.Controls.Native.unoproj
- Source/Fuse.Controls.Native/iOs/DateTimeConverterHelpers.uno
- Source/Fuse.Controls.TimePicker/Android/TimePicker.uno
- Source/Fuse.Controls.TimePicker/Fuse.Controls.TimePicker.unoproj
- Source/Fuse.Controls.TimePicker/TimePicker.Docs.uno
- Source/Fuse.Controls.TimePicker/TimePicker.uno
- Source/Fuse.Controls.TimePicker/TimePicker.ux
- Source/Fuse.Controls.TimePicker/iOS/TimePicker.uno
- Source/Fuse/Fuse.unoproj
- Tests/ManualTests/ManualTestingApp/DatePicker/DatePickerPage.ux
- Tests/ManualTests/ManualTestingApp/MainView.ux
- Tests/ManualTests/ManualTestingApp/TimePicker/NativeTimePickerPage.ux
- Tests/ManualTests/ManualTestingApp/UnoComponents.unoproj
Introduces the `Fuse.Controls.TimePicker` package, which includes a `TimePicker` class that proxies native views on Android and iOS. On desktop, a simple placeholder is shown.
> Native TimePickers

- Tests/ManualTests/ManualTestingApp/DatePicker/DatePickerPage.ux
I didn't realize that our testers don't have a log available.
> Remove log step in DatePicker manual test

- Source/Fuse.UserEvents/Tests/UserEvent.Test.uno
Disabled to reduce interruptions on CI.
See #551
> Fuse.UserEvents: disable spuriously failing test

- CHANGELOG.md
- Source/Fuse.Marshal/Marshal.Cast.uno
- Source/Fuse.Marshal/Tests/Fuse.Marshal.Test.unoproj
- Source/Fuse.Marshal/Tests/Marshal.Test.uno
- Source/Fuse.Marshal/Tests/UX/VectorMarshaling.ux
The rules for how to upscale a vector should be the same for literals
and expressions, but this wasn't the case. Make sure it is.
Fixes #540
> Fuse.Marshal: apply float-vector conversion-rules to IArray

- Source/Fuse.Controls.Video/VideoVisual.uno
https://github.com/fusetools/fuselibs-public/pull/506 changed the behavior of video slightly to go directly to the "paused" state when the video was ready to play. The expected behavior was neither "playing" nor "stopped", so I added an Undefined option to cover the last case. Should this perhaps be renamed to "Ready" or "Initialized"? This is simply to represent the state where the user hasn't done anything yet.
> Fix ManualTestApp/issues/371

- Source/Fuse.Controls.Navigation/PageControl.Pages.uno
API shift over time, the obvious fix is fine. If the wrong function is somehow called some tests will fail horribly.
fixes https://github.com/fusetools/fuselibs-public/issues/549
> hiding "new" fix

- Source/Fuse.Controls.DatePicker/Android/DatePicker.uno
Previously, we had missed a crucial detail: local time zone offset is of course relative to a specific timestamp, as offset changes over time. Luckily `java.util.TimeZone` gives us a way to get the default timezone's offset easily. All of this is necessary as `android.widget.setMinDate/setMaxDate` take time in the device's default timezone.
Fixes https://github.com/fusetools/ManualTestApp/issues/373.
> Fix min/max date for Android DatePicker

- Source/Fuse.Reactive.Bindings/Each.uno
- Source/Fuse.Reactive.Bindings/Instance.API.uno
- Source/Fuse.Reactive.Bindings/Instance.uno
- Source/Fuse.Reactive.Bindings/Tests/Instance.Test.uno
- Source/Fuse.Reactive.Bindings/Tests/UX/Instance.RootItems.ux
A change in Each.OnItemsChanged breaks an expected behaviour in Charting. The fix appears to be providing a more complete dervied API to resolve a rooting issue. Premiumlibs will need to use this new `SetItemsDerivedRooting` function.
> fix a regression with not updating items

- Source/Fuse.Controls.DatePicker/Android/DatePicker.uno
- Source/Fuse.Controls.DatePicker/DatePicker.uno
- Source/Fuse.Controls.DatePicker/iOS/DatePicker.uno
On older versions of Android, layout changes can cause the calendar part of the DatePicker's
view to scroll to a bogus month, which both makes the view look like it has the wrong value,
and also makes it hard to pick a relevant value in many cases. To get around this, we need
to somehow get the control to scroll to show the currently set value whenever layout changes.
To achieve this, we'll reset a counter to zero on layout change, count that up a couple times
in order to wait at least 1 frame (we need more than just one iteration to avoid potential
update manager ordering issues). Then, we'll grab the picker's current value and write it
back, tricking the picker to invalidate and scroll where we want it. The downside of this
approach is that _any_ change in layout that causes this view …
> Fix DatePicker bogus scroll

- CHANGELOG.md
- Source/Fuse.Controls.WebView/WebView.ScriptClass.uno
This patch exports four methods of WebViews to allow them to be controlled by FuseJS code. This allows the creation of UI elements or logic to build a mini-webbrowser, which can be sometimes useful in apps.
Are the code comments enough?
If needed, some guidance would be appreciated as I'm pretty new to Fuse/Uno development.
> [Feature] Add navigation methods to WebView for use in FuseJS

- Source/Fuse.Reactive.JavaScript/Observable.uno
The Diagnostic needs to be reported on the right DiagnosticSubject,
so let's pass that in also.
> Fuse.Reactive.JavaScript: fixup FUSELIBS_NO_TOASTS code-path

- Source/Fuse.Controls.Native/iOs/DateTimeConverterHelpers.uno
Just update some deprecated const's from iOS 8.
Fixes https://github.com/fusetools/fuselibs-public/issues/573.
> Fix iOS picker warnings

- Source/Fuse.Common/Diagnostics.uno
- Source/Fuse.Reactive.JavaScript/FunctionMirror.uno
- Source/Fuse.Reactive.JavaScript/JavaScript.uno
- Source/Fuse.Reactive.JavaScript/ModuleInstance.uno
- Source/Fuse.Reactive.JavaScript/Observable.uno
- Source/Fuse.Reactive.JavaScript/Tests/UXExpressionsTest.uno
FUSELIBS_NO_TOASTS is a blast from the past, when we needed the different
versions of the tool with different error-handling using the same fuselibs
version.
But that need is long gone, and the tool always enables this switch. So
let's get rid of the disabled case, as it just complicates things.
> hard-code FUSELIBS_NO_TOASTS on

- CHANGELOG.md
- Source/Fuse.Navigation/Router.ScriptClass.uno
- Source/Fuse.Reactive.JavaScript/ClassInstance.uno
- Source/Fuse.Reactive.JavaScript/FunctionMirror.uno
- Source/Fuse.Reactive.JavaScript/ModuleInstance.uno
- Source/Fuse.Reactive.JavaScript/Observable.uno
- Source/Fuse.Reactive.JavaScript/ObservableProperty.uno
- Source/Fuse.Reactive.JavaScript/ThreadWorker.uno
- Source/Fuse.Scripting/Context.uno
- Source/Fuse.Scripting/ModuleResult.uno
- Source/Fuse.Scripting/ScriptClass.uno
This is the start of a run of PRs to make the `Context` only be
accessible from the JS thread. The rest of the codebase will interface
through it via a (soon to be stripped down) `ThreadWorker`.
The way code will get access to the context is by running an action
on the JS thread. To enable this we start by making the `Invoke`
method take an `Action<Scripting.Context>` rather than an `Action`
There are two main evils in this commit:
- In Fuse.Reactive.JavaScript/Observable.uno:L93 we call Perform with
null. This in temporary as Observable shouldn't be querying if it is
on the JS thread so this will be removed in a future commit.
- Adding Invoke to `IThreadWorker`. I didn't want to add more to this
already questionable interface, however ultimately `Invoke` probably
should be the only …
> Make Invoke take an Action<Scripting.Context>

- Source/Fuse.Elements/Fuse.Elements.unoproj
Internals must be visible to CameraView so it can use https://github.com/fusetools/fuselibs-public/pull/597
> Make Fuse.Elements internals visible to CameraView

- Source/Fuse.BasicTheme/Basic.Resources.ux.uno
- Source/Fuse.Marshal/Marshal.Cast.uno
- Source/Fuse.Marshal/Marshal.Parse.uno
Color.FromHex has been marked as obsolete, as it's a bit quirky. Instead, Color.Parse() has been introduced, including a TryParse-variant that doesn't throw exceptions. So let's use these instead, to avoid both obsoletion-warnings, and needless exceptions.
> use Color.Parse instead of Color.FromHex

- Source/Fuse.Common/Font.uno
- Source/Fuse.Common/Internal/AndroidSystemFont.uno
This just cleans up the font-list parser changes that happened on a release-branch. Shouldn't have any functional effect, apart from making it easier to debug issues like this in the future.
> Font list parser fix master

- CHANGELOG.md
- Source/Fuse.Controls.Panels/Panel.Freeze.uno
- Source/Fuse.Controls.Panels/Tests/FreezePanel.Test.uno
- Source/Fuse.Controls.Panels/Tests/UX/Freeze.Opacity.ux
This was discovered during code-inspection.
> Fuse.Controls.Panels: respect Panel.Opacity when rendering

- CHANGELOG.md
- Source/Fuse.Controls.Primitives/TextControls/MobileTextEdit.uno
- Tests/ManualTests/ManualTestingApp/Singles/TextInputPage.ux
Fixed issue where the placeholdertext would be drawn with password dots. Since we have to draw placeholder as regular text this would happen since we always set transformationMethod. We should not do that while when drawing the placeholder.
Updated ManualTestingApp to account for this
> Fix TextInput PlaceholderText android drawing issue

- Tests/ManualTests/ManualTestingApp/MainView.ux
- Tests/ManualTests/ManualTestingApp/Singles/FrozenPanelPage.ux
While changing the implementation of Panel.IsFrozen, I needed to
test out things a bit. And it seems like a good idea to test this
feature on devices, as it contains a bit of finnicky rendering-stuff.
> ManualTestingApp: add a test for the frozen-panel feature

- CHANGELOG.md
- Source/Fuse.Scripting.JavaScript/ArrayMirror.uno
- Source/Fuse.Scripting.JavaScript/Context.uno
- Source/Fuse.Scripting.JavaScript/ModuleInstance.uno
- Source/Fuse.Scripting.JavaScript/ObjectMirror.uno
- Source/Fuse.Scripting.JavaScript/Observable.uno
- Source/Fuse.Scripting.JavaScript/ThreadWorker.uno
- Source/Fuse.Scripting.JavaScript/TreeObservable/TreeObject.uno
- Source/Fuse.Scripting.JavaScript/TreeObservable/TreeObservable.uno
As with our other commits in this area this seeks to make the
Scripting functionality more robust through the use of Scripting.Context.
This commit is interesting in that by updating the code we find an
exact place where the JS context is used incorrectly. Fixing this does
not belong in this commit but this should provide a sane place to
begin.
> IMirror.Reflect now takes a Scripting.Context

- CHANGELOG.md
- Source/Fuse.Scripting.JavaScript/ClassInstance.uno
- Source/Fuse.Scripting.JavaScript/DateTimeConverterHelpers.uno
- Source/Fuse.Scripting.JavaScript/Duktape/Object.uno
- Source/Fuse.Scripting.JavaScript/JavaScriptCore/Object.uno
- Source/Fuse.Scripting.JavaScript/Observable.uno
- Source/Fuse.Scripting.JavaScript/RootableScriptModule.uno
- Source/Fuse.Scripting.JavaScript/V8/Context.uno
- Source/Fuse.Scripting.JavaScript/V8/Object.uno
- Source/Fuse.Scripting/NativeEventEmitterModule.uno
- Source/Fuse.Scripting/Tests/Scripting.Test.uno
- Source/Fuse.Scripting/Types.uno
This makes `CallMethod` have the same guarantees as `Function.Call`
> CallMethod now takes a Scripting.Context

- Source/Fuse.Controls.ScrollView/Tests/ScrollView.Test.uno
- Source/Fuse.Elements/Element.HitTest.uno
- Source/Fuse.Nodes/Tests/Pointer.Test.uno
- Tests/ManualTests/ManualTestingApp/UserEvents/PopupNotices.ux
These issues are ancient, and there's no longer any point in talking about them. As for the soft-capture tests, the behavior changed so long ago that it should now just be accepted as what we do.
> Cleanup old issue-references

- Source/Fuse.Nodes/Input/Gesture.uno
The code is going to die at a later point if this argument is null,
so let's complain early, so we can find out what's doing this.
This is an old patch that I found useful while debugging, and as
this is public API, I think this could make sense to upstream.
> Fuse.Nodes: complain about null up-front

- CHANGELOG.md
- Source/Fuse.Controls.Navigation/PageControl.uno
- Source/Fuse.Controls.Navigation/Tests/PageControl.Test.uno
- Source/Fuse.Controls.Navigation/Tests/UX/PageControl.PageIndex.ux
- Source/Fuse.Navigation/DynamicLinearNavigation.uno
fixes https://github.com/fusetools/fuselibs-public/issues/614
@kusma This fixes a regression in 1.3, so at the very least it should be in 1.4, or if there is planned 1.3 release then there.
> fixes PageControl.ActiveIndex

- Source/Fuse.FileSystem/Uno/IO/FileStatusHelpers.Windows.uno
- Source/Fuse.Scripting.JavaScript/V8/V8Simple.cpp.uxl
- Source/Fuse.Text/Implementation/ICU.cpp.uxl
* We now use `<Require SharedLibrary>` to get a DLL for the right architecture copied to the right place.
* Remaining `TARGET_MSVC`-things are no longer used by the new target and can soon be removed.
* Includes a compile fix after the `char16_t`-refactoring.
> transition to new Native build target (fusetools/uno#1382)

- Source/Fuse.Controls.Primitives/Image.Visual.uno
- Source/Fuse.Controls.Primitives/Tests/Image.Test.uno
Using trigenometry and matrix-multiplictaions is a pretty slow way
of calculating these matrices. Let's instead hand-roll a version of
this that manually expands the known-zero parts of the matrices for
each variation.
As a nice benefit, we get a more accurate result :)
> Optimize image transform

- CHANGELOG.md
- Source/Fuse.Triggers/Actions/Callback.uno
- Source/Fuse.Triggers/Tests/Callback.Test.uno
- Source/Fuse.Triggers/Tests/UX/Callback.ArgsContainsSender.ux
Users depend on args.sender in the JavaScript handler of a Callback
to contain the name of the visual that was for instance pressed.
However, 51ec407 changed the sender to be the trigger itself, which
broke this behavior.
Let's restore this behavior, by lying about what the sender is inside
Callback. This should be the only user-visible effect of the
sender-change.
Fixes #659
> Fuse.Triggers: restore arg.sender argument on callbacks

- Source/Fuse.Scripting.JavaScript/JavaScriptCore/Array.uno
- Source/Fuse.Scripting.JavaScript/JavaScriptCore/Context.uno
- Source/Fuse.Scripting.JavaScript/JavaScriptCore/Function.uno
- Source/Fuse.Scripting.JavaScript/JavaScriptCore/Object.uno
JavaScriptCore is written in C, and cannot handle C++ exception-unwinding. So let's
avoid throwing exceptions through the scripting-engine, and do like we do on V8;
rethrow the exception when we've exited the VM.
This fixes ScriptingTest.CatchingUnoExceptions on iOS.
> Fuse.Scripting.JavaScriptCore: do not throw exceptions through scriping-engine

- Source/Fuse.Android.TextRenderer/TextRenderer.uno
- Source/Fuse.Controls.Native/NativeRenderer.uno
- Source/Fuse.Controls.Panels/Panel.Freeze.uno
- Source/Fuse.Controls.Primitives/Image.Visual.uno
- Source/Fuse.Controls/Viewport.uno
- Source/Fuse.Drawing.Surface/Android/GraphicsSurface.uno
- Source/Fuse.Drawing.Surface/Android/Surface.uno
- Source/Fuse.Drawing.Surface/CoreGraphics/CoreGraphicsSurface.uno
- Source/Fuse.Drawing.Surface/CoreGraphics/GraphicsSurface.uno
- Source/Fuse.Drawing.Surface/DotNetSurface.uno
- Source/Fuse.Drawing/Blitter.uno
- Source/Fuse.Drawing/Fuse.Drawing.unoproj
- Source/Fuse.Elements/Caching/Cache.uno
- Source/Fuse.iOS.TextRenderer/TextRenderer.uno
We blit a lot of images in Fuselibs. And draw-statements have made that very easy to open-code. However, the future of draw-statements in uno is a bit uncertain. So let's prepare a bit for moving away from them.
This PR introduce a general-purpose blitter, that has an interface that is trivial to implement with plain OpenGL code if needed.
The net-result is a reduction of 9 draw-statements, while keeping all features(*) intact.
> General-purpose blitter

- CHANGELOG.md
- Source/Fuse.Controls.Native/iOS/TextEdit.uno
ActionStyle is not a part of the TextView public API. This was here due to legacy code before the split into TextInput and TextView
> iOS: Remove SetActionStyle on MultiLineTextEdit

- Source/Fuse.Scripting.JavaScript/TreeObservable/TreeArray.uno
- Source/Fuse.Scripting.JavaScript/TreeObservable/TreeObject.uno
- Source/Fuse.Scripting.JavaScript/TreeObservable/TreeObservable.uno
This fixes a couple of cases where JS would be called on the UI thread and vice versa.
- Parsing of arguments passed to TreeObservable operators now happens on the JS thread, and only the call to `Perform(object dc)` implemented by each `Operation` is dispatched onto the UI thread. This has the side-effect of no longer calling JS code from the UI thread with a cached `Scripting.Context` (fixes #639)
- Replacing the contents of a TreeObject using `Set(Scripting.Context, IMirror, Scripting.Object)` now updates UI state and notifies subscribers on the UI thread (as it should)
- The same goes for TreeArray write-back operations
> Fix threading bugs in TreeObservable

- CHANGELOG.md
- Source/Fuse.LocalNotifications/Fuse.LocalNotifications.unoproj
- Source/Fuse.LocalNotifications/iOS/Impl.uxl
- Source/Fuse.PushNotifications/Fuse.PushNotifications.unoproj
- Source/Fuse.PushNotifications/iOS/Impl.uxl
If you implement the notification methods on the AppDelegate then apple
detect this and require you to declare your usage of the
notification's feature, *even if* you arent actually using it,
otherwise your app does not get approved.
Uno now wraps the AppDelegate methods in `#if` so we use declare to
include those methods when neccessary
> Fix notification regression

- CHANGELOG.md
- Source/Fuse.Controls.WebView/Android/FuseWebViewClient.java
- Source/Fuse.Controls.WebView/Android/WebView.uno
- Source/Fuse.Controls.WebView/Android/WebViewForeign.uno
This reverts commit df7e740c2b6607004c955c5f0d87f04a21809e7c, which
broke WebView when used with URISchemeHandler.
Fixes https://github.com/fusetools/fuselibs-public/issues/617.
> Revert "Avoid code duplication on Android + minor formatting fix"

- Source/Fuse.Elements/Caching/Cache.uno
- Source/Fuse.Elements/Caching/ElementAtlas.uno
- Source/Fuse.Elements/Caching/ElementBatch.uno
This code wasn't very exception-safe, and leaks pins on
CacheFramebuffers on errors. Let's clean up this by handling the errors
and explicitly unpinning.
In the future, it might be an idea to use an IDisposable + using pattern
to avoid having to do this manually. This is however a bit easier said
than done, as we need to pin a variable amount of CacheFramebuffers in
some cases. So let's just put a band-aid on here for now.
This was noticed while locally introducing a bug that made the device
run out of memory during rendering, causing test-failures claiming we
were unpinning while going to the background.
> Fuse.Elements: unpin CacheFramebuffers on Exceptions

- Source/Fuse.Controls/Tests/StatusBarBackground.Test.uno
fixes https://github.com/fusetools/fuselibs-public/issues/691
This test isn't valid for TopFrameBackground, or any other "frame" that adapts to OS system size.
> removes invalid test for type

- Source/Fuse.Scripting.JavaScript/ThreadWorker.uno
- `RunInner` is private and can only be run from `Run`
- `Run` is private and is only every invoked from the constructor
- _context has no default value at construction so must be null at the start of `Run` & `RunInner`
> Remove redundant _context checks during ThreadWorker creation

- Source/Fuse.Controls.DatePicker/Fuse.Controls.DatePicker.unoproj
- Source/Fuse.Controls.TimePicker/Fuse.Controls.TimePicker.unoproj
This solves compiler errors on uno/feature/lazy-dotnet:
```
lib\fuselibs\Source\Fuse.Controls.DatePicker\.uno\ux13\Fuse.Controls.DatePicker.g.uno(35): E0000: 'Fuse.Controls.Control.set_Background(Fuse.Drawing.Brush)' is not accessible from 'Fuse.Controls.DatePicker.Template.New()' because Fuse.Controls isn't referenced by Fuse.Controls.DatePicker
lib\fuselibs\Source\Fuse.Controls.DatePicker\DatePicker.uno(132): E0000: 'Fuse.Controls.Control.get_NativeView()' is not accessible from 'Fuse.Controls.DatePickerBase.get_DatePickerView()' because Fuse.Controls isn't referenced by Fuse.Controls.DatePicker
lib\fuselibs\Source\Fuse.Controls.TimePicker\.uno\ux13\Fuse.Controls.TimePicker.g.uno(35): E0000: 'Fuse.Controls.Control.set_Background(Fuse.Drawing.Brush)' is not accessible from …
```
> add missing references to Fuse.Controls

- Source/Fuse.Nodes/RootViewport.uno
There's no point in polling the invalidation-state every frame. So let's instead insert an event on every invalidate instead.
> Fuse.Nodes: do not try to perform layout every single frame

- Source/Fuse.Scripting.JavaScript/Context.uno
- Source/Fuse.Scripting.JavaScript/Observable.uno
- Source/Fuse.Scripting.JavaScript/ThreadWorker.uno
- Source/Fuse.Scripting.JavaScript/TypeWrapper.uno
The `FuseJS.Builtins` object is constructed with a specific context and so is tied to it. This means it is only safe to use from that context. Due to this we move it to the context and make it non-static.
Also we are trying to make the thread worker more focused on the thread communication so fits with that goal.
No changelog as it only effects an internal field
> Move FuseJS field from ThreadWorker to JSContext

- CHANGELOG.md
- Source/Fuse.Scripting.JavaScript/ThreadWorker.uno
Previously there were a number of public fields that would be
initialized during RunInner and so we couldnt trust other code to use
the ThreadWorker without potentially causing issues.
Now the public api revolves around Invoke with is a `ConcurrentQueue`,
thus I think we are in a good place to loosen the construction time
blocking we had previously
> ThreadWorker's public api is safe so we can remove the _ready event

- Source/Fuse.Controls.Primitives/Image.Visual.uno
- Source/Fuse.Controls.Primitives/Tests/Image.Test.uno
- Source/Fuse.Drawing/Blitter.uno
A float3x3 is sufficient to express all two-dimentional linear
transformations, using 4x4 is just wasteful. Let's take advantage
of this, and save some computations.
> Fuse.Drawing: reduce textureTransform to float3x3

- Source/Fuse.Scripting.JavaScript/Context.uno
- Source/Fuse.Scripting.JavaScript/Duktape/Function.uno
- Source/Fuse.Scripting.JavaScript/Duktape/Object.uno
- Source/Fuse.Scripting.JavaScript/FuseJS/Http.uno
- Source/Fuse.Scripting.JavaScript/JavaScriptCore/Function.uno
- Source/Fuse.Scripting.JavaScript/JavaScriptCore/Object.uno
- Source/Fuse.Scripting.JavaScript/ThreadWorker.uno
- Source/Fuse.Scripting.JavaScript/TypeWrapper.uno
- Source/Fuse.Scripting.JavaScript/V8/Debugger.uno
- Source/Fuse.Scripting.JavaScript/V8/Function.uno
- Source/Fuse.Scripting.JavaScript/V8/Object.uno
- Source/Fuse.Scripting/AppInitialized.uno
- Source/Fuse.Scripting/Context.uno
- Source/Fuse.Scripting/NativeEvent.uno
- Source/Fuse.Scripting/NativeEventEmitterModule.uno
- Source/Fuse.Scripting/NativePromise.uno
- Source/Fuse.Scripting/ScriptClass.uno
- Source/Fuse.Scripting/Tests/Scripting.Test.uno
- Source/Fuse.Scripting/Types.uno
Here's a bunch of cleanups to Fuse.Scripting / Fuse.Scripting.JavaScript to try to ensure that things won't get called on the wrong thread.
This particular patch doesn't really change any threading, it's just cleanups.
> Scripting cleanups

- CHANGELOG.md
- Source/Fuse.Controls.Navigation/NavigationControl.ScriptClass.uno
- Source/Fuse.Controls.Navigation/NavigationControl.uno
- Source/Fuse.Controls.Navigation/Tests/Navigator.Test.uno
- Source/Fuse.Controls.Navigation/Tests/Router.Test.uno
- Source/Fuse.Controls.Navigation/Tests/UX/Navigator.ModifyPath.ux
- Source/Fuse.Controls.Navigation/Tests/UX/Router.ModifyObject.ux
- Source/Fuse.Controls.Navigation/Tests/UX/Router.ObjectPath.ux
- Source/Fuse.Navigation/RouterModify.uno
- Source/Fuse.Navigation/RouterPage.uno
- Source/Fuse.Navigation/RouterRequest.uno
- Source/Fuse.Reactive/Fuse.Reactive.unoproj
This exposes some of the internal ability to use objects in the routing.
> Adds object based routing to the router/NavigationControl

- CHANGELOG.md
- Source/Fuse.Scripting.JavaScript/FuseJS/DebugLog.uno
This implements console.info(), console.warn(), console.error(),
as well as making general improvements to formatting.
Previously we called `ToString()` on each argument's Uno representation.
This is okay for primitive values; but for objects and arrays I'd like
to see something more useful than "Fuse.Scripting.V8.Object" in my log.
Instead, perform the string conversion in JavaScript itself,
to take advantage of its string conversion rules.
The string representations of each argument are now joined by a space
to more closely match the behavior of other JavaScript environments.
> Feature console improvements

- Source/Fuse.Controls.Navigation/Tests/PageControl.Test.uno
This makes the test pass consistently for now, but should be
investigated for a proper fix.
> Fuse.Controls.Navigation.Tests: work around #693

- Source/Fuse.PushNotifications/Fuse.PushNotifications.unoproj
Solves the following build errors (`uno doctor -aC`):
```
lib\fuselibs\Source\Fuse.PushNotifications\Fuse.PushNotifications.unoproj(19.70): E0000: Multiple projects or packages with the name Experimental.TextureLoader
lib\fuselibs\Source\Fuse.PushNotifications\Fuse.PushNotifications.unoproj(20.44): E0000: Multiple projects or packages with the name Fuse.Platform
```
> Fuse.PushNotifications: fix project references

- Source/Fuse.Controls/Tests/DockPanel.Test.uno
- Source/Fuse.Controls/Tests/Panel.Test.uno
- Source/Fuse.Controls/Tests/StackPanel.Test.uno
- Source/Fuse.Controls/Tests/UX/DockAligntmentImage.ux
- Source/Fuse.Controls/Tests/UX/LayoutAlignmentImage.ux
- Source/Fuse.Controls/Tests/UX/LayoutPercentDepend.ux
- Source/Fuse.Controls/Tests/UX/LayoutPercentDependent.ux
- Source/Fuse.Controls/Tests/UX/LayoutPercentFixed.ux
We don't really need texture2D.Load any more, so let's get rid of a few usages.
> No more `texture2d.Load`

- CHANGELOG.md
- Source/Fuse.Controls.Navigation/EdgeNavigator.ScriptClass.uno
- Source/Fuse.Controls.Primitives/Image.ScriptClass.uno
- Source/Fuse.Controls.ScrollView/ScrollViewPager.ScriptClass.uno
- Source/Fuse.Controls.ScrollView/Triggers/Scrolled.ScriptClass.uno
- Source/Fuse.Controls.Video/Video.ScriptClass.uno
- Source/Fuse.Controls.WebView/WebView.ScriptClass.uno
- Source/Fuse.Navigation/Router.ScriptClass.uno
- Source/Fuse.Scripting/ScriptClass.uno
- Source/Fuse.Selection/Selectable.ScriptClass.uno
- Source/Fuse.Selection/Selection.ScriptClass.uno
- Source/Fuse.Triggers/Busy.ScriptClass.uno
- Source/Fuse.Triggers/Completed.ScriptClass.uno
- Source/Fuse.Triggers/StateGroup.ScriptClass.uno
In the argument-less case, we can make a generic error if arguments
were passed to a method that doesn't care about arguments.
This ensures calling code is forward-compatible in the case where we
want to add arguments to existing methods.
> Fuse.Scripting: give error on unconsumed args

- Source/Fuse.Navigation/RouterRequest.uno
- Source/Fuse.Scripting.JavaScript/Context.uno
When we truncate while reflecting the JS state, we accidentally left
JS objects in the mirror, because we weren't able to tell the difference
between truncation and primitive-types. So let's rewrite the code a bit
to be able to tell the difference.
Because the mirroring gives up after 50 recursions, make the
RouterRequest validation give up after 49 instead, so we retain the
same errors even when truncating.
> Fuse.Scripting.JavaScript: do not make mirror contain JS objects

- Source/Fuse.Scripting.JavaScript/TreeObservable/TreeObservable.uno
TreeObservable.Operation now traverses the graph from the UI thread when the operation is
performed, instead of on the JS thread when it is scheduled.
This ensures that the previous operation has completed before the next operation is performed, so that the path of the next operation is valid.
Fixes #732
> Don't read TreeObservable state on JS thread

- Source/Fuse.Alerts/Fuse.Alerts.unoproj
- Source/Fuse.Audio/Fuse.Audio.unoproj
- Source/Fuse.GeoLocation/Fuse.GeoLocation.unoproj
- Source/Fuse.Launcher.Email/Email/EmailLauncher.uno
- Source/Fuse.Launcher.Email/Email/EmailTrigger.uno
- Source/Fuse.Launcher.Email/Email/JS.uno
- Source/Fuse.Launcher.Email/Fuse.Launcher.Email.unoproj
- Source/Fuse.Launcher.InterApp/Fuse.Launcher.InterApp.unoproj
- Source/Fuse.Launcher.InterApp/InterApp/InterAppLauncher.uno
- Source/Fuse.Launcher.InterApp/InterApp/InterAppTrigger.uno
- Source/Fuse.Launcher.InterApp/InterApp/JS.uno
- Source/Fuse.Launcher.Maps/Fuse.Launcher.Maps.unoproj
- Source/Fuse.Launcher.Maps/Maps/JS.uno
- Source/Fuse.Launcher.Maps/Maps/MapsLauncher.uno
- Source/Fuse.Launcher.Maps/Maps/MapsTrigger.uno
- Source/Fuse.Launcher.Phone/Fuse.Launcher.Phone.unoproj
- Source/Fuse.Launcher.Phone/Phone/JS.uno
- Source/Fuse.Launcher.Phone/Phone/PhoneLauncher.uno
- Source/Fuse.Launcher.Phone/Phone/PhoneTrigger.uno
- Source/Fuse.Launcher.Phone/Phone/PhoneUriHelper.uno
- Source/Fuse.Launcher/Fuse.Launcher.unoproj
- Source/Fuse.Maps/Fuse.Maps.unoproj
- Source/Fuse.Vibration/Fuse.Vibration.unoproj
- Source/Fuse.Vibration/Vibrate.uno
- Source/Fuse.WebSockets/Fuse.WebSockets.unoproj
- Source/FuseJS/FuseJS.unoproj
- Source/Polyfills.Window/Polyfills.Window.unoproj
There's two things going on here:
- reduction of using-statements
- switching from package-references to project references.
The former should in theory improve complilation-speeds a tad.
The latter is about correctness. If the user has a newer fuselibs
package installed than the in-tree version, the uno package manager
will try to resolve this with the newer one, which is not what we
want. So internal references in the fuselibs-repo should always be
project-references, not package-references.
This is a big, nasty commit, but untangling this without breaking
rebaseablitly is silly much work for little gain, so I'd prefer to
do it in one go.
> clean up packages/projects/usings

- Source/Fuse.Scripting/ScriptClass.uno
This PR refactors the internals of ScriptMethods a bit:
1. It removes ExecutionThread from the base-class, as this is not really a fundamental concept anymore (and never really was, but it's even less so now).
2. It moves the legacy constructor-support to be fully implemented in the constructor, plus a closure. This makes it a bit easier to maintain, at the cost of a slight decrease in performance. Since this is a legacy compatibility thing only, I think a performance degradation should be OK.
3. Some API usage errors would be noticed earlier. But since this part isn't public API, this should have no user-visible effects.
> Script class cleanups

- Source/Fuse.Scripting/ScriptException.uno
As this is kind of an unsolicited PR, feel free to discuss :)
In particular, the number `300` is chosen fairly arbitrarily, so we might want to be more conservative there.
My reasoning is that, if a single line of source code extends beyond 300 characters, it's either:
- A minified JavaScript library, where all the code is on a single line
- Very poorly written code
In any case, it will only clutter up the log, making the actual source of the error harder to find.
> ScriptException: Truncate long source lines

- CHANGELOG.md
- Source/Fuse.Common/Diagnostics.uno
- Source/Fuse.Scripting.JavaScript/Duktape/Context.uno
- Source/Fuse.Scripting.JavaScript/JavaScriptCore/Context.uno
- Source/Fuse.Scripting.JavaScript/Tests/JsErrorTest.uno
- Source/Fuse.Scripting.JavaScript/V8/Context.uno
- Source/Fuse.Scripting/ScriptException.uno
- Source/Fuse.Scripting/ScriptModule.Require.uno
This PR tries to restore some sanity to ScriptException:
- It tries to play ball with how normal `Uno.Exception`s work, in particular wrt Message vs ToString().
- `JSStackTrace` has been renamed to `ScriptStackTrace`, as this type is intended to be language agnostic
- The ill-advised SourceLine property that only worked on V8 has been dropped
There's more that can be done, but this should be sufficient to avoid breakages in feature-Models...
> Script exception sanity

- Source/Fuse.Nodes/AppBase.uno
This will be used by the tool as well as feature-Models. It's being
added early to make it easier for the tool to support both master and
the upcoming feature.
> Fuse.Nodes: introduce IRootVisualProvider

- Source/Fuse.Controls.TimePicker/TimePicker.Docs.uno
I believe the name of this property was changed prior to release, and I probably forgot to update the docs.
Fixes #767.
> Fix typo in TimePicker doc

- Source/Fuse.Elements/Element.Batching.uno
fixes https://github.com/fusetools/support-101ventures/issues/41
I was unable to come up with an isolated reproduction, thus could not create a unit test. It does fix the reported project. I've gone through several scenarios that exercise the code change, but I just couldn't get the original crash to happen except in the original code. :/
> Logical fix to batching cleanup

- CHANGELOG.md
- Source/Fuse.Common/Tests/FuseTest/ObservableList.uno
- Source/Fuse.Reactive/IObservable.uno
- Source/Fuse.Scripting.JavaScript/Observable.uno
- Source/Fuse.Scripting.JavaScript/ObservableProperty.uno
- Source/Fuse.Scripting.JavaScript/TreeObservable/TreeArray.uno
All call-sites can do better directly, due to internal knowledge
about the objects.
For instance, Fuse.Scripting.JavaScript.ObservableProperty knows
exactly the type of Subscription-object it gets, and can call
specific script-shortcut versions of the methods.
And Fuse.Scripting.JavaScript.TreeArray is going to dispatch to the
UI-thread anyway, so it can just do this a bit earlier.
This should fix some problems in premium packages that use this type.
> Drop Context methods from ISubscription

- CHANGELOG.md
- Source/Fuse.Scripting.JavaScript/FuseJS/Http.uno
- Source/Fuse.Scripting.JavaScript/ModuleInstance.uno
- Source/Fuse.Scripting/Module.uno
- Source/Fuse.Scripting/ModuleResult.uno
- Source/Fuse.Scripting/NativeModule.uno
- Source/Fuse.Scripting/ScriptModule.Evaluate.uno
- Source/Fuse.Scripting/ScriptModule.Require.uno
- Source/Fuse.WebSockets/WebSocketModule.uno
Here's some more thread-safety and general API cleanups in Fuse.Scripting and Fuse.Scripting.JavaScript.
The only functional change would be disposing the ModuleResult in an error-case, which usually shouldn't be triggered.
> More scripting cleanups

- CHANGELOG.md
- Source/Fuse.Common/Tests/FuseTest/Value.uno
- Source/Fuse.Reactive.Expressions/StringFunctions.uno
- Source/Fuse.Reactive.Expressions/Tests/StringFunctions.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/UX/StringFunctions.ToLower.ux
- Source/Fuse.Reactive.Expressions/Tests/UX/StringFunctions.ToUpper.ux
> Fuse.Reactive.Expressions: do not crash on null input

- Source/Fuse.Controls.TimePicker/Android/TimePicker.uno
- Source/Fuse.Controls.TimePicker/TimePicker.uno
- Source/Fuse.Controls.TimePicker/iOS/TimePicker.uno
Originally, they were erroneously stored on the view, which led to some invalid conditions where a property would be set before the view was ready and the value lost. Now, following other native controls like Slider, values are stored on the semantic control, and propagated to the view.
> Fix TimePicker properties

- Source/Fuse.Controls.DatePicker/Android/DatePicker.uno
- Source/Fuse.Controls.DatePicker/DatePicker.uno
- Source/Fuse.Controls.DatePicker/iOS/DatePicker.uno
Originally, they were erroneously stored on the view, which led to some invalid conditions where a property would be set before the view was ready and the value lost. Now, following other native controls like Slider, values are stored on the semantic control, and propagated to the view.
> Fix DatePicker properties

- CHANGELOG.md
- Source/Fuse.Animations/Attract.uno
- Source/Fuse.Controls.Primitives/RangeControls/CircularRangeBehavior.uno
- Source/Fuse.Controls.Primitives/RangeControls/LinearRangeBehavior.uno
- Source/Fuse.Controls.Primitives/RangeControls/RangeControl.uno
- Source/Fuse.Controls.Primitives/RangeControls/RangeControl2D.uno
- Source/Fuse.Controls.Primitives/Tests/RangeControl.Test.uno
- Source/Fuse.Controls.Primitives/Tests/RangeControl2D.Test.uno
- Source/Fuse.Controls.Primitives/Tests/UX/RangeControl.RangeValue.ux
- Source/Fuse.Controls.Primitives/Tests/UX/RangeControl2D.CircularBasic.ux
Corrects some behavior with using RangeControl and bound values. Fixes a related numeric stability issue in `attract`.
RangeControl no longer clamps the Value, only the behaviours do.
Fixes https://github.com/fusetools/fuselibs-public/issues/673
> Fix/range control.relative value

- .travis.yml
Looks like pip is not part of xcode command line tools anymore, could not find any details in apples changelogs. But on my fresh high sierra install I was also missing pip
> Travis: install pip

- Source/Fuse.Scripting.JavaScript/FuseJS/Builtins.uno
- Source/Fuse.Scripting.JavaScript/ObservableProperty.uno
Here's a couple of small cleanups from the models-branch that are independently a good idea.
> Pre-models cleanups

- Source/Fuse.Reactive.Expressions/MathFunctions.uno
- Source/Fuse.Reactive.Expressions/NameValuePair.uno
We don't want to allow users to override these, so let's mark them as sealed.
> Seal some expressions

- CHANGELOG.md
- Source/Fuse.Common/Tests/FuseTest/TestBase.uno
- Source/Fuse.Motion/DelayFunction.uno
- Source/Fuse.Reactive.Expressions/BinaryOperator.uno
- Source/Fuse.Reactive.Expressions/IsDefined.uno
- Source/Fuse.Reactive.Expressions/QuaternaryOperator.uno
- Source/Fuse.Reactive.Expressions/TernaryOperator.uno
- Source/Fuse.Reactive.Expressions/Tests/BinaryOperator.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/MathFunctions.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/QuaternaryOperator.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/TernaryOperator.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/UX/BinaryOperator.Error.ux
- Source/Fuse.Reactive.Expressions/Tests/UX/MathFunctions.Clamp.ux
- Source/Fuse.Reactive.Expressions/Tests/UX/MathFunctions.Lerp.ux
- Source/Fuse.Reactive.Expressions/Tests/UX/QuaternaryOperator.Error.ux
- Source/Fuse.Reactive.Expressions/Tests/UX/TernaryOperator.Error.ux
This adds more warning messages to operators.
I'm getting unhappy with a lot of the redundant code and will likely refactor it soon.
> Add warnings on invalid values to operators

- Source/Fuse.Reactive.Expressions/Tests/StringFunctions.Test.uno
This broke when merging release-1.4 into master, due to divergent changes
> Fuse.Reactive.Expressions: fixup ToUpper / ToLower tests

- Source/Fuse.Animations/Attractor.uno
- Source/Fuse.Animations/Change.uno
- Source/Fuse.Common/Internal/RootableList.uno
- Source/Fuse.Elements/Resources/FileImageSource.uno
- Source/Fuse.FileSystem/FileSystemModule.uno
- Source/Fuse.Navigation/PageBinding.uno
- Source/Fuse.Nodes/Event.uno
- Source/Fuse.Scripting.JavaScript/FuseJS/Timer.uno
- Source/Fuse.Storage/ApplicationDir.uno
- Source/Fuse.Triggers/Actions/Set.uno
Using nameof(foo) instead of "foo" will give us compilation-errors if we rename the variable but forget to update the exception. So let's use it to make sure things are consistent. At least one place was out of date already.
I just noticed that this was pretty inconsistent while reading some code.
> use nameof to keep strings consistent

- CHANGELOG.md
- Source/Fuse.Nodes/Node.uno
- Source/Fuse.Nodes/NodeGroup.uno
- Source/Fuse.Nodes/Tests/NodeGroup.Test.uno
- Source/Fuse.Nodes/Tests/UX/NodeGroup.EachOrder.ux
- Source/Fuse.Reactive.Bindings/Tests/UX/With.Basic.ux
- Source/Fuse.Reactive.Bindings/Tests/UX/With.EachOrder.ux
- Source/Fuse.Reactive.Bindings/Tests/UX/With.Observable.ux
- Source/Fuse.Reactive.Bindings/Tests/UX/With.Order.ux
- Source/Fuse.Reactive.Bindings/Tests/With.Test.uno
- Source/Fuse.Triggers/Deferred.uno
It's only accidental that the ordering worked previously -- the code just didn't account for ordering, thus it was undefined previously.
fixes https://github.com/fusetools/fuselibs-public/issues/803
> Fixes a NodeGroup ordering issue, affects Each/With ordering

- Source/Fuse.Scripting.JavaScript/Fuse.Scripting.JavaScript.unoproj
I had not included the jsc header files in the fuse.scripting.javascript unoproj, so when we merged manualtestapp failed to build
> Add missing jsc header files to unoproj file

- Tests/UxGeneratorTests/UxGeneratorTests/UxTests.uno
This avoids this warning:
```
Tests\UxGeneratorTests\UxGeneratorTests\UxTests.uno(43.31): W4139: 'Fuse.Visual.get_FirstVisualChild()' is obsolete: 'Use FirstChild<Visual>() instead'
```
> UxGeneratorTest: avoid triggering warning

- Source/Fuse.Models/FuseJS/Internal/Model.js
- Source/Fuse.Models/Tests/Model.Test.uno
- Source/Fuse.Models/Tests/UX/MultiParent.js
- Source/Fuse.Models/Tests/UX/MultiParent.ux
Fixes #844, as well as a number of other bugs relating to how Model.js manages parent-child relationships.
> Model: Attach to parent on property update

- Source/Fuse.Common/FramebufferPool.uno
I have no idea how this worked. We're including this in the wrong
generated source-file.
But let's fix it, as this has been reported by a user.
> Fuse.Common: move GLHelper include

- CHANGELOG.md
- Source/Fuse.Motion/DelayFunction.uno
- Source/Fuse.Navigation/ModifyRouteCommand.uno
- Source/Fuse.Reactive.Bindings/InstantiatorFunction.uno
- Source/Fuse.Reactive.Expressions/BinaryOperator.uno
- Source/Fuse.Reactive.Expressions/ConversionFunctions.uno
- Source/Fuse.Reactive.Expressions/DataToResource.uno
- Source/Fuse.Reactive.Expressions/Expression.uno
- Source/Fuse.Reactive.Expressions/ExpressionListener.uno
- Source/Fuse.Reactive.Expressions/Fuse.Reactive.Expressions.unoproj
- Source/Fuse.Reactive.Expressions/IsDefined.uno
- Source/Fuse.Reactive.Expressions/MathFunctions.uno
- Source/Fuse.Reactive.Expressions/NameValuePair.uno
- Source/Fuse.Reactive.Expressions/NullCoalesce.uno
- Source/Fuse.Reactive.Expressions/Object.uno
- Source/Fuse.Reactive.Expressions/Operators.uno
- Source/Fuse.Reactive.Expressions/QuaternaryOperator.uno
- Source/Fuse.Reactive.Expressions/StringFunctions.uno
- Source/Fuse.Reactive.Expressions/Subscription.uno
- Source/Fuse.Reactive.Expressions/TernaryOperator.uno
- Source/Fuse.Reactive.Expressions/Tests/BinaryOperator.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/QuaternaryOperator.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/TernaryOperator.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/UX/UnaryOperator.Basic.ux
- Source/Fuse.Reactive.Expressions/Tests/UX/UnaryOperator.Deprecated.ux
- Source/Fuse.Reactive.Expressions/Tests/UnaryOperator.Test.uno
- Source/Fuse.Reactive.Expressions/UnaryOperator.uno
- Source/Fuse.Reactive.Expressions/VarArgFunction.uno
- Source/Fuse.Reactive.Expressions/VectorFunctions.uno
This removes a lot of the redundant code from the expressions. It makes it simpler to implement new expressions, and fixes a few hidden defects in the previously divergent code.
Deprecations warnings will be produced at runtime in most cases (since it can't be detected statically).
There is one removal of old "technically public" API from UnaryOperator. A compatbile addition could be made, but it'd be messy, and those funcions should not have been exposed to begin with (they don't work correctly, nor did Binary/Ternary/QuaternaryOperator expose them).
I didn't manage to simplify all the bits I wanted yet, but this seems like a good merge point.
> merge redundant code in expressions

- CHANGELOG.md
- Source/Fuse.Marshal/Computer.uno
- Source/Fuse.Marshal/Marshal.Compute.uno
- Source/Fuse.Reactive.Expressions/MathFunctions.uno
- Source/Fuse.Reactive.Expressions/Operators.uno
- Source/Fuse.Reactive.Expressions/Tests/MathFunctions.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/StringFunctions.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/UX/MathFunctions.Add.ux
- Source/Fuse.Reactive.Expressions/Tests/UX/MathFunctions.MarshalFunctions.ux
- Source/Fuse.Reactive.Expressions/Tests/UX/StringFunctions.Concat.ux
- Source/Fuse.Reactive.Expressions/Tests/UX/StringFunctions.Marshal.ux
- Source/Fuse.Reactive.Expressions/UnaryOperator.uno
Fixes https://github.com/fusetools/fuselibs-public/issues/801
Workaround for https://github.com/fusetools/fuselibs-public/issues/897 was implemented differently than before.
> Use standard conversion errors for operators

- CHANGELOG.md
- Source/Fuse.Common/Tests/FuseTest/DudElement.uno
- Source/Fuse.Controls.Panels/GraphicsView.ux.uno
- Source/Fuse.Controls.Primitives/Behaviors/Shadow.uno
- Source/Fuse.Controls.Primitives/ShadowElement.uno
- Source/Fuse.Controls.Video/Video.uno
- Source/Fuse.Controls/Viewport.uno
- Source/Fuse.Elements/Element.Layout.Properties.uno
- Source/Fuse.Elements/LimitBoxSizing.uno
- Source/Fuse.Elements/Tests/Element.Test.uno
- Source/Fuse.Elements/Tests/UX/Element.PositionSize.ux
- Source/Fuse.Marshal/Marshal.Cast.uno
- Source/Fuse.Marshal/Tests/Marshal.Test.uno
- Source/Fuse.Reactive.Expressions/ConversionFunctions.uno
- Source/Fuse.Reactive.Expressions/Tests/ConversionFunctions.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/UX/ConversionFunctions.SizeBasic.ux
- Source/Fuse.Reactive.Expressions/Tests/UX/ConversionFunctions.SizeOp.ux
Adds some new functionality for simplified Element positioning/animation in some scenarios.
The Position/Size are hidden by derived classes in a few places. A few have new names/deprecated the old. Only `Video` doesn't have a new name. We can't solve this immediately (other than to deprecate Video.Progress with a new name). User's will have to use the old properties, or wrap the item in a panel.
> Feature `Element.Position` and `Size`, and `size()` expression function

- Source/Fuse.Android/AndroidApp.uno
- Source/Fuse.Platform/Android/SystemUI.uno
It seems some bad assumptions about static-initializer order has
been made, causing a crash if Fuse.Android.AppRoot gets initialized
before the Fuse.App-constructor is run.
So let's work around it, by calling SystemUI.OnCreate from inside
SystemUI.SetAsRootView() instead.
This is a nasty hack, but it fixes the start-up issue. The code
needs to be made more robust, though.
> Fuse.Android/Fuse.Platform: work-around crash on startup

- Source/Fuse.Models/FuseJS/Internal/Model.js
- Source/Fuse.Models/Tests/Model.Test.uno
- Source/Fuse.Models/Tests/UX/ParentLoop.js
- Source/Fuse.Models/Tests/UX/ParentLoop.ux
This fixes a bug where computePath() would look at the first valid parent of a node, and traverse upward from there. This could lead it to get into a cycle. We now keep track of visited parents, so that we only visit each meta node at most once.
Fixes #902 
> Model: Fix stack overflow in computePath()

- Source/Fuse.Models/FuseJS/Internal/Model.js
- Source/Fuse.Models/Tests/Model.Test.uno
- Source/Fuse.Models/Tests/UX/DisconnectOnUpdate.js
- Source/Fuse.Models/Tests/UX/DisconnectOnUpdate.ux
This fixes a bug where, if the value of a property changed from an object reference to a primitive value, the parent would be left dangling in its former child's parent list.
> Model: Fix dangling parent bug

- CHANGELOG.md
- Source/Fuse.Controls.Native/Android/ImageView.uno
The native imageview was transformed incorrectly, making native images
in certain cases be clipped and not match how it would look in a
GraphicsView
> Android: fix ImageView transform issue

- CHANGELOG.md
- Source/Fuse.Reactive.Expressions/Tests/UX/UnaryOperator.Basic.ux
- Source/Fuse.Reactive.Expressions/Tests/UnaryOperator.Test.uno
- Source/Fuse.Reactive.Expressions/UnaryOperator.uno
Being able to use the logical not operator seems neat, and we already
have support in the parser. Seems we're just missing the actual
implementation, so let's add that.
Fixes #915.
> Fuse.Reactive.Expressions: implement LogicalNot

- CHANGELOG.md
- Source/Fuse.Drawing.Surface/DotNetSurface.uno
This needs to be tested on Windows: I tested only DotNet on OSX.  I'm including  reference photo (CoreGraphics output, which is the same as the DotNet output on OSX).
_Note: The fix isn't complete per-se, you can still create gradients that fail by making the gradient line not cross the fill region. It's not a normal use-case, and would take more effort to fix than I think is desired now._
Test project: https://github.com/mortoray/fork-sandbox/tree/master/Jan2018/LinearGrad
fixes https://github.com/fusetools/fuselibs-public/issues/936
fixes https://github.com/fusetools/fuselibs-public/issues/841
> fixes the linearGradient on dotnet

- pack.sh
This should change the versioning of artifacts built with `stuff pack`
to be the same as for artifacts built with `uno pack`. In particular,
`AutomaticTestApp.stuff` and `ProjectTemplates.stuff` will now get the
same version numbers as `fuselibs.packages`. This will make things less
confusing for consumers of these packages.
I've tested this locally, here are examples from applying the patch to master, a release branch and another branch:
Before:
```
Creating upload/Polyfills.Window-1.6.0-rc1-master-070b904.upk  0.26 s
Creating ProjectTemplatesUpload/ProjectTemplates-1.6.0-rc1-local.zip
```
After:
```
Creating upload/Polyfills.Window-1.6.0-rc1-master-bc5baca.upk  0.24 s
Creating ProjectTemplatesUpload/ProjectTemplates-1.6.0-rc1-master-bc5baca.zip
```
Before:
```
Creating …
```
> Make stuff/uno pack use same versioning scheme

- Source/Fuse.Models/FuseJS/Internal/Model.js
- Source/Fuse.Models/Tests/Model.Test.uno
- Source/Fuse.Models/Tests/UX/NestedArray.js
- Source/Fuse.Models/Tests/UX/NestedArray.ux
This fixes a severe bug in Model where we get a crash when pushing an array onto an array.
`Array.prototype.concat()` is recursive up to one level.
This means that if one of the arguments is an array, then its elements,
rather than the array itself, will be appended to the original array.
This changes it to always wrap the value in a single-element array,
which gives us the intended behavior.
> Model: Fix pushing an array onto an array

- Source/Fuse.Models/FuseJS/Internal/Model.js
- Source/Fuse.Models/Tests/Model.Test.uno
- Source/Fuse.Models/Tests/UX/ArrayParentMeta.js
- Source/Fuse.Models/Tests/UX/ArrayParentMeta.ux
Whenever an element is inserted or removed from an array,
the indices of later elements are also adjusted.
However, for every node in the model graph, we also keep track of which
nodes have a property that refers to this node. These parent references
were not adjusted accordingly.
Now, when we do an `insertAt` or `removeRange`, the parent references
of elements that appear after the index we insert/remove at will be
adjusted accordingly.
Fixes #958
> Model: Fix parent refs on array manipulation

- CHANGELOG.md
- Source/Fuse.Scripting/NativeEvent.uno
This was an unintended hard API-breakage, but luckily it's pretty
simple to fix.
We mark the API as obsolete, so people can forward-port their code
to be correct.
Fixes #979.
> Fuse.Scripting: restore the old NativeEvent.RaiseAsync API

- CHANGELOG/router_goback_doublepush.md
- Source/Fuse.Controls.Navigation/Tests/Router.Test.uno
- Source/Fuse.Controls.Navigation/Tests/UX/Router.DoublePushGoBack.ux
- Source/Fuse.Navigation/Router.uno
fixes https://github.com/fusetools/fuselibs-public/issues/939
> Fixes router.goBack with duplicate path items

- Source/Fuse.Scripting/NativeEvent.uno
Before the API-breakage here, we would crash if something was queued
*and* CreateObject had not yet been called. After restoring the API, we
would crash regardless of something being queued or not.
Let's revert the behavior to the way it was.
This method is obsolete anyway, so we don't care that it can lead to a
crash, as long as that's not a new crash.
> Fuse.Scripting: do not crash if Context is null

- CHANGELOG.md
- Source/Fuse.Scripting/NativeEvent.uno
- Source/Fuse.Scripting/NativeFunction.uno
- Source/Fuse.Scripting/NativeMember.uno
- Source/Fuse.Scripting/NativePromise.uno
- Source/Fuse.Scripting/NativeProperty.uno
This restores the same thread-safety that the change that got reverted in #993 introduced, but without a hard API breakage.
> NativeMember thread-cleanup

- Source/Fuse.Models/ModelJavaScript.uno
Depends on #999
Apparently preview dislikes attached properties without a getter,
although it hasn't been a problem with these properties for some
reason. Let's do it anyway for consistency.
> Model: Add getters for Model and ModelNameTable properties

- Source/Fuse.Scripting.JavaScript/Tests/JavaScriptTest.uno
Running `Stuff/uno test Source/Fuse.Scripting.JavaScript/Tests/ -t=msvc` fails while compiling `UX.JavaScript.ExoticNames.ux`, which is used in the `JavaScriptTest.ExoticNames` test. This test was introduced in 882172eaa8a00c38d786308e52d861647e139a8a.
Excluding the test method with `extern(!MSVC)` fixes the problem, I assume this is because `UX.JavaScript.ExocticNames` then gets stripped away from the build.
- ~Changelog~ No user-facing changes
- ~Tests~ N/A
> Exclude broken test from MSVC build

- Source/Fuse.Models/Tests/Model.Test.uno
- Source/Fuse.Models/Tests/UX/NestedArray.ux
This fixes models tests after they broke when merging `release-1.6` to `master`.
> Fix models after 1.6 merge

- Source/Fuse.Nodes/AppBase.uno
These were never meant to be exposed to users, but it seems users are finding this and asking how to use it. So let's hide it so this doesn't happen again in the future. Note that we still want to keep the documentation for our own internal information, as well as the tool's.
> Hide unhandled exception methods

- CHANGELOG.md
- Source/Fuse.Elements/Resources/FileImageSource.uno
- Source/Fuse.Elements/Resources/HttpImageSource.uno
- Source/Fuse.Scripting.JavaScript/Tests/Various.Test.uno
The Diagnostic API's intention is to report issues to the user, so the messages should be friendly and easy to act on. This PR fix the messages reported on image load failure. 
> ImageSource: Report more friendly error messages

- Source/Fuse.Models/ModelJavaScript.uno
- ModelJavaScript's constructor made private rather than internal
- Now takes a ModelData instance rather than destructuring
> Refactor ModelJavaScript constructor

- CHANGELOG.md
- Source/Fuse.Nodes/Tests/UX/Visual.OnParameterChanged.ux
- Source/Fuse.Nodes/Tests/Visual.Test.uno
- Source/Fuse.Nodes/Visual.ScriptClass.uno
- Source/Fuse.Scripting.JavaScript/FunctionMirror.uno
- Source/Fuse.Scripting/Context.uno
- Source/Fuse.Scripting/Fuse.Scripting.unoproj
Seems our change to always reflect the arguments to ScriptClass-methods lead to breakage of the `onParameterChanged`-API. But we had no test that would notice.
So let's fix that. In general, we should make FunctionMirror a bit less insane (somehow). But that's not so good for a stable-branch. So let's use some internal API trickery for now.
> onParamaterChanged crash-fix

- CHANGELOG.md
- Source/Fuse.Models/ModelJavaScript.uno
- Source/Fuse.Models/Tests/Fuse.Models.Test.unoproj
- Source/Fuse.Models/Tests/Model.Test.uno
- Source/Fuse.Models/Tests/UX/Args.Each.Inner.js
- Source/Fuse.Models/Tests/UX/Args.Each.Outer.js
- Source/Fuse.Models/Tests/UX/Args.Each.ux
- Source/Fuse.Models/Tests/UX/Args.ScrollView.js
- Source/Fuse.Models/Tests/UX/Args.ScrollView.ux
- Source/Fuse.Models/Tests/UX/Args.Single.js
- Source/Fuse.Models/Tests/UX/Args.Single.ux
- Source/Fuse.Models/Tests/UX/Args.SingleVectorArg.js
- Source/Fuse.Models/Tests/UX/Args.SingleVectorArg.ux
- Source/Fuse.Scripting.JavaScript/JavaScript.uno
Adds support for passing constructor arguments to the model class.
`MyComponent.ux`
<Panel
ux:Class="MyComponent"
Model="Models/MyComponent"
ModelArgs="this, {foo}, 123, {ReadProperty Title}"
/>
`Models/MyComponent.js`
export default class {
constructor(view, foo, oneTwoThree, titleProperty) {
// ...
}
}
This is currently only implemented for component models, since
app-level model arguments would be a bit more convoluted
(state migration would need to be disabled in this case).
> Model: Introduce ModelArgs property

- CHANGELOG/protected_internal_apis.md
- Source/Fuse.Common/Tests/FuseTest/ObservableList.uno
- Source/Fuse.Controls.Primitives/TextControls/TextControl.GraphicsText.uno
- Source/Fuse.Controls.Primitives/TextControls/TextInputControl.uno
- Source/Fuse.Physics/ForceFieldTriggers.uno
These protected internal members returned or took as parameter internal entities, which will soon be an error in Uno (matching C#). A member being protected internal means that it's visible to derived classes outside the package, but this wasn't really possible for these members since they were mentioning internal entities.
> Change some members from protected internal to just internal

- CHANGELOG/native_path_rendering.md
- Source/Fuse.Controls.Panels/GraphicsView.ux.uno
- Source/Fuse.Controls.Panels/NativeViewHost.uno
- Source/Fuse.Controls.Panels/SingleViewHost.uno
- Source/Fuse.Controls.Panels/TreeRenderer.Android.uno
- Source/Fuse.Controls.Panels/TreeRenderer.iOS.uno
- Source/Fuse.Elements/Element.ITreeRenderer.uno
- Source/Fuse.Elements/Element.Validation.uno
- Source/Fuse.Elements/Tests/Element.TreeRenderer.Test.uno
- Source/Fuse.Elements/Tests/UX/ElementTreeRenderer.PathRenderBounds.ux
The forwarding of renderoubnds relied on the Placed event triggering,
which might not happen when only RenderBounds are invalidated
> TreeRenderer: add RenderBoundsChanged

- Source/Fuse.Models/FuseJS/Internal/Model.js
Given an efficient implementation, this should bring lookup time
down to O(1), instead of always doing a linear search.
> Model: Use Set to track visited nodes in evaluateDerivedProps

- Source/Fuse.Models/FuseJS/Internal/Model.js
- Source/Fuse.Models/Tests/Model.Test.uno
- Source/Fuse.Models/Tests/UX/UpdateDisconnectedAfterPromise.js
- Source/Fuse.Models/Tests/UX/UpdateDisconnectedAfterPromise.ux
This fixes a class of bugs where we would attempt to invoke TreeObservable operations, even if the node was no longer part of the graph. We now check that we have a valid path to the root object before performing an operation on the TreeObservable.
>  Model: Check if we are rooted before sending TreeObservable messages

- .teamcity_set_versions.sh
- .travis.yml
- README.md
Everything required for upgrading Mono from 4.4.2 to 5.4.1.
> Upgrade to Mono 5.4.1

- CHANGELOG.md
- Source/Fuse.Controls.Navigation/Tests/Router.Test.uno
- Source/Fuse.Controls.Navigation/Tests/UX/Router.Issue1066.ux
- Source/Fuse.Navigation/Router.uno
- Source/Fuse.Nodes/Tests/UX/Visual.OnParameterChanged.ux
- Source/Fuse.Nodes/Tests/Visual.Test.uno
- Source/Fuse.Nodes/Visual.ScriptClass.uno
- Source/Fuse.Scripting.JavaScript/FunctionMirror.uno
- Source/Fuse.Scripting/Context.uno
- Source/Fuse.Scripting/Fuse.Scripting.unoproj
- Source/Fuse.Scripting/NativeEvent.uno
These patches were part of a 1.6 patch release, but we missed merging them to master afterwards, and so they've missed 1.7 and the 1.8 branch-out. 
After [merging 1.6 into 1.7](https://github.com/fusetools/fuselibs-public/pull/1074), this PR merges 1.7 into 1.8, so everything should be up to date.
> Merge missed patches

- Source/Fuse.Models/FuseJS/Internal/Model.js
Even though functions are objects in JS, we want to treat them
as immutable, atomic primitives.
So let's ignore functions when registering object properties or
fixing up parent references in arrays.
> Model: Don't register props or fixup parent refs for functions

- Source/Fuse.Common/Tests/FuseTest/ObservableCollector.uno
Adds methods for writing back to the subscription created by
ObservableCollector. These will throw an InvalidOperationException if
the subscription does not support write-back.
> ObservableCollector: Add support for writing back to the subscription

- Source/Fuse.Controls.Native/Android/Java/FuseScrollView.java
The wrapping ViewGroup deals with clipping
This fixes https://github.com/fusetools/fuselibs-public/issues/1091
> Internal ScrollViews on Android should not clip

- Source/Fuse.Common/Tests/FuseTest/InterceptPanel.uno
- Source/Fuse.Controls.Panels/Layouts/DockLayout.uno
- Source/Fuse.Controls.Panels/Tests/DockPanel.Test.uno
- Source/Fuse.Controls.Panels/Tests/UX/DockPanel.Issue1082.ux
- Tests/ManualTests/ManualTestingApp/ActionTiming/ActionTiming.ux
- Tests/ManualTests/ManualTestingApp/BackButton/BackButtonView.ux
- Tests/ManualTests/ManualTestingApp/DeviceInfo/DeviceInfo.ux
- Tests/ManualTests/ManualTestingApp/Singles/AnimationControlTest2.ux
- Tests/ManualTests/ManualTestingApp/Singles/Opacity.ux
- Tests/ManualTests/ManualTestingApp/Singles/SwipeLimitPage.ux
- Tests/ManualTests/ManualTestingApp/Singles/VideoPage.ux
Fixes https://github.com/fusetools/fuselibs-public/issues/1082 in DockPanel
Cleanup warnings from ManualTestApp -- both deprecated and invalid layouts
> Fixes DockPanel layout, and ManualTestApp invalid layouts

- Source/Fuse.Controls.Panels/Tests/ColumnLayout.Test.uno
- Source/Fuse.Controls.Panels/Tests/UX/ColumnLayout1.ux
- Source/Fuse.Controls.Panels/Tests/UX/ColumnLayout2.ux
- Source/Fuse.Controls.Panels/Tests/UX/ColumnLayout3.ux
- Source/Fuse.Controls.Panels/Tests/UX/ColumnLayout5.ux
- Source/Fuse.Nodes/Tests/UX/UxCompiler.NodeSource.ux
- Source/Fuse.Nodes/Tests/UxCompiler.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/ExpressionSources.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/UX/ExpressionSources.ux
Now that we'll get generated source information for several fuselibs objects for better error reporting after https://github.com/fusetools/uno/pull/1622 and https://github.com/fusetools/fuselibs-public/pull/1103, let's add some tests to make sure they're what we expect for these fuselibs objects specifically.
> UX source tests for fuselibs objects

- .travis.yml
It seems that the default OSX image on travis is having some security
issues, causing builds to fail. So let's try to upgrade the OSX image to
the latest non-beta one, so builds will hopefully work again.
> travis: update osx image

- CHANGELOG/mapview_curloc_crash.md
- Source/Fuse.Maps/iOS/MapViewDelegate.m
MKUserLocation blue userLocation MKAnnotation causes app to crash if inadvertently touched.
This modifications fixe this issue by testing the kind of clicked marker.
> Fix crash when user click on blue userLocation

- Source/Fuse.Controls.ScrollView/Tests/ScrollViewPager.Test.uno
helps track https://github.com/fusetools/fuselibs-public/issues/1125
It's unclear what the failure is right now. Potentially this test just takes took long on the integration server -- potentially a heavy load?
> extend info on test to track failure

- Source/Fuse.Launcher.Email/Email/EmailLauncher.uno
- Source/Fuse.Launcher.Maps/Maps/MapsLauncher.uno
- Source/Fuse.Launcher.Phone/Phone/PhoneUriHelper.uno
`Uri.Encode(string)` is obsolete in favor of `Uri.EscapeDataString(string)`, so let's update this code also.
This gets rid of a few warnings.
> Fuse.Launcher: do not use deprecated APIs

- Tests/AutomaticTestApp/App/Parts/HttpJson.ux
- Tests/ManualTests/ManualTestingApp/HttpXml/HttpXmlView.ux.uno
- Tests/ManualTests/ManualTestingApp/Https/HttpsView.ux.uno
The uno-http-test.azurewebsites.net app is part of some very old Azure legacy infrastructure that we'd like to decomission as soon as possible. ManualTestApp and AutomaticTestApp were depending on this app simply to download some documents to assert JSON/XML parsing and some HTTP/HTTPS functionality.
I've uploaded the documents to an S3-bucket and changed the URLs accordingly.
> Deprecate uno-http-test.azurewebsites.net

- Source/Fuse.Elements/Tests/Element.TreeRenderer.Test.uno
We don't have a functional surface-backend on this platform, so let's
not even try to run this test. It's not going to work ;)
> Source.Elements.Tests: ignore PathDataChanged on MSVC

- Source/Fuse.Drawing.Surface/DotNetSurface.uno
It seems the .NET implementation of LinearGradientBrush doesn't really
like zero-length gradients, so we end up allocating a silly amount of
memory, eventually crashing.
We already have an early-out like this earlier, so let's add one more
to avoid crashing.
Fixes #1117.
> Fuse.Drawing.Surface: avoid out-of-memory exception

- Source/Fuse.Share/ShareModule.uno
1/ Create a script that calls this line:
Share.shareFile(image.path, "image/*", "Text To Share", ShareOrigin);
2/ Run it
=> Description is never shown, even in a simple email.
> Fix for the ticket #1156

- Source/Fuse.Controls.Navigation/Docs/Navigator.md
This should fix the currently broken link at:
https://docs.fusetools.com/fuse/controls/navigator.html#transitions
> Fuse.Controls.Navigation: correct URL in documentation

- Source/Experimental.TextureLoader/Experimental.TextureLoader.unoproj
- Source/Fuse.Platform/Fuse.Platform.unoproj
This fixes two instances of incorrect filename casings. This fixes the build on machines with a case-sensitive file system.
> Fix filename casing

- README.md
This is a bit more helpful to the public, as the TeamCity server is only
reachable to a few of the users.
> README: switch build-badges to travis/appveyor

- Source/Fuse.Controls.Primitives/Docs/Button.md
- Source/Fuse.Reactive.Bindings/Docs/DataBindingRemarks.md
This fixes a few dead links in docs. In the case where the link is removed, there are no corresponding link in the current docs.
> cleanup dead links

- Source/Fuse.Platform/Fuse.Platform.unoproj
This is a cherry-pick of bba6b3b123ea064fe21942851380e36eeb48329a onto release-1.9, because
a bad merge (9270031d3c337df729a99387c970d3c418e1cbd8) removed the fix. So let's get the fix
back!
Fixes #1180.
> Make Fuse.Platform internals visible to Fuse.Views

- Source/Fuse.Platform/Fuse.Platform.unoproj
- Source/Fuse.Platform/iOS/KeyboardContext.h
- Source/Fuse.Platform/iOS/KeyboardContext.mm
- Source/Fuse.Platform/iOS/SystemUI.ios.uxl
- Source/Fuse.Platform/iOS/SystemUI.uno
The use of Categories in objc is not a good pattern. uAppDelegate needs
to be killed. This fixes issues in fuse views where we do not have a
uAppDelegate instance
--------------------
Fixes https://github.com/fuse-open/fuselibs/issues/1172
> iOS: refactor uAppDelegate dep away from softkeyboard

- CHANGELOG.md
- Source/Fuse.Nodes/MobileBootstrapping.uno
For Fuse.Views, there's no global root-viewport that can handle
input for us, unlike for normal apps. This means that we're just
going to crash down these code-paths anyway.
Fixes #1177.
> Fuse.Nodes: do not use KeyboardBootstrapper with Fuse.Views

- Source/Fuse.PushNotifications/Android/Impl.uno
Regarding to forum posts talking about a problem with unintended behavior on `Fuse.PushNotifications` that represent the following scenario : 
1- Our app received multiple notifications on the notifications bar.
2- When we click on the first one, the notification will be clickable and `` will fired also `push.on("receivedMessage" .. `.
3- The rest of notifications won't work.
I have fixed the flags for the pending intent in `Impl.uno` so that the app will receive multiple notifications and all notifications are working and doing fine
> Fix Push Notifications

- README.md
The existing link to Slack doesn't work well for new users.  It asks for
a login, but provides no means to create one.  Update the link so it
points to https://slackcommunity.fusetools.com/, which provides a better
on-boarding experience.
> Fix link to Slack

- Source/Experimental.TextureLoader/TextureLoader.uno
Dear Sirs,
I have added the ability to load images with `binary/octect-stream` content type header which will increase the support of using images from different CDNs.
Best,
Ahmad
> Enable loading images with binary/octet-stream content-type header

- Source/Fuse.Platform/Fuse.Platform.unoproj
Otherwise we'll get build errors when using this package on mobile.
`Fuse.Entities` are using `Fuse.Platform.SystemUI.FrameChanged` here:
https://github.com/fuse-open/Fuse.Entities/blob/master/src/Scene.uno#L9
Maybe there's a better way to fix this, but this was the quickest route I found.
> Fuse.Platform: make internals visible to Fuse.Entities

- Source/Fuse.Maps/Android/MapView.uno
Change the version of play services of Fuse.Maps to **12.0.1** To work and compile with the last commit of Fuse.Firebase(https://github.com/fuse-compound/Fuse.Firebase)
SOLVE this problem: https://stackoverflow.com/questions/41408514/com-google-android-gms-common-internal-safe-parcel-safe-parcelable-not-found
> Change version of play services of Maps

- CHANGELOG.md
- Source/Fuse.CameraRoll/Android/AndroidCameraRoll.uno
- Source/Fuse.CameraRoll/CameraRoll.uno
- Source/Fuse.CameraRoll/iOS/iOSCameraRoll.uno
- Tests/ManualTests/ManualTestingApp/Singles/CameraPage.ux
Sometimes automatically asking for access to photos may not be a good idea.
These new features allow the programmer to know the status and request access when the timing is appropriate.
More on that [here](https://uxplanet.org/getting-to-yes-best-practices-for-ios-permissions-dialogs-9d62892142cc).
`checkPermissions()` - Checks if your app has access to the gallery.
`requestPermissions()` - Requests permission to access the gallery. In iOS, if the user has previously denied access this function will redirect them to your app settings in their iPhone / iPad.
> New camera roll features

- Source/Fuse.Triggers/Tests/Callback.Test.uno
This makes life with CI much more comfortable. This test has been randomly failing for a while, stalling otherwise good PRs.
> Fuse.Triggers: ignore spuriously failing test

- Source/Fuse.PushNotifications/iOS/Impl.uno
Xcode error: `UI API called on a background thread: -[UIApplication registerUserNotificationSettings:]`
UIApplication can only be called from main thread.
> fixes Xcode background thread error

- CHANGELOG.md
- Source/Fuse.Camera/Android/AndroidCamera.uno
- Source/Fuse.Camera/Camera.uno
- Source/Fuse.Camera/iOS/iOSCamera.uno
- Tests/ManualTests/ManualTestingApp/Singles/CameraPage.ux
Similar to #1209 
Sometimes automatically asking for access to the camera may not be a good idea.
These new features allow the programmer to know the status and request access when the timing is appropriate.
More on that [here](https://uxplanet.org/getting-to-yes-best-practices-for-ios-permissions-dialogs-9d62892142cc).
`checkPermissions()` - Checks if your app has access to the camera.
`requestPermissions()` - Requests permission to access the camera. In iOS, if the user has previously denied access this function will redirect them to your app settings in their iPhone / iPad.
> New camera features

- build.sh
After the last .stuff file in the Stuff dir was removed the build script now exits with an "ERROR: No input files" output on my mac.
Removing the redundant stuff line fixes this.
> Fix build.sh error

- CHANGELOG.md
- Source/Fuse.Controls.DatePicker/iOS/DatePicker.uno
The actual issue here was simple. The Min & Max were set to the Value,
which meant there were no valid dates so iOS greyed them out.
There is probably a secondary issue of why this issue didn't manifest without
the inclusion of the WhileTrue, but that is for a separate PR.
This fixes:
- https://github.com/fuse-open/fuselibs/issues/1218
- https://forums.fusetools.com/t/datepicker-wont-allow-date-change-when-inside-whiletrue-on-ios/7295
> Fix iOS DatePicker in WhileTrue bug

- CHANGELOG.md
- Source/Fuse.LocalNotifications/iOS/AppDelegateLocalNotify.mm
- Source/Fuse.LocalNotifications/iOS/Impl.uno
This fixes https://github.com/fuse-open/fuselibs/issues/1219
The issue was that, in the case where an app is started (rather than
just restored) by clicking on a notification in the status bar, the
notification is delivered via the iOS launch options and not the usual callback
> Fix iOS not delivering local notif, if launched from statusbar

- CHANGELOG.md
- Source/Fuse.Controls.WebView/Android/FuseWebViewClient.java
- Source/Fuse.Controls.WebView/iOS/WVNavDelegate.m
Current <WebView /> markup renders HTML files/pages so well but system special URL links such as "mailto:", "sms:", and "tel:"  do not have any behavior to open system apps. This PR proposes a basic approach to handle those URLs. 
> Fuse.Controls.WebView: Handles mailto, sms, and tel URLs (iOS & Android)

- Source/Fuse.Text/Implementation/Harfbuzz.uno
- Source/Fuse.Text/Implementation/hb-ft-cached.cc
This fixes compile-time C++ warnings in our Harfbuzz integration.
> Fuse.Text: fix harfbuzz warnings

- Source/Fuse.FileSystem/FileSystemModule.uno
This adds missing parameters to writeTextToFile and writeBufferToFile
methods, and uses the correct method name in the existsSync example.
> Fuse.FileSystem: fix mistakes in doc-comments

- Source/Fuse.LocalNotifications/JS.uno
- Source/Fuse.PushNotifications/JS.uno
Both of these files uses both Uno.UX and Fuse.Reactive (which both
provides a Resource class), but neither clarify which one they want to
use. This leads to a compilation error on usage.
So let's fix it, by adding the fully qualified name here.
How this has gone unnoticed for this long is beyond me. I guess nobody
is using this functionality?
This was extracted out of #1197, but another case was added as well.
> Fuse.*Notifications: clarify ambiguous symbol

- Source/Experimental.TextureLoader/CIL/CilTextureLoader.uno
- Source/Experimental.TextureLoader/TextureLoader.uno
- Source/Experimental.TextureLoader/TextureLoaderImpl.cpp.uxl
- Source/Experimental.TextureLoader/TextureLoaderImpl.uno
- Source/Fuse.Drawing.Primitives/Rectangle.uno
- Source/Fuse.Drawing/Internal/BufferCollections.uno
- Source/Fuse.Elements/Caching/ElementBatch.uno
- Source/Fuse.Elements/Resources/FileImageSource.uno
- Source/Fuse.Elements/Resources/HttpImageSource.uno
- Source/Fuse.Text/Renderer.uno
`Uno.Buffer` was deprecated in https://github.com/fuse-open/uno/pull/80, and this migrates to `byte[]` and removes deprecation warnings.
> Migrate away from Uno.Buffer

- Source/Fuse.Controls.CameraView/Fuse.Controls.CameraView.unoproj
We should use project references when referencing projects from the same
repository. This avoids getting errors when building, such as:
E0000: Multiple projects or packages with the name Fuse.ImageTools
The errors starts happening when building multiple times, when both the
original project and a built package version of it exist. After fixing the
project references, we can build multiple times without getting errors.
> Fuse.Controls.CameraView: fix project references

- Source/Fuse.Elements/Resources/Exif/Exif.uno
- Source/Fuse.Maps/Android/MapView.uno
- Source/Fuse.PushNotifications/Android/Impl.uno
- Source/Fuse.Scripting.JavaScript/JavaScriptCore/Context.uno
- Source/Fuse.Scripting.JavaScript/V8/V8Simple.cpp.uxl
- Source/Fuse.Text/Implementation/Harfbuzz.uno
Uno 1.10 upgrades to a new version of the Gradle plugin, and renames some build properties to conform. This PR migrates to the new properties.
See https://github.com/fuse-open/uno/pull/73 and https://github.com/fuse-open/uno/pull/101.
> Migrate to new Android tooling

- Source/Fuse.Designer/Attributes.uno
FilenameAttribute was deprecated a long time ago, and because using it has no
effect it is safe to remove.
> Fuse.Designer: remove use of obsolete attribute

- Source/Fuse.Scripting.JavaScript/V8/V8Simple.uno
- Source/Fuse.Scripting.JavaScript/V8/V8SimpleExtensions.uno
Fixes the crash of android preview; as the debug calls are deprecated in the newer version of V8, we still need to upgrade the JS debugger calls.
> Temp Android Preview Crash Fix

- .appveyor.yml
- Source/Fuse.Common/Internal/DesktopFonts.stuff
- Source/Fuse.Controls.Video/CIL/XamMac.stuff
- Source/Fuse.Elements/Tests/UX/ImageFill.UrlResource.ux
- Source/Fuse.Scripting.JavaScript/V8/V8Simple.cil.uxl
- Source/Fuse.Scripting.JavaScript/V8/lib/DotNet.stuff
- Source/Fuse.Scripting.JavaScript/V8/lib/OSX.stuff
- Source/Fuse.Scripting.JavaScript/V8/lib/Windows.stuff
- Source/Fuse.Text/Implementation/ICU.cil.uxl
- Source/Fuse.Text/harfbuzz/lib/Android.stuff
- Source/Fuse.Text/harfbuzz/lib/OSX.stuff
- Source/Fuse.Text/harfbuzz/lib/iOS.stuff
- Source/Fuse.Text/icu/Windows.stuff
- Source/Fuse.Text/icu/iOS.stuff
- Source/Fuse.WebSockets/iOS/SocketRocket/SocketRocket-iOS.stuff
- package-lock.json
- package.json
It looks like all dependencies hosted on files.fusetools.com are no longer available, effectively breaking all versions of Fuse and Fuse Studio ever released. Hopefully they will come back again soon...
Dependencies are now repackaged and hosted on nuget.org to get things up and running again and to avoid problems with files.fusetools.com in the future.
> Fix dependency downloads

- Source/Fuse.Share/ShareModule.uno
- Source/Fuse.Share/android/AndroidShareImpl.uno
- Source/Fuse.Share/android/AndroidShareImpl.uxl
- Source/Fuse.Share/android/ShareFileProvider.java
- Source/Fuse.Share/android/android_share_paths.xml
Updated to new android file permission requirements when sharing.
You will need to override the android_share_paths.xml(via AndroidShareImpl.uno) if you would like to add custom paths of folders you would like to give share access to.
https://medium.com/@andrewq/hello-world-eaa996c594b7
> Share - Android Updates

- Source/Fuse.Gestures/Pressed.uno
As pointed out [here][1], the reason why this documentation doesn't
appear in the generated docs, is that the documentation comment is
preceeding the internal field, not the public property. So let's remedy
this.
[1]: https://github.com/fuse-open/docs/pull/12#discussion_r201247919
> Fuse.Gestures: move documentation to the public property

- Source/Fuse.Controls.Native/Android/TextEdit.uno
- Source/Fuse.Controls.Native/iOS/Helpers.h
- Source/Fuse.Controls.Native/iOS/Helpers.mm
- Source/Fuse.Controls.Native/iOS/TextEdit.uno
IsReadOnly Property on TextInput both iOS and Android are not function. User still can make an edit and keyboard still showing up. this also fix https://github.com/fuse-open/fuselibs/issues/492
> fix readonly TextInput

- index.d.ts
- package.json
This adds a Definitions file for TypeScript, helpful for code-completion and as documentation.
This file is automatically picked up by TypeScript editors when Fuselibs is installed to `node_modules/` via `npm install` or `npm link`. Tested in Visual Studio Code.
> Add TypeScript Definitions

- Source/Fuse.Android/AppRoot.uno
- Source/Fuse.Controls.CameraView/Android/Camera.uno
- Source/Fuse.Controls.CameraView/Android/CameraView.uno
- Source/Fuse.Controls.CameraView/Android/PhotoPreview.uno
- Source/Fuse.Controls.DatePicker/Android/DatePicker.uno
- Source/Fuse.Controls.Native/Android/CanvasViewGroup.uno
- Source/Fuse.Controls.TimePicker/Android/TimePicker.uno
- Source/Fuse.Nodes/ViewHandle.Android.uno
Most other code is using `com.fuse.Activity.getRootActivity()`, so switch to using that method in all similar call sites.
`@(Activity.Package).@(Activity.Name).GetRootActivity()` is being deprecated in https://github.com/fuse-open/uno/pull/162.
> Android: switch out calls to GetRootActivity()

- Source/Fuse.Sensor/SensorModule.uno
this fix is necessary so that when building fuse api-docs, generator will not complaining about invalid / missing links
> fix sensor docs links

- Source/Fuse.Scripting.JavaScript/V8/V8.stuff
- Source/Fuse.Scripting.JavaScript/V8/V8Simple.cpp.uxl
- Source/Fuse.Text/Implementation/Harfbuzz.uno
- Source/Fuse.Text/harfbuzz/lib/Android.stuff
This replaces Android packages of Harfbuzz and V8, and includes code for `armeabi-v7a`, `arm64-v8a`, `x86` and `x86_64`*.
* V8 is not currently available for `x86_64`.
Related: https://github.com/fuse-open/uno/issues/154
> Android: add fat builds (64-bit support)

- Source/Fuse.Controls.Primitives/Image.ScriptClass.uno
- Source/Fuse.Elements/Resources/HttpImageSource.uno
Add disk cache functionality to the image so that the next time we display an image it will no longer be downloaded from the network.
> Add disk cache functionality to image

- Source/Fuse.Elements/Resources/HttpImageSource.uno
This is a fix for when using `HttpImageSource` without `DiskCache` property, the image can't even be loaded. This resolve #1276 
And this also corrects when we don't use DiskCache, images that have been loaded from the network are not saved to disk
> Fix critical bugs on DiskCache

- Source/Fuse.Sensor/SensorModule.uno
- index.d.ts
This fixes typos in the documentation and TypeScript definitions for the newly introduced Fuse.Sensor module.
#1267 #1271
> Fuse.Sensor: fix typos in documentation

- Source/Fuse.Controls.Navigation/NavigatorSwipe.uno
This feature enables swiping gesture for page navigation from the edge of the screen ( left, right, top and bottom ). We can now mimic swipe back gesture from the left edge as in iOS
> Add Page Navigation Swipe from Edges

- CHANGELOG.md
- Source/Fuse.Triggers/Actions/StateTransition.uno
- Source/Fuse.Triggers/Tests/StateGroup.Test.uno
- Source/Fuse.Triggers/Tests/UX/StateGroup.TransitionStateValue.ux
Added `Value` property on `TransitionState` to be able to transition directly to defined state
> Add Value property to TransitionState

- Source/Fuse.Platform/iOS/SystemUI.uno
This method is private, not used and not implemented. Let's remove it.
> Fuse.Platform: drop unused method on iOS

- Source/Fuse.Animations/Attract.uno
- Source/Fuse.Charting/DataSeries.uno
- Source/Fuse.Charting/Plot.uno
- Source/Fuse.Charting/PlotAxis.uno
- Source/Fuse.Charting/PlotAxisLayout.uno
- Source/Fuse.Charting/PlotBar.uno
- Source/Fuse.Charting/PlotCurvePoint.uno
- Source/Fuse.Charting/PlotData.uno
- Source/Fuse.Charting/PlotElement.uno
- Source/Fuse.Charting/PlotExpression.uno
- Source/Fuse.Charting/PlotPoint.uno
- Source/Fuse.Charting/PlotTicks.uno
This should remove the following notice from generated pages at https://fuseopen.com/docs.
This entity is experimental and might be changed or removed in a future release.
Because Fuse.Animations.AttractorConfig is commonly used in Fuse.Charting code, we
also drop the experimental attribute from this class.
> Fuse.Charting: drop experimental attributes

- README.md
What it does:
* adds a badge to show the latest number of financial contributors
* adds a banner displaying contributors to the project on GitHub
* adds a banner displaying all individuals contributing financially on Open Collective
* adds a section displaying all organizations contributing financially on Open Collective, with their logo and a link to their website
(Adapted from https://github.com/fuse-open/fuse-studio/pull/44)
> README: add Open Collective info

- Source/Fuse.Scripting.JavaScript/V8/V8.stuff
- Source/Fuse.Scripting.JavaScript/V8/V8Simple.cpp.uxl
- Source/Fuse.Scripting.JavaScript/V8/include/V8Simple.cpp
This version also includes binaries for x86_64, which are missing in the
current v6.9.427.23 distribution.
> Android: upgrade V8 to v7.6.303.30

- package.json
This will only build libraries that are actually changed, skipping
dependents.
This will make incremental builds faster when making small changes
to a few libraries.
> build: pass --express flag

- CHANGELOG.md
- Source/Fuse.ImageTools/ImageTools.uno
Typo in crop function causing always square crop
> Fix typo in ImageTools.crop

- Source/Fuse.Navigation/Tests/Activated.Test.uno
This has been documented for a while, let's ignore it.
> ignore spuriously failing test

- CHANGELOG.md
- Source/Fuse.Drawing.Surface/LineParser.uno
- Source/Fuse.Drawing.Surface/Tests/LineParser.Test.uno
Adds support to SVGPathParser to process svg path data with serial floating points that are minimized.
I.e. following minimized svg has valid data path (in browser), but not in Fuse
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="16" height="16">
<path d="M19 6H5c-1.1 0-2 .9-2 2v8c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V8c0-1.1-.9-2-2-2zm0 10H5V8h14v8z "></path>
</svg>
```
The problem is curve `c0 1.1.9 2 2 2` being translated to 5 tokens instead of 6.
This PR improves SVGPathParser to properly generate tokens in these cases  (`c 0  1.1 .9 2 2 2`)
> SVGPathParser tokenizer improvement

- .travis.yml
Unsetting instead of assigning empty string avoid getting the following
warning in the build log.
Ignoring configuration file '(null)' because it could not be loaded.
Reason: File could not be parsed due to preprocessing errors:
> travis: unset variable

- Source/Fuse.Scripting.JavaScript/Fuse.Scripting.JavaScript.unoproj
This header is only needed when USE_JAVASCRIPTCORE is defined, and we don't
want it copied on all build targets.
> Fuse.Scripting.JavaScript: skip JSC header unless needed

- Source/Fuse.Models/ModelJavaScript.uno
- Source/Fuse.Scripting/ScriptModule.Require.uno
This will avoid getting the following error when setting the Model attribute
to empty string (can't pass `null` from UX).
Error: : Uncaught require(): module not found:
In: Fuse.Scripting.DiagnosticSubject
Fuse: (model-script):4
> Fuse.Models: allow unsetting Model

- Source/Fuse.Controls.Native/DarkMode.uno
- Source/Fuse.Controls.Native/Fuse.Controls.Native.unoproj
- Source/Fuse.Controls.Native/iOS/ContainerView.h
- Source/Fuse.Controls.Native/iOS/ContainerView.mm
- Source/Fuse.Controls.Native/iOS/GraphicsView.uno
Oh so dark and lovely :smile_cat:
> iOS 13 DarkMode

- Source/Fuse.Controls.Native/DarkMode.uno
Added support for Android Dark Theme to our "Dark Mode" module: https://developer.android.com/guide/topics/ui/look-and-feel/darktheme
Needs Uno PR as well: https://github.com/fuse-open/uno/pull/236
> Android Q(29) - Dark Theme Support

- Source/Fuse.Common/Font.uno
- Source/Fuse.Common/Internal/SystemFont.uno
- Source/Fuse.Common/Internal/iOSSystemFont.uno
- Source/Fuse.Common/SystemFont.uno
- Source/Fuse.Controls.Native/iOS/FontCache.uno
- added iOS13 way of doing SystemFont
- fixed older system font issues with font weight/style
- added reasonable fallbacks for missing font weights for older system font way
> iOS 13 SystemFont Changes + Previous System Font Issues

- Source/Fuse.Reactive.Expressions/UnaryOperator.uno
Pass Flags.None to disable the following run-time warnings:
Warning: This constructor and use of the Is*Optional virtuals is deprecated. Pass the optionals as flags to the constructor, or specifiy Flags.None to avoid the message
Warning: Overiding the UnaryOperator.OnNewOperand/OnLostData is deprecated. Implement `Compute` and call the other constructor, or pass Flags.None, or implement an `Expression` and `ExpressionListener` if you need the behavior (rare).
The other Negate operator found in this file already passes Flags.None,
so I believe this was just forgotten about for LogicalNot.
> Fuse.Reactive.Expressions: fix run-time warnings with LogicalNot

- .travis.yml
- README.md
- package-lock.json
- package.json
This upgrades to the newest version of Uno.
The new version of Uno installs Mono automatically, so we're dropping the Mono requirements. Also doing some light refurbishing in README.
> Upgrade to Uno v1.13

- Source/Fuse.iOS/AppRoot.uno
Caters for when the app is started initially in landscape, then switches to portrait, to allow the recalculation of the height and or left margin when resizing the mask. Initial behaviour was only taking into account starting from portrait and changing to landscape.
> iOS - Auto Resizing Mask Fix

- Source/Fuse.Charting/PlotPoint.uno
- Source/Fuse.Charting/PlotWedge.uno
New properties are needed by variations of pie chart that should not be a full circle, for example to create gauge charts and speedometers.
> Fuse.Charting: add RadialOffset and RadialScale

- Source/Fuse.GeoLocation/Android/AndroidLocationProvider.uno
- Source/Fuse.GeoLocation/GeoLocation.uno
- Source/Fuse.GeoLocation/LocationProvider.uno
- Source/Fuse.GeoLocation/Spoof/SpoofLocationProvider.uno
- Source/Fuse.GeoLocation/iOS/IOSLocationProvider.uno
Allows us to determine the current authorization status of Geo location, so that we can cater for alternative UI regarding the UX. e.g. iOS - When the user hasn't ever set a permission, the status will be undetermined, so we can present a different UI message than that of the status being unauthorized.
> Geo-Location - Added GetAuthorizationStatus

- Source/Fuse.Launcher.InterApp/InterApp/InterAppLauncher.uno
- Source/Fuse.Launcher.InterApp/InterApp/InterAppTrigger.uno
- Source/Fuse.Launcher.InterApp/InterApp/JS.uno
- Source/Fuse.iOS/iOSInterop.uno
Check if app is available, else can open a link (typically to App Store).
For the app that you want to open, you have to know its scheme and whitelist it:
Example:
```
whatsapp://
```
```
<Extensions Backend="CPlusPlus" Condition="iOS">
<Require Condition="iOS" Xcode.Plist.Element>
<![CDATA[
<key>LSApplicationQueriesSchemes</key>
<array>
<string>whatsapp</string>
</array>
]]>
</Require>
</Extensions>
```
> iOS - InterApp - Open app fallback to open a url

- Source/Fuse.Charting/PlotDataItem.uno
This happens quite frequently in a user app and we don't want this to cause
a fatal crash, nor spam the log with error messages. The app seems to work
fine if we simply early-out here instead.
> Fuse.Charting: early-out on attempts to access a disposed object.

- Source/Fuse.Text/Implementation/HarfbuzzFont.uno
- Source/Fuse.Text/Renderer.uno
This replaces the last remaining references to the obsolete
`Uno.Runtime.Implementation.BufferImpl` class.
> Fuse.Text: replace obsolete code

- Source/Fuse.Controls.Native/ImageLoader.uno
Because this is Java code, we can use android.util.Log directly instead of
calling one of many generated and deprecated debug_log() methods.
We want to remove the generated debug_log() methods in the future.
> Fuse.Controls.Native: replace foreign debug_log() calls

- Source/Fuse.Controls.ScrollView/ScrollView.uno
This fixes a small typo in our documentation.
> Fuse.Controls.ScrollView: fix typo in documentation

- README.md
- package.json
It's been observed that --express sometimes gives build-errors, but will
eventually succeed after several attempts. This seems to be caused by a bug
in Uno's caching mechanism, and the problem isn't observed when building
without --express.
Therefore, I want to revert back to building without --express by default and
instead document in README how to use --express.
> build: make --express opt-in

- Tests/ManualTests/ManualTestingApp/ManualTestingApp.unoproj
This gives ManualTestingApp a proper bundle identifier, fixing the following error when building locally using Xcode 11.
error: No profiles for 'com.apps.manualtestingapp' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.apps.manualtestingapp'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'ManualTestingApp' from project 'ManualTestingApp')
** BUILD FAILED **
> ManualTestingApp: set iOS.BundleIdentifier

- Source/Fuse.ImageTools/iOS/ImagePicker.m
- Source/Fuse.Maps/iOS/MapViewDelegate.m
- Source/Fuse.Platform/iOS/KeyboardContext.mm
This fixes some compile-time warnings when building for iOS.
```
/Users/morten/fuselibs/Tests/ManualTests/ManualTestingApp/build/iOS/Debug/src/iOS/MapViewDelegate.m:123:4: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
/Users/morten/fuselibs/Tests/ManualTests/ManualTestingApp/build/iOS/Debug/src/iOS/MapViewDelegate.m:127:34: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
/Users/morten/fuselibs/Tests/ManualTests/ManualTestingApp/build/iOS/Debug/src/iOS/MapViewDelegate.m:129:36: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self] …
```
> iOS: fix compile-time warnings

- Tests/ManualTests/ManualTestingApp/ManualTestingApp.unoproj
This fixes cleartext HTTP request on new Android API.
Related: https://github.com/fuse-open/uno/commit/47cf218d18ff706ccfec3fffda11260199d82339
> ManualTestingApp: enable cleartext traffic on Android

- CHANGELOG.md
- Source/Fuse.Vibration/Vibrate.uno
- Source/Fuse.Vibration/Vibration.uno
- Source/Fuse.Vibration/VibrationModule.uno
On iOS, now you can do feedback vibration by leveraging Taptic Engine. There are 9 types of vibration :
- Soft
- Rigid
- light
- Medium
- Heavy
- Success
- Warning
- Error
- Selection
To activate it, just pass those value to `VibrationType` property
**Example**
```
<StackPanel Margin="20">
<Button Margin="10" Text="Heavy Vibrate">
<Clicked>
<Vibrate VibrationType="Heavy" />
</Clicked>
</Button>
</StackPanel>
```
> Add feedback vibration using Taptic Engine on iOS

- Source/Fuse.Vibration/Vibration.uno
Adding extern(iOS) on this class avoids receiving the following compile-time
error when building for Android, with --no-strip enabled.
Fuse.Vibration.g.cpp:19:10: fatal error: 'UIKit/UIKit.h' file not found
#include <UIKit/UIKit.h>
^~~~~~~~~~~~~~~
> Fuse.Vibration: fix C++ compile-error

- Source/Fuse.Controls.Native/iOS/ImageView.uno
This is a fix when `Image` Component placed inside a `Panel` with no size or alignment specified in `NativeViewHost` environment, 
the `Image` component size will not respect the size of its container, but instead, it will draw in accordance with the size of the image itself and the `Image` component will overlap the size of its container when the image size is larger than the container itself
> Fix Image bounds in NativeViewHost on iOS

- Source/Fuse.PushNotifications/Android/Impl.uno
- Source/Fuse.PushNotifications/Android/PushNotificationReceiver.java
- allows for "deeper" JSON payload to be received, instead of just the first level of key/value pairs
```
push.on("receivedMessage", function(payloadIn, fromNotificationBar) {
console.log("Recieved Push Notification: " + payloadIn);
payload.value = JSON.stringify(payloadIn);
console.log("fromNotificationBar");
console.log(fromNotificationBar);
var notificationData = JSON.parse(payloadIn);
console.log(JSON.stringify(notificationData));
console.log(notificationData.notification);
//Now possible
console.log(notificationData.notification.alert);
console.log(notificationData.notification.alert.title);
console.log(notificationData.customPayload.valueText);
console.log(notificationData.customPayload.value);
});
```
> Android - Push Notifications - JSON Payload Upgrade

- CHANGELOG.md
- Source/Fuse.Auth/Biometric.uno
- Source/Fuse.Auth/Fuse.Auth.unoproj
- Source/Fuse.Auth/triggers/BiometricTrigger.uno
- Source/Fuse.Auth/triggers/actions/BiometricAction.uno
It provides the easiest way to do biometric authentication using a sensor available on the device. This feature adds a new `trigger action` called `<Authenticate/>` and `trigger class` called `<SupportBiometric/>`.
**Example**
```
<JavaScript>
resultHandler: function(data) {
console.dir(data.status) // boolean value true or false
}
}
</JavaScript>
<Panel>
<SupportBiometric>
<Button Text="Sign In With Biometric">
<Clicked>
<Authenticate PromptMessage="We need your Fingerprint" Handler="{resultHandler}" />
</Clicked>
</Button>
</SupportBiometric>
</Panel>
```
**Note**
> This PR require Uno PR: https://github.com/fuse-open/uno/pull/305
> Add Biometric Authentication features

- Source/Fuse.Nodes/RootViewport.uno
This PR replaces references to deprecated `PlatformWindowImpl` in `Fuse.Nodes`.
> Replace uses of obsolete APIs

- CHANGELOG.md
- Source/Fuse.Platform/Android/SystemUI.uno
- Source/Fuse.Platform/SystemUI.uno
- Source/Fuse.Platform/iOS/AppDelegateStatusBar.mm
- Source/Fuse.Platform/iOS/SystemUI.uno
- Source/Fuse.Triggers/Actions/SetWindowOrientation.uno
- Source/Fuse.Triggers/Fuse.Triggers.unoproj
Add `SetWindowOrientation` trigger action. With this trigger action, we can now specify different screen orientation of a `Page` in Navigation.
**Example:**
```
<Page>
<Activated>
<SetWindowOrientation To="LandscapeLeft" />
</Activated>
<Page>
```
> Add trigger action for setting device orientation

- Source/Experimental.Http/BinaryLoader.uno
- Source/Experimental.Http/HttpLoader.uno
- Source/Fuse.Elements/Resources/HttpImageSource.uno
`HttpImageSource` since version 1.12 has support for disk caching to store downloaded images on the local disk using `DiskCache` property, so next time when we loaded image again with the same URL it will pick up from local disk instead of making request to the network. 
But the current implementation of disk caching does not obey Http cache-control header sent by the server. So it always uses a local version even if the server mark image as stale and has to load again from the network.
We introduce `DiskCachePolicy` to give options on how DiskCache should behavior. There are two options: 
- Default: Honor cache-control header from the server
- AlwaysUseLocalCache: Always use local data if available and ignoring the cache-control header
**Note**:
This PR requires Uno PR: …
> Introduce DiskCachePolicy in HttpImageSource

- CHANGELOG.md
- Source/Fuse.Auth/Fuse.Auth.unoproj
- Source/Fuse.Auth/SignInModule.uno
- Source/Fuse.Auth/SignInProvider.uno
- Source/Fuse.Auth/iOS/SignInHelper.h
- Source/Fuse.Auth/iOS/SignInHelper.mm
- Source/Fuse.Auth/triggers/actions/SignInAction.uno
Platform SignIn is a SignIn mechanism that uses `Sign In With Apple` on iOS and `Google SignIn` on Android. There is two API added, `PlatformSignIn` as trigger action and `FuseJS/Auth` as javascript module. 
This module does not provide UI elements of Platform Sign In. (Visual button of Sign In With Apple or Google Sign In Button). Users must design the Sign In Button itself that complies with design guidelines on both platform
> For more information on what are the pre-request when implementing `Sign In With Apple` or `Google Sign In`, you can check the documentation on the Apple developer website or android developer website
> For iOS, add "SystemCapabilities": { "SignInWithApple":true }  in the unoproj file.
The following example shows how to use it:
```
<App>
<JavaScript>
var Auth = …
```
> Introduce Platform Sign In

- Source/Fuse.Controls.ScrollView/ScrollView.uno
This is a fix for https://github.com/fuse-open/fuselibs/issues/1365
> Fix Visual Scroll Position of an element when MinScroll is Negative

- Source/Fuse.Elements/Resources/Exif/Exif.uno
When I observe using the Instruments tool, I saw a small leak every time we process the image to get orientation information
> iOS fix memory leak on get image orientatioon

- Source/Fuse.Controls.Navigation/PageControl.uno
- Source/Fuse.Gestures/Internal/Swiper.uno
- Source/Fuse.Navigation/VisualNavigation.uno
- Source/Fuse.Nodes/Visual.Parameter.uno
- Source/Fuse.Selection/Selectable.uno
- Source/Fuse.Selection/Selection.uno
These properties are used internally for caching purposes, and should not be exposed in the public API, nor show up in docs, etc.
There are instance properties available for Uno programmers. The static selector properties are unlikely to be used directly by external code, and because we are working on 2.0 it is nice to clean-up our public API a little.
> Make static selectors internal

- Source/Fuse.Camera/Android/AndroidCamera.uno
- Source/Fuse.CameraRoll/Android/AndroidCameraRoll.uno
- Source/Fuse.Common/Internal/AndroidSystemFont.uno
- Source/Fuse.Common/Internal/FontListParser.java
- Source/Fuse.Controls.CameraView/Android/NativePhoto.uno
- Source/Fuse.Controls.WebView/Android/FuseWebChromeClient.java
- Source/Fuse.Controls.WebView/Android/FuseWebViewClient.java
- Source/Fuse.Controls.WebView/Android/JsInterface.java
- Source/Fuse.Controls.WebView/Android/ScrollableWebView.java
- Source/Fuse.Controls.WebView/Android/WebViewForeign.uno
- Source/Fuse.Drawing.Surface/Android/GraphicsSurface.uno
- Source/Fuse.Drawing.Surface/Android/GraphicsSurfaceContext.java
- Source/Fuse.Drawing.Surface/Android/LinearGradientStore.java
- Source/Fuse.Drawing.Surface/Android/NativeSurface.uno
- Source/Fuse.Drawing.Surface/Android/Surface.uno
- Source/Fuse.ImageTools/Android/AndroidImageUtils.uno
- Source/Fuse.ImageTools/Android/Image.java
- Source/Fuse.ImageTools/Android/ImageStorageTools.java
- Source/Fuse.ImageTools/Android/ImageUtils.java
- Source/Fuse.Maps/Android/ForeignHelpers.uno
- Source/Fuse.Maps/Android/FuseMap.java
This renames the packages `com.fusetools` and `fuse.android.graphics` to match better with other Java-code in the repo.
The packages are internal Java packages that are unlikely to be used directly by external code, and because we are working on 2.0 it is nice to clean-up our code-base a little.
I have tested the patches locally since May on various Fuse apps I am working on without detecting any issues...
> Java packages

- CHANGELOG.md
- Source/Fuse.Elements/Fuse.Elements.unoproj
- Source/Fuse.Physics/Body.uno
- Source/Fuse.Physics/Draggable.uno
- Source/Fuse.Physics/DraggableTriggers.uno
- Refactor `Draggable` using IGesture System. Credit to @egonyans 
- Introduce `Translation` property to `Draggable` to track translation position when the user drags a visual with `Dragabble` behavior attached. Credit to @egonyans 
- Introduce two new Triggers:
- `DragStarted` Pulse when dragging activity has been started
- `DragEnded` Pulse when dragging activity has been ended
- Drag and Drop API. Experimental support for drag and drop between visual elements. Introduce sets of Triggers:
- `WhileDraggingOver` Activated when Visual that contains `Draggable` behavior and `WhileDraggingOver` trigger is overlapped/intersected with the `Target` Visual property that is defined in `WhileDraggingOver`
- `WhileDroppingBy` Activated when Visual that contain `WhileDroppingBy` trigger being …
> Draggable Enhancement

- Source/Fuse.Platform/iOS/SystemUI.uno
This is a regression fix for a feature introduced in #1354. The bugs reported here: #1374
> Fix iOS device orientation setup, honor the project settings 

- CHANGELOG.md
- Source/Fuse.Controls.Primitives/Behaviors/Shadow.uno
Experimental support for drawing Shadow inside NativeViewHost.
Test Case:
```
<App Background="White">
<ClientPanel Color="White">
<StackPanel Alignment="Center" ItemSpacing="20">
<Rectangle Size="200" Color="Red" StrokeColor="Blue" StrokeWidth="1" CornerRadius="10" ux:Name="rect">
<Shadow Size="10" Distance="5" Color="Green" />
</Rectangle>
<NativeViewHost>
<Rectangle Size="200" Color="Red" StrokeColor="Blue" StrokeWidth="1" CornerRadius="10" ux:Name="rect2">
<Shadow Size="10" Distance="5" Color="Green" />
</Rectangle>
</NativeViewHost>
</StackPanel>
</ClientPanel>
</App>
```
**Note:**
Shadow drawing (distance, size) slightly different between in graphics view and nativeviewhost
> Added support for Shadow Behavior in NativeViewHost

- CHANGELOG.md
- Source/Fuse.Controls.Primitives/Behaviors/Glass.uno
- Source/Fuse.Effects/Fuse.Effects.unoproj
Added support for rendering backdrop filter of glass effect using the new `Glass` behavior
**Example:**
```
<ClientPanel>
<Panel Width="150" Height="70" Alignment="Center">
<Glass Radius="10" Background="image" />
<Text Font="Bold" Value="This is awesome!" Color="Black" Alignment="Center" />
</Panel>
<Image ux:Name="image" Alignment="Center" Margin="20" Background="Purple"
Url="https://fuseopen.com/assets/white-logo.png" />
</ClientPanel>
```
> Experimental support for Glass effect behavior

- Source/Fuse.Reactive.Expressions/StringFunctions.uno
Add `length` function expression for string or array 
**Example:**
```
<ClientPanel>
<LetString ux:Name="s" Value="This is text" />
<JavaScript>
var arr = [1,2,3,4,5]
module.exports = { arr }
</JavaScript>
<StackPanel>
<Text Value="{s}" />
<Text Value="{= length({s})}" />
<Text Value="{arr}" />
<Text Value="{= length({arr})}" />
</StackPanel>
</ClientPanel>
```
also fix a mistake on `indexOf` function
> Add length function

- CHANGELOG.md
- Source/FuseJS/Environment.uno
This will make it easier to display general information of the App, like inside the about page.
Added properties:
- `appTitle`
- `appVersion`
- `appPublisher`
- `copyright`
- `androidTitle`
- `androidVersionNumber`
- `androidVersionCode`
- `iosTitle`
- `iosVersionNumber`
> Expose general information that reside in the .unoproj file in FuseJS/Environment

- Source/Fuse.Controls.DatePicker/Android/DatePicker.uno
- Source/Fuse.Controls.DatePicker/DatePicker.uno
- Source/Fuse.Controls.DatePicker/iOS/DatePicker.uno
- Source/Fuse.Controls.TimePicker/Android/FuseTimePickerDialog.java
- Source/Fuse.Controls.TimePicker/Android/TimePicker.uno
- Source/Fuse.Controls.TimePicker/Fuse.Controls.TimePicker.unoproj
- Source/Fuse.Controls.TimePicker/TimePicker.uno
- Source/Fuse.Controls.TimePicker/iOS/TimePicker.uno
There are 4 styles available:
- Default
- Compact
- Inline
- Wheels (Only available on iOS)
This also fixes the rendering error on iOS 14 as reported in [forum](https://forums.fusetools.com/t/datepicker-not-showing-correctly-on-ios-14-2/8092/3)
> add `Style` property to DatePicker and TimePicker

- CHANGELOG.md
- Source/Fuse.Android.TextRenderer/Internal/StaticLayout.uno
- Source/Fuse.Android.TextRenderer/TextRenderer.uno
- Source/Fuse.Controls.Native/Android/TextView.uno
- Source/Fuse.Controls.Native/Interfaces.uno
- Source/Fuse.Controls.Native/iOS/TextEdit.uno
- Source/Fuse.Controls.Native/iOS/TextView.uno
- Source/Fuse.Controls.Primitives/TextControls/FallbackTextRenderer/TextRenderer.uno
- Source/Fuse.Controls.Primitives/TextControls/FuseTextRenderer/CacheState.uno
- Source/Fuse.Controls.Primitives/TextControls/TextControl.Forwarding.uno
- Source/Fuse.Controls.Primitives/TextControls/TextControl.Properties.uno
- Source/Fuse.Nodes/Visual.FastProperties2.uno
- Source/Fuse.Text/Wrap.uno
- Source/Fuse.iOS.TextRenderer/TextRenderer.uno
Added `MaxLines` property to the `Text` component to limit the number of lines to display when `TextWrapping` property is set to `Wrap`
**Examples**:
```
<ClientPanel>
StackPanel ItemSpacing="10">
<Text Value="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." />
<Text Value="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut …
```
> MaxLines property on Text component

- Source/Fuse.Charting/Tests/FilterObservable.Test.uno
NextInt() has been deprecated since at least v1.9, I believe.
> Fuse.Charting: fix old deprecation warnings in test

- .appveyor.yml
The Mesa 3D library (used here as a software OpenGL renderer) has been
redundant since at least v1.9 because we've since been using ANGLE for
OpenGL support in .NET builds on Windows (translating to Direct3D 9).
> appveyor: drop legacy mesa-download

- tools/doc-export/doc-export.unoproj
Documentation for Fuse.Auth should be included in our API docs, and
therefore also included in the doc-export project.
> doc-export: add Fuse.Auth reference

- Source/Fuse.Controls.CameraView/VideoTools.uno
Related to https://github.com/fuse-open/docs/pull/41
> Fuse.Controls.CameraView: fix type-name typo in doc-comment

- Source/Fuse.Alerts/Fuse.Alerts.unoproj
- Source/Fuse.Alerts/NativeAlerts.uno
- Source/Fuse.Alerts/Triggers.uno
This adds trigger action for showing a native alert dialog.
**Examples**:
```
<JavaScript>
handler: function(data) {
if (data.buttonLabel == 'Yes'){
console.log("yes button clicked")
}
if (data.buttonLabel == 'No'){
console.log("no button clicked")
}
}
};
</JavaScript>
<StackPanel ItemSpacing="10'>
<Button Text="Display Alert" Alignment="Center">
<Clicked>
<ShowAlert Message="Hello world!" OkLabelButton="Yes" Handler="{handler}"/>
</Clicked>
</Button>
<Button Text="Display Confirm" Alignment="Center">
<Clicked>
<ShowConfirm Message="Are you sure want to logout?" OkLabelButton="Yes" CancelLabelButton="No" Handler="{handler}"/>
</Clicked>
</Button>
</StackPanel>
```
> Trigger Action for Native Alerts

- Source/Fuse.Controls.ScrollView/Triggers/WhileScrolling.uno
Trigger that will active while the ScrollView is in motion
**Example**:
```
<App>
<ClientPanel>
<Panel>
<Rectangle ux:Name="indicator" Color="#838383" CornerRadius="5" Width="8" Height="80" Alignment="TopRight"
Opacity="0" />
<ScrollView ux:Name="scrollview">
<ScrollingAnimation>
<Move Y="0.95" Target="indicator" RelativeNode="scrollview" RelativeTo="Size" />
</ScrollingAnimation>
<WhileScrolling>
<Change indicator.Opacity="1" Duration="0.1" DelayBack="1" />
</WhileScrolling>
<StackPanel ItemSpacing="10">
<Each Count="100">
<Panel Height="40" Color="#CDCDCD">
<Text Value="Item #{index()}" Alignment="VerticalCenter" Margin="10" />
</Panel>
</Each>
</StackPanel>
</ScrollView>
</Panel>
</ClientPanel>
</App>
```
> WhileScrolling Trigger

- Source/Fuse.Android.TextRenderer/Fuse.Android.TextRenderer.unoproj
- Source/Fuse.Android.TextRenderer/Internal/StaticLayout.uno
- Source/Fuse.Android.TextRenderer/StaticLayoutBuilder.java
- Source/Fuse.Controls.Primitives/TextControls/MobileTextEdit.uno
This PR contains 2 fixes:
- TextView bugs when we set alignment to the center, on lost focus the text become disappear. the issues reported on #1399
- Fix regression introduced by this PR #1385. the app will crash on Android pre-Marshmallow when we set `TextWrapping` to `Wrap`
> Fix text rendering on Android

- Source/Fuse.Android.Permissions/AndroidPermissionsInternal.uxl
- Source/Fuse.Android.Permissions/Permissions.uxl
Apps with this permission declared in their manifest are rejected when
submitting to Google Play, unless providing a video demonstrating how
this functionality is used in the app.
The problem with some apps is that they aren't really using this feature
so there's nothing to demonstrate, and the only way to publish currently
is to manually edit AndroidManifest.xml, remove the permission, re-run
build.sh, and finally submit the modified AAB/APK.
This patch addresses the problem by not adding this permission
automatically. Apps that really need it will be required to add it
manually. Please report issues if this becomes a problem for anyone.
Closes #1402
> Android: don't add BACKGROUND_LOCATION to manifest

- Source/Fuse.Controls.Primitives/TextControls/MobileTextEdit.uno
This is a workaround fix for the issue: https://github.com/fuse-open/fuselibs/issues/1407. When we set alignment to the center or right on the recent version of Android, on lost focus the text won't visible.
related issue: 
> TextEditRenderer: enable horizontal scrolling only on lower version of android

- Source/Fuse.Controls.Navigation/NavigatorSwipe.uno
Reduce hit size of the edge detection. Now edge navigation will only triggered if you start to swipe really from the edge of the screen. (Previously it can be triggered up until 100pt from the edge)
> Tweak swipe edge navigation

- Source/Fuse.Controls.DatePicker/iOS/DatePicker.uno
- Source/Fuse.Controls.TimePicker/iOS/TimePicker.uno
This is a fix for a regression introduced by https://github.com/fuse-open/fuselibs/pull/1384. First reported on the issue: https://github.com/fuse-open/fuselibs/issues/1419
> add runtime check of iOS version on DatePicker and TimePicker

- Source/Fuse.Drawing.Surface/LineParser.uno
Fixed bugs when drawing SVG path that contains smooth curve (lower letter `s` command) instead of using absolute position, it should use relative position.
Test Case:
```
<Path Size="100" StrokeColor="Blue" StrokeWidth="2" Data="M560.249,690.146v-61.737 c0-16.887,13.619-30.505,30.506-30.505c16.887,0,30.506,13.618,30.506,30.505v61.737c0,16.887-13.619,30.506-30.506,30.506 S560.249,707.032,560.249,690.146z M577.68 628.408 v61.737 c0 7.264 5.811 13.074 13.074 13.074 s13.074-5.811 13.074-13.074 v-61.737 c0-7.263-5.811-13.073-13.074-13.073 S577.68 621.146 577.68 628.408z" />
```
> Fix path 's' command use relative bezier curve

- Source/Fuse.Reactive.Expressions/Color.uno
Added new `hexColor` to convert `float4` to a hex string representation and `rgba` to create color from: 0-255
```
<Rectangle ux:Name="rect" Width="100" Height="40" Color="rgba(255,0,0,255)" />
<Text Value="{= hexColor(Property rect.Color)}" />
<LetFloat ux:Name="r" Value="255" />
<LetFloat ux:Name="g" Value="200" />
<LetFloat ux:Name="b" Value="50" />
<LetFloat ux:Name="a" Value="255" />
<Rectangle  Width="100" Height="40" Color="rgba({r},{g},{b},{a})" >
```
> added hexColor and rgba UX Function

- Source/Fuse.Common/GraphicsWorker.uno
- Source/Fuse.Controls.CameraView/iOS/NativePhoto.uno
- Source/Fuse.Controls.Native/NativeRenderer.uno
- Source/Fuse.Controls.Native/iOS/GraphicsView.uno
- Source/Fuse.Controls.Native/iOS/Helpers.h
- Source/Fuse.Controls.Video/iOS/VideoImpl.mm
- Source/Fuse.Drawing.Surface/CoreGraphics/CoreGraphicsSurface.uno
- Source/Fuse.Drawing.Surface/CoreGraphics/GraphicsSurface.uno
- package.json
This fixes compile errors and enables building using -DMETAL.
The -DMETAL flag was introduced in https://github.com/fuse-open/uno/pull/396.
Apps are crashing so it looks like more work is needed to support
MetalANGLE in Fuselibs.
Closes #1432
> iOS: fix MetalAngle compile errors

- Source/Fuse.Launcher.InAppBrowser/Fuse.Launcher.InAppBrowser.unoproj
- Source/Fuse.Launcher.InAppBrowser/InAppBrowserLauncher.uno
- Source/Fuse.Launcher.InAppBrowser/JS.uno
- Source/Fuse.Launcher.InAppBrowser/Trigger.uno
- Source/Fuse.Launcher/Fuse.Launcher.unoproj
- Source/Fuse.Launcher/Launcher.uno
launch `InAppBrowser` using `SFSafariViewController` on iOS and Chrome `CustomTabs` on Android
```
App Background="#000">
<JavaScript>
module.exports.launch = function(args) {
var inAppBrowser = require("FuseJS/InAppBrowser");
inAppBrowser.openUrl("https://fuseopen.com");
}
</JavaScript>
<StackPanel Margin="20">
<Button Margin="10" Text="Launch InApp Browser">
<Clicked>
<LaunchInAppBrowser Url="https://fuseopen.com" />
</Clicked>
</Button>
<Button Margin="10" Text="Launch InApp Browser Via JS">
<Clicked Handler="{launch}" />
</Button>
</StackPanel>
</App>
```
> InAppBrowser Launcher

- Source/Fuse.Shortcut/Fuse.Shortcut.unoproj
- Source/Fuse.Shortcut/ShortcutModule.uno
- Source/Fuse.Shortcut/ShortcutProvider.uno
- Source/Fuse.Shortcut/iOS/FOShortcutHandler.h
- Source/Fuse.Shortcut/iOS/FOShortcutHandler.m
This module allows you to shows menu items when pressing App Icon on the device home screen. This feature refers to the [home screen actions](https://developer.apple.com/design/human-interface-guidelines/ios/system-capabilities/home-screen-actions/) on iOS and [App Shortcut](https://developer.android.com/guide/topics/ui/shortcuts.html) on Android (introduced in Android 7.1 / API Level 25)
```
<App>
<JavaScript>
var Observable = require("FuseJS/Observable")
var selectedShortcut = new Observable("-")
var shortcut = require("FuseJS/Shortcut");
shortcut.registerShortcuts([
{
id: 'compose',
title: "Compose",
icon: "assets/images/compose.png"
},
{
id: 'profile',
title: "Profile",
icon: "assets/images/user.png"
},
{
id: 'book_store',
title: "Book Store",
icon: "assets/images/book.png"
}
]) …
```
> Introduce Fuse.Shortcut

- Source/Fuse.Controls.Primitives/Behaviors/Glass.uno
Fixed memory leak where the framebuffer after the capture region operation is not released
> Fix memory leak on glass effect

- Source/Fuse.Drawing/Brushes/DashedColor.uno
- Source/Fuse.Drawing/Stroke.uno
Added experimental support for drawing dashed strokes using the new `DashedSize` property on the `Stroke` class
```
<Rectangle Size=300 Color="Yellow">
<Stroke Width="5" DashedSize="10" Color="Red" />
</Rectangle>
```
> Feature: Dashed Strokes

- Source/Fuse.iOS/iOSApp.uno
Currently on iOS polling mechanism to check device orientation is using an old API that is deprecated and when I observe it takes more CPU usage. 
This PR it replaces the `[[UIApplication sharedApplication] statusBarOrientation]` API with the `[[UIDevice currentDevice] orientation]` and can reduce CPU usage up to 1% when the app is in an idle state. And this PR is also fixed some bad indentation
> Change implementation for checking device orientation

- Source/Fuse.Text/icu/i18n/unicode/uconfig.h
This silences warnings from uconfig.h seen when building on Mac with
Xcode 13.
> Fuse.Text: silence C warning on Mac

- Source/Fuse.Controls.WebView/Android/FuseWebChromeClient.java
- Source/Fuse.Controls.WebView/Android/PickImage.uxl
Show a dialog to let us choose either Camera or Gallery to pick an image
to upload, unless multiple files are allowed (not supported).
* Extract _filePathCallback and onReceiveFileChooserValue(), so we can
finish the existing callback to avoid a dead-lock.
* Integrate PickImage by vansuita via UXL.
~~Depends on https://github.com/fuse-open/uno/pull/409 and https://github.com/fuse-open/uno/pull/412.~~
> WebView (Android): Image picker dialog

- Source/Fuse.Controls.WebView/Android/WebViewForeign.uno
- Source/Fuse.Controls.WebView/iOS/WebView.uno
On iOS by enabling edge swipe for history back, and disabling preview a page on long pressing a link, and on Android by hiding zoom button controls
**note**:
This is hard code by means that currently, this PR is not introducing the public property of `WebView` to change the behavior, maybe will do on separate PR. 
> Make WebView more friendly for wrapping a web app

- Source/Fuse.ImageTools/iOS/ImageHelper.m
When photos are edited in iOS and I get them via camera roll return me the same path for both. This modification adds a unique uuid for each path avoiding the error
> Prevent duplicate paths in iOS

- Source/Fuse.LocalNotifications/Android/Impl.uxl
Add the android:exported attribute to silence the following error when targetting Android 12 (API 31):
Apps targeting Android 12 and higher are required to specify an
explicit value for `android:exported` when the corresponding
component has an intent filter defined. [...]
> Fuse.LocalNotifications: Android 12 compatibility fix

- Source/Fuse.Controls.WebView/Android/PickImage.uxl
This upgrades PickImage for Android to version 3.0.01 (latest).
The new major version requires API 31 to build successfully, which was introduced in Uno version 2.5.0.
> Fuse.Controls.WebView: upgrade com.github.jrvansuita:PickImage

- Source/Fuse.Platform/iOS/SystemUI.uno
According to the iOS 16 Release note:
"Attempting to set an orientation on UIDevice via setValue:forKey: isn’t supported and no longer works."
This is a fix using the new API introduced in iOS 16
> Device orientation for iOS 16 compatibility

- Source/Fuse.Scripting/Context.uno
This method converts a JavaScript object to a Uno string containing a JSON object, essentially invoking JSON.stringify() in JavaScript.
> Fuse.Scripting: add Context.Stringify()

- .appveyor.yml
We're still using the old lock-file version so this will avoid seeing warnings in the build log.
* Use 'npx' to run 'uno'
* Use 'npm test' to run tests
> appveyor: use nodejs v14

- Source/Fuse.Controls.ScrollView/ScrollViewSnap.uno
- Source/Fuse.Controls.ScrollView/Triggers/WhileScrollSnapping.uno
Scroll snapping allows you to lock the viewport to a certain location after a user has finished scrolling. You can use the `SnapAlignment` property to control the lock position. Three lock positions are available: ' Start `Center`, and `End`.
The setup that works now is with a `StackPanel` (Horizontal or Vertical)
```
<ScrollView LayoutMode="PreserveVisual" Height="400">
<StackPanel>
<Each Count="100" Reuse="Frame" >
<Panel Color="#AAA">
<Text Value="Data {= index() }"/>
</Panel>
</Each>
</StackPanel>
<ScrollViewSnap SnapAlignment="Center" />
</ScrollView>
```
It's required to use `LayoutMode="PreserveVisual"` on the `ScrollView` and the child element in the `StackPanel` has an equal size
> add Snapping to the ScrollView

- Source/Fuse.Controls.Panels/Panel.Capture.uno
- Source/Fuse.Drawing.Surface/DotNetSurface.uno
This add one `ScriptPromise` called `capture` to the Panel.
**Example**
```
<JavaScript>
save: function (args) {
p.capture().then((file) => {
console.log(file);
})
}
}
</JavaScript>
<StackPanel ux:Name="p">
<Text Value="Demo capture" />
<Button Text="Save" Clicked="{save}" />
</Panel>
```
> Add capability to capture/make screenshot content of a Panel and save it to the file

- Source/Fuse.Common/Json.uno
- Source/Fuse.Storage/UserSettingsImpl.uno
- Source/Fuse.Storage/UserSettingsModule.uno
Currently broken on desktop (NET) because:
- There is no `Json.Stringify` for `Dictionary` object (the implementation is using `Dictionary` object and serialize it to json)
- Shared output file between Apps / Project, so it will overwrite the output between Apps/Project
This will fix those problems.
> Fix desktop implementation of UserSettings Module

- Source/Fuse.PushNotifications/Android/Impl.cpp.uxl
Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined.
> Fuse.PushNotifications: Android 12 compatibility fix (hotfix)

- Source/Fuse.Scripting/NativePromise.uno
Use lambda expressions instead of manually created closure classes.
There was a bug in Uno blocking us from using lambda expressions before, fixed by https://github.com/fuse-open/uno/pull/446.
> Fuse.Scripting: use compiler to generate closures

- Source/Fuse.Alerts/NativeAlerts.uno
- Source/Fuse.Auth/BiometricModule.uno
- Source/Fuse.Auth/SignInModule.uno
- Source/Fuse.Camera/Camera.uno
- Source/Fuse.CameraRoll/CameraRoll.uno
- Source/Fuse.FileSystem/FileSystemModule.uno
- Source/Fuse.GeoLocation/GeoLocation.uno
- Source/Fuse.ImageTools/ImageTools.uno
- Source/Fuse.MediaPicker/MediaPickerModule.uno
- Source/Fuse.Scripting/NativePromise.uno
- Source/Fuse.Storage/StorageModule.uno
- Source/FuseJS/Bundle.uno
- Source/FuseJS/FileReader.uno
- Source/FuseJS/Globals.uno
Make all existing instances of NativePromise receive the Context parameter, and deprecate the old constructors and delegate types.
> Fuse.Scripting: deprecate NativePromise without Context (beta-3.0)

- Source/Fuse.Android/Fuse.Android.unoproj
- Source/Fuse.Controls.DrawingPanel/Bitmap.uno
- Source/Fuse.Controls.DrawingPanel/Drawing.uno
- Source/Fuse.Controls.DrawingPanel/DrawingCompositor.uno
- Source/Fuse.Controls.DrawingPanel/DrawingPanel.ux
- Source/Fuse.Controls.DrawingPanel/DrawingPanel.ux.uno
- Source/Fuse.Controls.DrawingPanel/Fuse.Controls.DrawingPanel.unoproj
- Source/Fuse.Controls.DrawingPanel/NativeCanvas.Android.uno
- Source/Fuse.Controls.DrawingPanel/NativeCanvas.iOS.uno
- Source/Fuse.Controls.DrawingPanel/NativeDrawingPanel.Android.uno
- Source/Fuse.Controls.DrawingPanel/NativeDrawingPanel.iOS.uno
- Source/Fuse.Controls.Native/Fuse.Controls.Native.unoproj
- Source/Fuse.Controls.Native/iOS/CoreGraphics.uno
- Source/Fuse.Controls.Native/iOS/CoreGraphics.uxl
- Source/Fuse.Nodes/Fuse.Nodes.unoproj
A Panel that can be used to draw lines using your finger. As the `DrawingPanel` is native only, it must be contained in a `NativeViewHost`.
To use this control, You need to add a reference to `Fuse.Controls.DrawingPanel` and `Fuse.ImageTools` on your .unoproj file
```
<App Background="White">
<JavaScript>
var drawing = DrawingPanel
undoClicked: function(args) {
drawing.undo();
},
redoClicked: function(args) {
drawing.redo();
},
clearClicked: function(args) {
drawing.clear();
},
clearHistoryClicked: function(args) {
drawing.clearHistory();
}
}
</JavaScript>
<ClientPanel>
<NativeViewHost>
<DockPanel>
<DrawingPanel ux:Name="DrawingPanel" />
<StackPanel Height="70" ItemSpacing="10" Alignment="Center" Padding="10" Dock="Bottom" Orientation="Horizontal">
<Button Text="Undo" …
```
> Feature drawing panel

- Source/Fuse.Scripting.JavaScript/JavaScript.uno
- Source/Fuse.Scripting.JavaScript/TypeScript.uno
This adds a new TypeScript tag and a new Transpile attribute on the existing JavaScript tag, used to enable modern script features.
The UX compiler (located in Uno) will understand these and invoke the FuseJS transpiler accordingly, replacing user-provided code (modern) with transpiled code (ES5) compatible with our JavaScript engine.
The live reload feature in Fuse X will understand these also, transpiling user-provided code to ES5 on the fly.
> Fuse.Scripting.JavaScript: TypeScript and transpiler support (beta-3.0)

- Source/Fuse.Drawing.Surface/DotNet.uxl
- Source/Fuse.Drawing.Surface/DotNetSurface.uno
- Source/Fuse.Drawing.Surface/System.Drawing.Common.stuff
- Source/Fuse.ImageTools/DotNet.uxl
- Source/Fuse.ImageTools/DotNetImageUtils.uno
- Source/Fuse.ImageTools/System.Drawing.Common.stuff
- Source/Fuse.Nodes/Tests/DrawRectsTest/DefineDrawRects.cil.uxl
- Source/Fuse.Nodes/Tests/DrawRectsTest/DrawRects.Test.uno
* Download System.Drawing.Common@6.0.0 from NuGet
* Make System.Windows.Forms references conditional (Windows only)
> Fuse.Drawing.Surface: update assembly references for .NET 6.0 (beta-3.0)

- Source/Fuse.LocalNotifications/Android/Impl.uno
Use a macro that will expand to the package name of the app being built, fixing the build error introduced in 98a3359.
> Fuse.LocalNotifications: fix package name on Android

- Source/Fuse.Android.Permissions/AndroidPermissionsInternal.uno
- Source/Fuse.Android.Permissions/AndroidPermissionsInternal.uxl
- Source/Fuse.Android.Permissions/Permissions.uno
- Source/Fuse.Android.Permissions/Permissions.uxl
- Source/Fuse.PushNotifications/Android/Impl.uno
- Source/Fuse.PushNotifications/Android/PushNotificationReceiver.java
- Source/Fuse.PushNotifications/Common.uno
- Source/Fuse.PushNotifications/Docs/Guide.md
- Source/Fuse.PushNotifications/Fuse.PushNotifications.unoproj
We also needed this PR: https://github.com/fuse-open/uno/pull/504 to make it works
Now, on Android 13 later, we can lazy request permission for push notifications same with iOS. First, define it on the unoproj
```
"Android": {
"PushNotifications": {
"RegisterOnLaunch": false
}
}
```
and in your App, you can call the `register` method to ask for permission. Example:
```
<App>
<JavaScript>
var push = require("FuseJS/Push");
var Observable = require("FuseJS/Observable")
var log = new Observable()
push.on("registrationSucceeded", function(regID) {
console.log("Reg Succeeded: " + regID);
log.value = "Reg Succeeded: " + regID
});
push.on("error", function(reason) {
console.log("Reg Failed: " + reason);
log.value = "Reg Failed: " + reason
});
push.on("receivedMessage", function(payload) { …
```
> Push Notification: fix compatibility with latest Android

- Source/Fuse.Android.TextRenderer/StaticLayoutBuilder.java
- Source/Fuse.Controls.Native/Android/TextEdit.uno
- Source/Fuse.Controls.Native/Android/TextView.uno
- Source/Fuse.Controls.Primitives/TextControls/MobileTextEdit.uno
- Source/Fuse.Controls.Video/Android/VideoPlayer.uno
- Source/Fuse.Controls.WebView/Android/FuseWebChromeClient.java
- Source/Fuse.MediaPicker/Android/MediaPickerImpl.java
- Source/Fuse.Platform/Android/SystemUI.uno
- Source/Fuse.PushNotifications/iOS/Impl.uno
- Source/Fuse.Vibration/Vibration.uno
Since we are raising the minimum OS requirement for Andriod to API level 19 (https://github.com/fuse-open/uno/pull/504) and iOS to iOS 11 (https://github.com/fuse-open/uno/pull/476) This will clean up some unnecessary runtime OS version check
> Clean up runtime OS version check

- Source/Fuse.PushNotifications/Android/RemoveAdvertisingId.uxl
- Source/Fuse.PushNotifications/Fuse.PushNotifications.unoproj
This removes the AD_ID permission from AndroidManifest to fix the following error when submitting an app in Google Play Console:
This version includes the permission com.google.android.gms.permission.AD_ID,
but your Play Console statement says that your app does not use the
advertising ID.
The AD_ID permission was most likely introduced when upgrading firebase packages in 90b53e3.
Pass -DANDROID_AD_ID_PERMISSION to "uno build" if you wish to keep this permission in your AndroidManifest.
> Fuse.PushNotifications: remove AD_ID permission

- Source/Fuse.Scripting.JavaScript/V8/lib/DotNet.stuff
- Source/Fuse.Scripting.JavaScript/V8/lib/OSX.stuff
This upgrades V8.Simple.net assemblies (macOS and Windows) to .NET 6.0.
> Fuse.Scripting.JavaScript: upgrade V8.Simple.net (beta-3.0)

- Source/Fuse.Maps/Android/MapView.uno
This is the minimum version required to be published on Google Play.
Reported on Slack: https://fusecommunity.slack.com/archives/CGV5ZLY85/p1699546723472489
> Fuse.Maps: com.google.android.gms:play-services-maps -> 17.0.0

- Source/Fuse.Controls.Video/Video.uno
- Source/Fuse.Drawing.Surface/CoreGraphics/CoreGraphicsSurface.uno
- Source/Fuse.Drawing.Surface/CoreGraphics/GraphicsSurface.uno
- Source/Fuse.Drawing.Surface/CoreGraphics/NativeSurface.uno
- Source/Fuse.Drawing.Surface/Fuse.Drawing.Surface.unoproj
- Source/Fuse.Drawing.Surface/SurfaceManager.uno
- Source/Fuse.FileSystem/UnifiedPaths.uno
- Source/Fuse.Platform/iOS/SystemUI.uno
- Source/Fuse.PushNotifications/Docs/AppleSpecifics.md
- Source/Fuse.Reactive.Bindings/Instantiator.uno
- Source/Fuse.Reactive.Expressions/Device.uno
- Source/Fuse.Reactive.Expressions/PlatformFunctions.uno
- Source/Fuse.Scripting.JavaScript/V8/V8Simple.cpp.uxl
- Source/Fuse.Text/README.md
- Tests/ManualTests/ManualTestingApp/DeviceInfo/DeviceInfo.ux
- Tests/ManualTests/ManualTestingApp/Update/UpdatePage.ux.uno
This deprecates the isOSX() function. Please use isMac() instead.
Prefer to use MAC in compile-time conditionals.
XCode -> Xcode
Prefer to say macOS and Xcode in documentation.
> OS X -> macOS (beta-3.0)

- Source/Fuse.Controls.CameraView/Android/CameraView.uno
- Source/Fuse.Controls.Video/Android/VideoPlayer.uno
This PR also fix memory leak on `<Video>` component reported on android Logcat because FileDescriptor is not closed.
> Fix Android CameraView not showing on Android 13 or later because of permissions

- Source/Fuse.Controls.Native/Android/Java/FuseScrollView.java
- Source/Fuse.Controls.Native/Android/Java/HorizontalScrollView.java
- Source/Fuse.Controls.Native/Android/Java/ScrollInteractionEventHandler.java
- Source/Fuse.Controls.Native/Android/Java/VerticalScrollView.java
- Source/Fuse.Controls.Native/Android/ScrollView.uno
- Source/Fuse.Controls.Native/Fuse.Controls.Native.unoproj
- Source/Fuse.Controls.Native/Interfaces.uno
- Source/Fuse.Controls.Native/iOS/Helpers.h
- Source/Fuse.Controls.Native/iOS/Helpers.mm
- Source/Fuse.Controls.Native/iOS/ScrollView.uno
- Source/Fuse.Controls.ScrollView/ScrollView.Native.uno
- Source/Fuse.Controls.ScrollView/ScrollView.uno
- Source/Fuse.Controls.ScrollView/Scroller.uno
- Source/Fuse.Controls.Video/Android/VideoPlayer.uno
- Source/Fuse.Nodes/Visual.Layout.uno
This PR makes:
- `UserScroll` Property works on native platform scrollView
-  `ScrollTo` or `Goto` action works on native platform scrollview
-  `BringIntoView` action works on native platform scrollview
-  `WhileInteracting` trigger works on native platform
Silent warning and deprecated on android media player
> Native ScrollView feature parity with the Graphics Mode

- Source/Fuse.Controls.CameraView/VideoTools.uno
- Source/Fuse.Controls.Primitives/Behaviors/Shadow.uno
Fix crash `EXC_BAD_ACCESS` when using `<Shadow />` behavior on `NativeViewHosts` if the shadow removed.
This PR also include fix iOS deprecated warning when saving video to camera roll using `FuseJS/VideoTools` because of old `ALAssetsLibrary` that will be removed when iOS 18 come out.
> iOS fix crash bugs on removing shadow

- Source/Fuse.Controls.Native/Android/Java/FuseScrollView.java
Fix regression introduced in https://github.com/fuse-open/fuselibs/pull/1268 where ScrollView are not able to nested with another ScrollView with horizontal orientation (horizontal scrolling is not worked)
use case:
```
<App>
<ClientPanel>
<ScrollView>
<StackPanel ItemSpacing="10">
<Each Count="5">
<Panel Height="60" ux:Name="p" Color="#ccc">
<Clicked>
<Scale Factor="2" Duration="0.2" />
</Clicked>
</Panel>
</Each>
<Panel Height="100">
<ScrollView AllowedScrollDirections="Horizontal">
<StackPanel ItemSpacing="10" Orientation="Horizontal">
<Each Count="10">
<Panel Height="100" Width="100" ux:Name="p" Color="#0f0">
<Clicked>
<Scale Factor="2" Duration="0.2" />
</Clicked>
</Panel>
</Each>
</StackPanel>
</ScrollView>
</Panel>
<Each Count="15">
<Panel Height="60" ux:Name="p" Color="#ccc"> …
```
> Fix Android native ScrollView where nested with horizontal ScrollView

- Source/Fuse.Android/AndroidApp.uno
- Source/Fuse.iOS/iOSApp.uno
Since all the primitive controls / components now supports native UI, We can switch the default rendering system for Android and iOS using Native Rendering instead of Graphics Rendering (OpenGL). 
The benefits of switch it can increase application performances and reduce memory usages. And since we are working on Fuse version 3.0 I think this is also the perfect moment to do so.
For component that need to render in native UI such as `MapView` or `WebView` now it doesn't have to wrap it inside `NativeViewHost` tag. But if some part of the Application want to render using OpenGL because it using package from `Fuse.Effects` such as `Blur` for blurring image or video, it needs to be wrapped inside `GraphicsView`. 
For users want to switch the default rendering back to the Graphics (OpenGL) …
> Switch Default iOS and Android Rendering

- Source/Fuse.Maps/iOS/MapView.uno
Memory usage continue to reside even though MapView has been removed from the UI Tree, This is because something was missed when destroying the object.
> iOS MapView fix memory leaks 

- Source/Fuse.Controls.Native/Android/Slider.uno
- Source/Fuse.Controls.Primitives/RangeControls/RangeControl.uno
On Android, when toying with `Video` Control using `Progress` property and bind it with Sliders Value, because of the two-way binding, the Sliders value always keep Progress value of Video control to restart from beginning so that the video wont play. To fix the issue, we only dispatch notification of progress changes only when triggered by user and not by the value binding.
test case:
```
<DockPanel>
<Slider ux:Name="_slider" Minimum="0" Maximum="1" Dock="Top" />
<Video ux:Name="_video" StretchMode="Fill" IsLooping="true" Url="https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" Progress="{Property _slider.Value}">
</DockPanel>
```
> Native Slider Android: fix bug recursive setting value

- Source/Fuse.Controls.Native/Android/Java/FuseScrollView.java
When we define `ScrollView` content such as `StackPanel` with padding, the bottom padding will not work, This is default behavior how Android Scrollview calculate layout, see: https://stackoverflow.com/questions/17124680/scrollview-doesnt-scroll-to-the-margin-at-the-bottom?rq=3. So to fix it we need to wrap the content with container as suggested on the link.
Test Case:
```xml
<App>
<ClientPanel>
<JavaScript>
var Observable = require("FuseJS/Observable")
var items = new Observable(1,2,3,4,5,6,7,8,9,10)
items,
addItem: function() {
items.add(11)
}
}
</JavaScript>
<StackPanel Dock="Top" Height="100">
<Button Text="Add">
<Clicked Handler="{addItem}" />
</Button>
</StackPanel>
<ScrollView ux:Name="scroll">
<StackPanel Padding="20" ItemSpacing="15" Color="Red" …
```
> Fix Android Scrollview with content padding

- Source/Fuse.Nodes/ViewHandle.Android.uno
On some rare case, Application will go crash if we do component transformation such as `Scale`, `Rotate` because of bad calculation (Float.NaN), we need more investigation on how it came like that. but in meanwhile we add sanitary check before  transformation
> android fix crash on layout transformation

- Source/Fuse.Controls.Native/Android/Java/FuseScrollView.java
- Source/Fuse.Controls.Native/Android/Java/HorizontalScrollView.java
- Source/Fuse.Controls.Native/Android/Java/VerticalScrollView.java
- Source/Fuse.Controls.Native/Android/ScrollView.uno
- Source/Fuse.Controls.Native/Interfaces.uno
- Source/Fuse.Controls.Native/iOS/ScrollView.uno
- Source/Fuse.Controls.ScrollView/ScrollView.Native.uno
- Implement Bounce Effect on Android Native ScrollView in order to make SnapMin/MaxTransform works properly on Android.
- `SnapMinTransform` and `SnapMaxTransform` property now works on Native ScrollView both on Android and iOS,
> Implement native Scrollview snap min/max and Android bounce scroll

- Source/Fuse.Maps/Android/FuseMap.java
Handling for potential crash due to the callback is null. This can be happened especially when Previewing App.
> Android MapView Sanitary Check
