fuse-open/fuselibs

- Source/Fuse.Reactive/Fuse.Reactive.unoproj
- Source/Fuse.Testing/JavaScriptTest.uno
- Source/Fuse.Testing/TestRootPanel.uno
This fixes the broken tests after updating uno and merging release-1.0
> Fix broken tests

- Source/Fuse.Controls.Primitives/TextControls/FuseTextEdit.uno
- Source/Fuse.Reactive.JavaScript/RootableScriptModule.uno
These are a couple of trivial warnings on the release-branch. Let's get rid of them.
> Fix trivial warnings

- Source/Fuse.Controls.WebView/WebView.uno
- Source/Fuse.Share/ShareModule.uno
This fixes a couple of annoying warnings.
> Fix warnings

- CHANGELOG.md
- Source/Fuse.Controls.Panels/Container.uno
- Source/Fuse.Controls.Panels/Tests/Container.Test.uno
- Source/Fuse.Controls.Panels/Tests/UX/Issue-public-53.ux
Fixes #53 - NRE in Container.uno
> Add fix and test for issue fuselibs-public #53

- CHANGELOG.md
- Source/Fuse.Elements/LayoutFunctions.uno
- Source/Fuse.Elements/Tests/Fuse.Elements.Test.unoproj
- Source/Fuse.Elements/Tests/LayoutFunctions.Test.uno
- Source/Fuse.Elements/Tests/UX/LayoutFunctions.Issue4189.ux
fixes https://github.com/fusetools/fuselibs/issues/4189
> fixes x,y,width,height functions for already rooted nodes

- Source/Fuse.Common/GraphicsWorker.uno
Use an AutoResetEvent to prevent the thread from constantly looping. Now it will only run whenever there is work in the work Queue.
> GraphicsWorker: Use AutoResetEvent for thread scheduling

- Source/Fuse.Reactive.JavaScript/JavaScript.uno
> Add note about latest supported JavaScript version.

- Source/Fuse.Controls.Navigation/PageView.uno
- Add example of how it relates to Navigator
- Less confusing description (esp. removing the word "specialized")
- Describe the use-case
> Cleanup PageView docs

- CHANGELOG.md
- Source/Fuse.Elements/Internal/ImageContainer.uno
> ImageContainer: fix inifinte recursion bug

- Source/FuseJS/Tests/Bundle.Test.uno
> FuseJS: ignore BundleTests.TestExtract

- CHANGELOG.md
- Source/Fuse.Common/Tests/FuseTest/DudElement.uno
- Source/Fuse.Controls.Panels/LayoutControl.uno
- Source/Fuse.Navigation/VisualNavigation.uno
- Source/Fuse.Nodes/Visual.Children.uno
- Source/Fuse.Reactive.Bindings/Instance.uno
- Source/Fuse.Reactive.JavaScript/Tests/EachTest.uno
- Source/Fuse.Reactive.JavaScript/Tests/UX/Each.Reuse.ux
- Source/Fuse.Reactive.JavaScript/Tests/UX/Each.ReuseTemplates.ux
Adds the `Each.Reuse` property to allow reusing existing nodes.
This experimental feature has some limtiations:
- https://github.com/fusetools/fuselibs/issues/4218
- https://github.com/fusetools/fuselibs/issues/4217
- https://github.com/fusetools/fuselibs/issues/4219  (More of a feature)
> Each reuse

- Source/Fuse.Controls.ScrollView/Triggers/WhileScrolled.uno
The @see directive was wrongly used
> Fixed a couple cases of wrongly formatted doc

- Source/Fuse.Common/Profiling.uno
- Source/Fuse.Elements/Caching/Cache.uno
- Source/Fuse.Elements/Element.Drawing.uno
Optimizations and improvements to make Fuse.Profiling more precise and usfeul
> Faster & better Fuse.Profiling

- CHANGELOG.md
- Source/Fuse.Common/Fuse.Common.unoproj
- Source/Fuse.Common/Json.Parse.uno
- Source/Fuse.Common/Json.uno
- Source/Fuse.Reactive.Expressions/Parameter.uno
- Source/Fuse.Reactive.JavaScript/Tests/UX/Expressions.Parameter.ux
- Source/Fuse.Reactive.JavaScript/Tests/UX/Observable.Parameter.ux
- Source/Fuse.Reactive.JavaScript/Tests/UXExpressionsTest.uno
UX expressions improvements. Added parameter(page) function which returns the routing parameter of the page parsed as an JSON string.
> UX parameter() function

- CHANGELOG.md
- Source/Fuse.Navigation/NavigationPageProxy.uno
- Source/Fuse.Navigation/RoutePageProxy.uno
fixes https://github.com/fusetools/fuselibs/issues/4246
> fixes https://github.com/fusetools/fuselibs/issues/4246

- CHANGELOG.md
- Source/Fuse.Navigation/FindRouter.uno
- Source/Fuse.Navigation/Tests/FindRouter.Test.uno
- Source/Fuse.Navigation/Tests/UX/FindRouter.Basic.ux
> adding FindRouter

- CHANGELOG.md
- Source/Fuse.Controls.Navigation/Tests/Router.Test.uno
- Source/Fuse.Controls.Navigation/Tests/UX/Router.RelativeNest.ux
- Source/Fuse.Controls.Navigation/Tests/UX/Router.RelativeNestModify.ux
- Source/Fuse.Navigation/Router.ScriptClass.uno
- Source/Fuse.Navigation/Router.uno
Fixes https://github.com/fusetools/fuselibs/issues/4196
Relatively minor functional code changes plus better test coverage.
- [-] Documentation: no API change
> Router Relative Fix

- Source/Fuse.Controls.Primitives/TextControls/MobileTextEdit.uno
Fixes https://github.com/fusetools/fuselibs-public/issues/197
Regressed in f791ebbc8a20b0d53b6d94a0ae392eab5cfa96ee
> Android: Fix TextAlignment regression

- CHANGELOG.md
- Source/Fuse.Share/ios/iOSShareImpl.uno
> Fuse.Share: crashfix for iPads

- Source/Fuse.Reactive.Bindings/InstantiatorFunction.uno
- Source/Fuse.Reactive.Bindings/Tests/UX/Each.Function.Basic.ux
- Source/Fuse.Reactive.Expressions/VarArgFunction.uno
- Source/Fuse.Reactive.Expressions/VectorFunctions.uno
- Source/Fuse.Reactive.JavaScript/Tests/VarArgsTest.uno
fixes https://github.com/fusetools/fuselibs-public/issues/205
- [-] Changelog: no change to released API yet
> Index() with parameters

- Source/Fuse.Reactive.Bindings/Instance.API.uno
- Source/Fuse.Reactive.Bindings/Instance.uno
- Source/Fuse.Reactive.Bindings/Tests/EachTest.uno
- Source/Fuse.Reactive.Bindings/Tests/UX/Each.DoubleSubscribe.ux
This fixes the unreleased regression https://github.com/fusetools/fuselibs-public/issues/227
> Hotfix for 1.2 - Regression in Each double subscribe

- Source/Fuse.Selection/Tests/Selection.Test.uno
- Source/Fuse.Selection/Tests/UX/Selection.SubscribeInit.ux
> catches a change duckers might make in his branch

- CHANGELOG.md
- Source/Fuse.Navigation/Activated.uno
- Source/Fuse.Navigation/EdgeNavigation.uno
- Source/Fuse.Navigation/RoutePageProxy.uno
- Source/Fuse.Navigation/Tests/Activated.Test.uno
- Source/Fuse.Navigation/Tests/UX/Activated.EdgeNavigator.ux
- Source/Fuse.Navigation/WhileNavigationTriggers.uno
I'm not entirely happy with how I fixed EdgeNavigator but I saw no other simple short-term solution, especially not for a hotfix. A lot of the clarified stuff was undefined before, so it shouldn't be backwards incompatible. Some stuff is still undefined unfortunately.
fixes https://github.com/fusetools/fuselibs-public/issues/223
> Fixes Activation and EdgeNavigator

- Source/Fuse.Gestures/Tests/Gesture.Test.uno
- Source/Fuse.Nodes/Visual.BeginRemove.uno
- Source/Fuse.Reactive.Bindings/Instance.WindowItems.uno
- Source/Fuse.Reactive.Bindings/Instance.uno
- Source/Fuse.Reactive.Bindings/Tests/EachTest.uno
- Source/Fuse.Reactive.Bindings/Tests/UX/Each.ReplaceWithLessData.ux
fixes a regression in 1.2 in Each for removing nodes
It's an alternate solution to https://github.com/fusetools/fuselibs-public/pull/258
> Detects and fixes a regression in 1.2 with Each node removal (Alternate fix)

- CHANGELOG.md
- Source/Fuse.Common/UpdateManager.uno
- Source/Fuse.Controls.ScrollView/Tests/UX/WhileVisibeInScrollView.Bypass.ux
- Source/Fuse.Controls.ScrollView/Tests/UX/WhileVisibleInScrollView.Placed.ux
- Source/Fuse.Controls.ScrollView/Tests/WhileVisibleInScrollView.Test.uno
- Source/Fuse.Controls.ScrollView/Triggers/WhileVisibleInScrollView.uno
- Source/Fuse.Nodes/Node.Rooting.uno
- Source/Fuse.Triggers/Tests/Internal/SetupHelper.uno
- Source/Fuse.Triggers/Tests/Trigger.Test.uno
- Source/Fuse.Triggers/Tests/UX/Trigger.DeferredRootGroup.ux
- Source/Fuse.Triggers/Tests/WhileDefer.uno
- Source/Fuse.Triggers/Trigger.uno
Fixes https://github.com/fusetools/fuselibs-public/issues/265
This PR includes the https://github.com/fusetools/fuselibs-public/pull/266 as it builds on that fix.
> Fixed root grouping to consider deferred actions and placement

- Source/Fuse.Common/UpdateManager.uno
- Source/Fuse.Controls/Tests/Panel.Test.uno
- Source/Fuse.Nodes/Tests/Fuse.Nodes.Test/NodeGroup.Test.uno
- Source/Fuse.Nodes/Visual.BeginRemove.uno
- Source/Fuse.Triggers/Tests/Trigger.Test.uno
- [-] Changelog - no relevant public changes
- [-] Tests - covered by existing tests, in particular it would fix one merged into the 1.2 branch
> Deferred BeginRemove action, improved handling in UpdateManager

- Source/Fuse.Controls.WebView/EvaluateJS.uno
- Tests/ManualTests/ManualTestingApp/Singles/WebViewPage.ux
fixes https://github.com/fusetools/fuselibs-public/issues/262
I'd like to add a test case to the ManualTestPlan for EvaluateJS before merging this.
- [-] Changelog - hasn't made a release
- [-] Documentation - not relevant
> Fixes EvaluateJS crash

- CHANGELOG.md
- Source/Fuse.Common/FastMatrix.uno
- Source/Fuse.Elements/Caching/ElementBatch.uno
- Source/Fuse.Nodes/VisualBounds.uno
> Optimized how the ElementBatcher calculates renderbounds for larger lists

- CHANGELOG.md
- Source/Fuse.Common/UpdateManager.uno
> Optimizes the deferred actions queue to deal better with high numbers of inserts in a single frame

- Source/Fuse.Nodes/Tests/DrawRectsTest/DrawRects.Test.uno
See https://github.com/fusetools/fuselibs-public/issues/297 for more info. Changelog/documentation/tests aren't appropriate here.
> Ignore draw rect video tests

- Source/Fuse.Controls.Navigation/PageIndicator.uno
- Source/Fuse.Controls/ContentControl.uno
- Source/Fuse.Controls/Viewport.uno
- Source/Fuse.Nodes/VisualBounds.uno
These fix obsoletion-warnings in #301
> Fix obsoletions

- CHANGELOG.md
- Source/Fuse.Controls/Viewport.uno
- Source/Fuse.Nodes/VisualBounds.uno
This is simply a back-port of #261 to release-1.2. Should be trivial.
> Back-port #261 to release-1.2

- Source/Fuse.Reactive.JavaScript/Observable.uno
> Typo fix: supressCallback -> suppressCallback

- CHANGELOG.md
- Source/Fuse.Reactive.Bindings/Instance.WindowItems.uno
- Source/Fuse.Reactive.Bindings/Tests/EachTest.uno
- Source/Fuse.Reactive.Bindings/Tests/UX/Each.ReuseRemove.ux
fixes https://github.com/fusetools/fuselibs-public/issues/311
- [-] Documentation - no api change
> fixes https://github.com/fusetools/fuselibs-public/issues/311

- CHANGELOG.md
- Source/Fuse.Reactive.JavaScript/Observable.uno
- Source/Fuse.Reactive.JavaScript/Tests/JsOrderingTest.uno
- Source/Fuse.Reactive.JavaScript/Tests/UX/JsOrdering.Basic.ux
- Source/Fuse.Reactive.JavaScript/Tests/UX/JsOrdering.Function.ux
- Source/Fuse.Reactive.JavaScript/ThreadWorker.Mirror.uno
- Source/Fuse.Reactive.JavaScript/ThreadWorker.uno
Fixes https://github.com/fusetools/fuselibs-public/issues/324
> Fixes JS->UI callback dispatch order issues 

- README.md
This should make it a bit easier to get things up and running on a
clean machine (or docker-image).
> README: add a requirements section

- CHANGELOG.md
- Source/Fuse.Controls.Primitives/Shapes/Ellipse.uno
- Source/Fuse.Controls.Primitives/Tests/Ellipse.Test.uno
- Source/Fuse.Controls.Primitives/Tests/UX/Ellipse.HitTest.ux
- [-] Documentation - no api change (fixes missing feature)
> adds hit testing to Ellipse, useful for pie charts

- CHANGELOG.md
- Source/Fuse.Controls.Navigation/NavigationControl.Pages.uno
- Source/Fuse.Controls.Navigation/NavigationControl.uno
- Source/Fuse.Controls.Navigation/Navigator.Pages.uno
- Source/Fuse.Controls.Navigation/Navigator.uno
- Source/Fuse.Controls.Navigation/Tests/Navigator.Test.uno
- Source/Fuse.Controls.Navigation/Tests/UX/Navigator.Pages.ux
- Source/Fuse.Reactive/Fuse.Reactive.unoproj
Implements the base feature neede for state driven navigation
> Navigator.Pages feature

- Source/Fuse.Common/NameValuePair.uno
- Source/Fuse.Common/Tests/FuseTest/DudElement.uno
- Source/Fuse.Reactive.Expressions/Object.uno
- Source/Fuse.Reactive.Expressions/Tests/ExpressionFormat.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/UX/ExpressionFormat.Array.ux
- Source/Fuse.Reactive.Expressions/Tests/UX/ExpressionFormat.ArrayObject.ux
- Source/Fuse.Reactive.Expressions/VarArgFunction.uno
- Source/Fuse.Reactive.Expressions/VectorFunctions.uno
Replaces https://github.com/fusetools/fuselibs-public/pull/337
Fixes https://github.com/fusetools/fuselibs-public/issues/274
- [-] Changelog - I don't believe any changes affect already public API, nor do they introduce any value on their own (needed to support features in other branches)
> Feature name value pair objects

- Source/Fuse.Common/UpdateManager.uno
- Source/Fuse.Controls.ScrollView/ScrollView.Layout.uno
- Source/Fuse.Controls.ScrollView/ScrollView.uno
- Source/Fuse.Controls.ScrollView/ScrollViewPager.uno
- Source/Fuse.Controls.ScrollView/Scroller.uno
- Source/Fuse.Controls.ScrollView/Tests/ScrollView.Test.uno
- Source/Fuse.Motion/Simulation/BoundedRegion2D.uno
- Source/Fuse.Triggers/Tests/WhileDefer.uno
- Tests/ManualTests/ManualTestingApp/MainView.ux
- Tests/ManualTests/ManualTestingApp/Singles/ScrollViewPager.ux
Fixes some abrupt position changes and odd corner cases.
- [-] Changelog - primarily fixes an unreleased feature
- [-] Documentation - no API change
> Fix scroll view pager

- Source/Fuse.Elements/Caching/Cache.uno
- Source/Fuse.Elements/Caching/ElementAtlas.uno
- Source/Fuse.Elements/Caching/ElementBatch.uno
- Source/Fuse.Elements/Caching/ElementBatcher.uno
This is just cleanups that makes this code IMO much more sane.
> Cleanup caching-rects in batcher

- CHANGELOG.md
- Source/Fuse.Reactive.Bindings/Instance.WindowItems.uno
- Source/Fuse.Reactive.Bindings/Tests/EachTest.uno
- Source/Fuse.Reactive.Bindings/Tests/UX/Each.ReplaceList.ux
Also added test for this case.
> Fixed a defect in Each when replacing Items with an empty list

- .travis.yml
This is smaller and faster to install, and ends up saving us 8 minutes per build. Yay :)
> travis: use the mono-build Fuse ship with

- Source/Fuse.Navigation/Navigation.Locators.uno
- Source/Fuse.Navigation/Tests/UX/WhileHistory.GoBackBehavior.ux
- Source/Fuse.Navigation/Tests/WhileHistory.Test.uno
- Source/Fuse.Navigation/WhileCanGoBack.uno
fixes https://github.com/fusetools/fuselibs-public/issues/405
- [-] Changelog - fixes an unreleased regression
> Fixes a IBaseNavigation location defect

- CHANGELOG.md
- Source/Fuse.Controls.Navigation/NavigationControl.Pages.uno
- Source/Fuse.Controls.Navigation/NavigationControl.uno
- Source/Fuse.Controls.Navigation/Navigator.uno
- Source/Fuse.Controls.Navigation/PageControl.Pages.uno
- Source/Fuse.Controls.Navigation/PageControl.uno
- Source/Fuse.Controls.Navigation/Tests/PageControl.Test.uno
- Source/Fuse.Controls.Navigation/Tests/UX/PageControl.Active.ux
- Source/Fuse.Controls.Navigation/Tests/UX/PageControl.DynamicActiveIndex.ux
- Source/Fuse.Controls.Navigation/Tests/UX/PageControl.Empty.ux
- Source/Fuse.Gestures/Tests/Gesture.Test.uno
- Source/Fuse.Navigation/DynamicLinearNavigation.uno
- Source/Fuse.Navigation/Tests/DynamicLinearNavigation.Test.uno
- Source/Fuse.Navigation/Tests/UX/DynamicLinearNavigation.Active.ux
- Source/Fuse.Navigation/Tests/UX/DynamicLinearNavigation.Basic.ux
- Source/Fuse.Navigation/Tests/UX/DynamicLinearNavigation.Index.ux
Adds the `PageControl.Pages` feature
Blocked/PR required for this merge: https://github.com/fusetools/fuselibs-public/pull/412
I will likely rebase once that one is merged
> PageControl.Pages

- Source/Fuse.Nodes/Node.Rooting.uno
- Source/Fuse.Nodes/Tests/Rooting.Test.uno
- Source/Fuse.Nodes/Tests/UX/Rooting.DoubleRooting.ux
- Source/Fuse.Nodes/Visual.uno
fixes https://github.com/fusetools/fuselibs-public/issues/430
> fixing issue with double rooting with known bindings

- Source/Fuse.Reactive/Fuse.Reactive.unoproj
> give access to IObservable to charting test

- CHANGELOG.md
- Source/Fuse.Controls.Native/Android/CanvasViewGroup.uno
- Source/Fuse.Controls.Native/iOS/CanvasViewGroup.uno
- Source/Fuse.Nodes/ViewHandle.Android.uno
- Source/Fuse.Nodes/ViewHandle.iOS.uno
> ViewHandle invalidation opt-in

- Source/Fuse.Controls.Navigation/NavigationControl.uno
- Source/Fuse.Controls.Navigation/PageControl.uno
- Source/Fuse.Controls.Navigation/Tests/PageControl.Test.uno
- Source/Fuse.Controls.Navigation/Tests/UX/PageControl.Visibility.ux
- Source/Fuse.Controls.Navigation/Tests/UX/PageControl.WhileActive.ux
- Source/Fuse.Controls.Navigation/Tests/UX/PageControl.WhileTrigger.ux
- Source/Fuse.Controls.Navigation/Tests/UX/PageControl.WhileTrigger2.ux
- Source/Fuse.Navigation/DynamicLinearNavigation.uno
Relatively minor fixes with supporting test cases. These were regressions.
- [-] Changelog - regression not released
- [-] Documentation - no API changes
> Navigation fixes

- Source/Fuse.Controls.Navigation/Docs/Navigator.md
- Source/Fuse.Controls.Navigation/NavigationActions.uno
- Source/Fuse.Controls.Navigation/NavigationControl.uno
fixes https://github.com/fusetools/fuse-docs/issues/827
- [-] Tests
> Adds docs for ReleasePage

- CHANGELOG.md
- Source/Fuse.Controls.Primitives/Tests/Circle.Test.uno
- Source/Fuse.Controls.Primitives/Tests/UX/Circle.Rendering.ux
- Source/Fuse.Drawing.Primitives/Circle.uno
- Source/Fuse.Drawing.Primitives/Wedge.uno
> Fix circle precision

- .gitignore
- Source/Fuse.WebSockets/.gitignore
Removed duplicate `.gitignore` references and added `/lib` ignore for `Fuse.WebSockets`
> Moved private .gitignores to modules. Added ignore for /lib in Fuse.WebSockets

- CHANGELOG.md
- Source/Fuse.Controls.Navigation/NavigatorSwipe.uno
- Source/Fuse.Navigation/RouterModify.uno
- Source/Fuse.Reactive.Bindings/DataBinding.uno
- Source/Fuse.Reactive.Bindings/EventBinding.uno
- Source/Fuse.Reactive.Bindings/ExpressionBinding.uno
- Source/Fuse.Reactive.Bindings/NodeExpressionBinding.uno
- Source/Fuse.Reactive.Expressions/Expression.uno
- Source/Fuse.Reactive.JavaScript/JavaScript.Dependencies.uno
- Source/Fuse.Reactive/IExpression.uno
Fixes https://github.com/fusetools/fuselibs-public/issues/213
Replaces https://github.com/fusetools/fuselibs-public/pull/310
- [-] Documentation - no new APIs
- [-] Tests - covered by existing tests
> Remove NameTable dependency from DataBinding

- CHANGELOG.md
- Source/Fuse.Animations/Attract.uno
- Source/Fuse.Animations/Tests/Attract.Test.uno
- Source/Fuse.Animations/Tests/UX/Attract.JavaScript.ux
- Source/Fuse.Common/Tests/FuseTest/TestRootNode.uno
- Source/Fuse.Reactive.JavaScript/Tests/Various.Test.uno
fixes https://github.com/fusetools/fuselibs-public/issues/456
> Make attract use InnerListener to update data bindings

- Source/Fuse.ImageTools/ImageTools.uno
Fixed small typo in the docs for ImageTools
> Fixed small typo in the docs for ImageTools

- CHANGELOG.md
- Source/Fuse.Controls.Native/Android/ImageView.uno
- Source/Fuse.Controls.Native/iOS/ImageView.uno
- Source/Fuse.Elements/Resources/MultiDensityImageSource.uno
Meaning it can be used within a NativeViewHost.
> Add native support for MultiDensityImageSource

- Tests/ManualTests/ManualTestingApp/Multitouch/Multitouch.ux.uno
fixes https://github.com/fusetools/fuselibs-public/issues/453
> fixes https://github.com/fusetools/fuselibs-public/issues/453

- Source/Fuse.PushNotifications/Android/BigPictureStyleHttp.java
- Source/Fuse.PushNotifications/Android/BundleFiles.java
- Source/Fuse.PushNotifications/Android/Impl.cpp.uxl
- Source/Fuse.PushNotifications/Android/Impl.uno
Modified version of Android implementation to add BigTextStyle and three new parameters (longTitle, longBody and notificationStyle). These parameters are sended from server side like title or body.
> Extend Fuse.PushNotifications

- Source/Fuse.PushNotifications/Fuse.PushNotifications.unoproj
Unbreaks master, which currently is broken by #461 
> Add missing files to unoproj

- CHANGELOG.md
> Changelog typo fix (introced -> introduced)

- CHANGELOG.md
- Source/Fuse.Controls.Video/Fuse.Controls.Video.unoproj
- Source/Fuse.Controls.Video/Video.ScriptClass.uno
- Source/Fuse.Controls.Video/Video.uno
- Source/Fuse.Controls.Video/VideoVisual.uno
- Tests/ManualTests/ManualTestingApp/Singles/VideoPage.js
- Tests/ManualTests/ManualTestingApp/Singles/VideoPage.ux
> Feature video scriptclass

- CHANGELOG.md
- Source/Fuse.Controls.ScrollView/ScrollViewPager.uno
- Source/Fuse.Controls.ScrollView/Tests/ScrollViewPager.Test.uno
- Source/Fuse.Controls.ScrollView/Tests/UX/ScrollViewPager.Issue560.ux
fixes https://github.com/fusetools/fuselibs-public/issues/560
> fix NullReferenceError in ScrollViewPager

- Source/Fuse.Elements/Resources/Exif/Exif.uno
Here's a couple of small cleanups on top of the Exif-support PR.
> Exif cleanups

- CHANGELOG.md
- Source/Fuse.Controls.Primitives/RangeControls/LinearRangeBehavior.uno
- Source/Fuse.Controls.Primitives/Tests/RangeControl.Test.uno
- Source/Fuse.Controls.Primitives/Tests/UX/RangeControl.LinearRangeBounds.ux
fixes https://github.com/fusetools/fuselibs-public/issues/578
> Fix bounds on LinearRangeBehavior

- Source/Fuse.Controls.Native/Android/ImageView.uno
- Source/Fuse.Controls.Native/iOS/ImageView.uno
Fixes https://github.com/fusetools/fuselibs-public/issues/584
> ImageView: return if ImageSource == null

- CHANGELOG.md
- Source/Fuse.Controls.Native/Android/Slider.uno
- Source/Fuse.Controls.Native/Interfaces.uno
- Source/Fuse.Controls.Native/iOS/Slider.uno
- Source/Fuse.Controls.Primitives/RangeControls/LinearRangeBehavior.uno
- Source/Fuse.Controls.Primitives/RangeControls/RangeControl.uno
Also fixes an update issue with progress values
> Add UserStep support to native slider

- Source/Fuse.Common/UpdateManager.uno
- Source/Fuse.Controls.Native/NativeRenderer.uno
- Source/Fuse.Controls.Panels/SingleViewHost.uno
> Misc Fuse.Controls.Native fixes

- Source/Fuse.Common/Internal/FontListParser.java
In Android O, FontVariationAxis was introduced to the fontlist format
in a way that wasn't backwards compatible with the old FontListParser.
Unfortunately, our copy has diverged quite a bit, and can't be replaced
with the new one, because the new one doesn't keep compatibility with
the old format.
So the best thing we can do for now, is to patch up the meat to match
the code better.
Sicne we don't really care about the FontVariationAxis-data yet, we
just ignore it to avoid depending on later SDK versions. We can revisit
this in the future.
This was not helped by #440, which just painted over the initial
problem instead of fixing it.
The change was adopted from the upstream, available [here](https://raw.githubusercontent.com/aosp-mirror/platform_frameworks_base/master/graphics/java/android/ …
> Fuse.Common: fix FontListParser for Android O

- Source/Fuse.Reactive.Bindings/Subscription/DataSubscription.uno
- Source/Fuse.Reactive.JavaScript/ArrayMirror.uno
- Source/Fuse.Reactive.JavaScript/FuseJS/Builtins.uno
- Source/Fuse.Reactive.JavaScript/FuseJS/TreeObservable.js
- Source/Fuse.Reactive.JavaScript/ObjectMirror.uno
- Source/Fuse.Reactive.JavaScript/Tests/Fuse.Reactive.JavaScript.Test.unoproj
- Source/Fuse.Reactive.JavaScript/Tests/TreeObservableTest.uno
- Source/Fuse.Reactive.JavaScript/Tests/UX/TreeObservable.Array.ux
- Source/Fuse.Reactive.JavaScript/Tests/UX/TreeObservable.Set.ux
- Source/Fuse.Reactive.JavaScript/Tests/UX/TreeObservable.SetCyclic.ux
- Source/Fuse.Reactive.JavaScript/Tests/UX/TreeObservable.TwoWayArray.ux
- Source/Fuse.Reactive.JavaScript/Tests/UX/TreeObservable.TwoWayObject.ux
- Source/Fuse.Reactive.JavaScript/ThreadWorker.Mirror.uno
- Source/Fuse.Reactive.JavaScript/ThreadWorker.uno
- Source/Fuse.Reactive.JavaScript/TreeObservable/TreeArray.uno
- Source/Fuse.Reactive.JavaScript/TreeObservable/TreeObject.uno
- Source/Fuse.Reactive.JavaScript/TreeObservable/TreeObservable.uno
- Source/Fuse.Reactive.JavaScript/ValueMirror.uno
~~Requires #490~~ (now merged)
> Feature TreeObservable

- CHANGELOG.md
- Source/Fuse.Desktop/DesktopApp.uno
fix https://github.com/fusetools/fuselibs-public/issues/452
> fix frameindex issue when not drawing

- Source/FuseJS/Tests/Bundle.Test.uno
> FuseJS: disable failing test

- Tests/ManualTests/ManualTestingApp/MainView.ux
- Tests/ManualTests/ManualTestingApp/UnoComponents.unoproj
- Tests/ManualTests/ManualTestingApp/Update/UpdatePage.ux
- Tests/ManualTests/ManualTestingApp/Update/UpdatePage.ux.uno
Some special tests that ensure updates in the update loop, ensures idle time, and a timing trigger.
> adding test for timing issues

- CHANGELOG.md
- Source/Fuse.Scripting.JavaScript/Observable.uno
- Source/Fuse.Scripting.JavaScript/ThreadWorker.Mirror.uno
- Source/Fuse.Scripting.JavaScript/ThreadWorker.ScriptClass.uno
- Source/Fuse.Scripting.JavaScript/ThreadWorker.uno
- Source/Fuse.Scripting/Context.uno
It wasn't needed and mixed concerns
> Remove Observable from Context & IThreadWorker

- Source/Fuse.Elements/Resources/Exif/Exif.uno
- Source/Fuse.Elements/Tests/Exif.OrientationTest.uno
Adds an internal android specific method to get ExifData directly from a Java InputStream
> Feature exif orientation from android stream

- Source/Fuse.Scripting.JavaScript/Observable.uno
In e58f7bd, I was a bit careless in one of the cases, and
accidentally kept some of the unwrapping on the UI-thread. Let's
fix that.
> Fuse.Reactive.JavaScript: fix unwrap to run on JS thread

- Source/Fuse.Common/Internal/iOSSystemFont.uno
- Source/Fuse.Controls.Panels/Backgrounds/TopFrameBackground.uno
- Source/Fuse.Controls.Panels/GraphicsView.ux.uno
- Source/Fuse.Controls.Primitives/TextControls/TextControl.GraphicsText.uno
Here's the first batch of test-fixes for mobile. This makes a bunch more tests pass on Android and iOS.
The first patch is about making the tests actually compile on iOS, due to a missing require.
> Mobile test fixes

- Tests/ManualTests/ManualTestingApp/Update/UpdatePage.ux.uno
fixes https://github.com/fusetools/ManualTestapp/issues/376
It appears there was actually at iming change on desktop, not just a mobile problem. It can't see that the action orderign is a genuine problem though, so I changed the test to be resilient against it.
> Improves timing test

- CHANGELOG.md
- Source/Fuse.Controls.Navigation/NavigationControl.BlockInput.uno
- Source/Fuse.Controls.Navigation/NavigationControl.uno
- Source/Fuse.Controls.Navigation/NavigationInternal/BlockInputWhileNavigating.ux
- Source/Fuse.Controls.Navigation/Navigator.uno
- Source/Fuse.Controls.Navigation/Tests/Navigator.Test.uno
- Source/Fuse.Controls.Navigation/Tests/UX/Navigator.HitTest.ux
Fixes https://github.com/fusetools/fuselibs-public/issues/615
> Block interaction while navigating

- Source/Fuse.Scripting.JavaScript/ThreadWorker.uno
Fixes https://github.com/fusetools/fuselibs-public/issues/643
> Remove unused methods from ThreadWorker

- CHANGELOG.md
I was careless during a rebase. Sorry about that
> remove duplicate changelog entries

- Source/Fuse.Scripting.JavaScript/Tests/JsErrorTest.uno
- Source/Fuse.Scripting.JavaScript/Tests/UX/TreeObservable.Array.ux
- Source/Fuse.Scripting.JavaScript/Tests/UX/TreeObservable.Set.ux
- Source/Fuse.Scripting.JavaScript/Tests/UX/TreeObservable.TwoWayObject.ux
These are a few incorrect assumptions I noticed while running the tests using JavaScriptCore instead of V8.
> JsErrorTest fixes

- Source/Fuse.Scripting.JavaScript/Tests/ObservableTest.uno
> Fuse.Scripting.JavaScript: ignore intermittently failing test

- Source/Fuse.Controls.Panels/Tests/GraphicsView.Test.uno
- Source/Fuse.Controls.Primitives/Tests/Text.Test.uno
- Source/Fuse.Controls.Primitives/Tests/TextControl.Test.uno
- Source/Fuse.Scripting.JavaScript/Tests/ObservableTest.uno
- Source/Fuse.Scripting.JavaScript/Tests/TreeObservableTest.uno
- Source/Fuse.Scripting.JavaScript/Tests/UXExpressionsTest.uno
- Source/Fuse.Scripting.JavaScript/Tests/Various.Test.uno
- Source/Fuse.Triggers/Tests/VariousTriggers.Test.uno
> Tests: disable tests using NativeViewHost on mobile

- Source/Fuse.Elements/Caching/ElementAtlasPool.uno
- Source/Fuse.Elements/Tests/BoxSizing.Test.uno
- Source/Fuse.Elements/Tests/ElementBatcher.Test.uno
- Source/Fuse.Elements/Tests/ExifImageTests.uno
- Source/Fuse.ImageTools/Tests/ImageTools.Test.uno
- Source/Fuse.Scripting/Tests/ScriptClass/ScriptPromise.Test.uno
- Source/Fuse.Scripting/Tests/ScriptClass/UX/ScriptPromiseTest.ux
- Source/FuseJS/Tests/Bundle.Test.uno
- Source/FuseJS/Tests/environment.js
This is a bunch of test-fixes (and some minor functionality changes to accommodate tests) that fixes all unexpected test-failures for me on iOS!
> No more unexpected ios test failures

- Tests/ManualTests/ManualTestingApp/Singles/VideoPage.ux
Fixes fusetools/ManualTestApp#375
> Fix ManualTestApp/issues/375

- Source/Fuse.Scripting.JavaScript/Tests/Various.Test.uno
- Source/Fuse.Scripting.JavaScript/ThreadWorker.uno
We don't want anyone else to touch the Context directly, so let's make it private.
> ThreadWorker private _context

- Source/Fuse.Scripting.JavaScript/ThreadWorker.uno
Here's a couple of cleanups and bugfixes made possible by @cbaggers' awesome JSContext-work!
> ThreadWorker fixes

- Source/Fuse.Controls.Primitives/Tests/Curve.Test.uno
- Source/Fuse.Elements/Caching/ElementAtlasPool.uno
- Source/Fuse.Elements/Tests/ElementBatcher.Test.uno
- Source/Fuse.ImageTools/Tests/ImageTools.Test.uno
- Source/Fuse.Scripting.JavaScript/Tests/JsErrorTest.uno
- Source/Fuse.Scripting/Tests/CommonJSmodulesTest.uno
- Source/Fuse.Scripting/Tests/Scripting.Test.uno
- Source/Fuse.Triggers/Tests/UX/Callback.ArgsContainsSender.ux
This PR leaves us with no more failing test when running on Android. Yay :)
> No more Android test failures

- Source/Fuse.Scripting.JavaScript/ThreadWorker.uno
Here's two more small fixes / cleanups for ThreadWorker. The first commit fixes a small threading-issue (unlikely to trigger in real-life, but nice to fix anyway), while the second factors out JS-specifics from the ThreadWorker main-loop.
> Thread worker cleanups2

- CHANGELOG.md
- Source/Fuse.Controls.Video/Video.ScriptClass.uno
- Source/Fuse.Controls.WebView/WebView.ScriptClass.uno
- Source/Fuse.Scripting.JavaScript/Context.uno
- Source/Fuse.Scripting.JavaScript/V8/Context.uno
- Source/Fuse.Scripting/ScriptClass.uno
- Source/Fuse.Triggers/Timeline.ScriptClass.uno
Here's some more cleanups for Fuse.Scripting etc, preparing for a revamp of the ScriptClass API.
This touches on a bit more than just Fuse.Scripting, but it's all scripting-related.
> Scripting cleanups

- Source/Fuse.Navigation/TriggerActions.uno
Fixes one half of https://www.fusetools.com/community/forums/general/error_in_the_document_article
> Typo fix to GoBack from forum

- Source/Fuse.Maps/MapView.ScriptClass.uno
- Source/Fuse.Navigation/RouterRequest.uno
- Source/Fuse.Scripting.JavaScript/FuseJS/Http.uno
- Source/Fuse.UserEvents/UserEvent.ScriptClass.uno
Here's some more cleanups in the scripting code.
> Scripting more cleanups

- Source/Fuse.Controls.Navigation/NavigationControl.Pages.uno
- Source/Fuse.Controls.Navigation/Tests/Navigator.Test.uno
- Source/Fuse.Controls.Navigation/Tests/UX/Navigator.PagesBypass.ux
fixes https://github.com/fusetools/fuselibs-public/issues/756
> Fix incorrect page navigation on load

- CHANGELOG.md
- Source/Fuse.Animations/Player.uno
- Source/Fuse.Triggers/Tests/Timeline.Test.uno
- Source/Fuse.Triggers/Tests/UX/Timeline.WrapLowDuration.ux
> fixing an issue with wrap and short duration

- CHANGELOG.md
- Source/Fuse.Reactive.Bindings/Instance.Data.uno
- Source/Fuse.Reactive.Bindings/Tests/Expression.Test.uno
- Source/Fuse.Reactive.Bindings/Tests/UX/Expression.HasValue.ux
- Source/Fuse.Reactive.Bindings/Tests/UX/Expression.IsDefined.ux
- Source/Fuse.Reactive.Bindings/With.uno
- Source/Fuse.Reactive.Expressions/LookUp.uno
- Source/Fuse.Reactive.Expressions/Subscription.uno
- Source/Fuse.Reactive/ValueObserver.uno
- Source/Fuse.Scripting.JavaScript/JavaScript.uno
fixes https://github.com/fusetools/fuselibs-public/issues/782
> Handle lost data on InnerListener/ValueObserver

- CHANGELOG.md
- Source/Fuse.Scripting.JavaScript/FuseJS/Builtins.uno
- Source/Fuse.Scripting.JavaScript/FuseJS/Timer.uno
- Source/Fuse.Scripting.JavaScript/Tests/TimerTest.uno
- Source/Fuse.Scripting.JavaScript/Tests/UX/TimerTest.ux
- Source/Fuse.Scripting.JavaScript/ThreadWorker.uno
> Fix idleness in ThreadWorker when using setTimeout( func, 0)

- CHANGELOG.md
- Source/Fuse.Reactive.Bindings/Let.uno
- Source/Fuse.Reactive.Bindings/Tests/Let.Test.uno
- Source/Fuse.Reactive.Bindings/Tests/UX/Let.Array.ux
- Source/Fuse.Reactive.Bindings/Tests/UX/Let.Explicit.ux
- Source/Fuse.Reactive.Bindings/Tests/UX/Let.ExpressionChain.ux
- Source/Fuse.Reactive.Bindings/Tests/UX/Let.Null.ux
- Source/Fuse.Reactive.Bindings/Tests/UX/Let.Observable.ux
- Source/Fuse.Reactive.Bindings/Tests/UX/Let.SimpleBind.ux
- Source/Fuse.Reactive.Bindings/Tests/UX/Let.TwoWayProperty.ux
> introduction of experimental Let feature

- Source/FuseJS/Bundle.uno
Fixing a number of cosmetic and syntax issues with FuseJS/Bundle example snippets
> cosmetic and syntax fixes to example snippets

- Source/FuseJS/Bundle.uno
fixing syntax in the example snippet
> fixing Bundle.list example

- CHANGELOG.md
- Source/Fuse.Common/Tests/FuseTest/Value.uno
- Source/Fuse.Reactive.Expressions/BinaryOperator.uno
- Source/Fuse.Reactive.Expressions/ConversionFunctions.uno
- Source/Fuse.Reactive.Expressions/IsDefined.uno
- Source/Fuse.Reactive.Expressions/MathFunctions.uno
- Source/Fuse.Reactive.Expressions/NameValuePair.uno
- Source/Fuse.Reactive.Expressions/Operators.uno
- Source/Fuse.Reactive.Expressions/QuaternaryOperator.uno
- Source/Fuse.Reactive.Expressions/StringFunctions.uno
- Source/Fuse.Reactive.Expressions/TernaryOperator.uno
- Source/Fuse.Reactive.Expressions/Tests/BinaryOperator.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/ConversionFunctions.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/MathFunctions.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/QuaternaryOperator.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/TernaryOperator.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/UX/ConversionFunctions.FailFloat.ux
- Source/Fuse.Reactive.Expressions/Tests/UX/ConversionFunctions.FailString.ux
- Source/Fuse.Reactive.Expressions/Tests/UX/ConversionFunctions.ToFloat.ux
- Source/Fuse.Reactive.Expressions/Tests/UX/ConversionFunctions.ToString.ux
- Source/Fuse.Reactive.Expressions/UnaryOperator.uno
Adds `float(expr)` and `string(expr)` to force conversion.
> Conversion functions

- CHANGELOG.md
- Source/Fuse.Controls.DatePicker/Android/DatePicker.uno
- Source/Fuse.Controls.DatePicker/DatePicker.uno
- Source/Fuse.Controls.DatePicker/iOS/DatePicker.uno
- Source/Fuse.Controls.TimePicker/Android/TimePicker.uno
- Source/Fuse.Controls.TimePicker/TimePicker.uno
- Source/Fuse.Controls.TimePicker/iOS/TimePicker.uno
This cherry-picks the commits from https://github.com/fusetools/fuselibs-public/pull/774 and https://github.com/fusetools/fuselibs-public/pull/797 onto `release-1.4`, as well as adds changelog entries for those changes.
> Picker prop fixes

- Source/Fuse.Models/Tests/Model.Test.uno
- Source/Fuse.Models/Tests/UX/NonPrototypeMethod.js
- Source/Fuse.Models/Tests/UX/NonPrototypeMethod.ux
> Fuse.Models: Add test for non-prototype methods

- Source/Fuse.Scripting.JavaScript/Fuse.Scripting.JavaScript.unoproj
This should hopefully prevent an error on TC.
> Fuse.Scripting.JavaScript: bundle all FuseJS JavaScript-sources

- CHANGELOG.md
- Source/Fuse.Scripting.JavaScript/Duktape/Context.uno
- Source/Fuse.Scripting.JavaScript/Duktape/Function.uno
- Source/Fuse.Scripting.JavaScript/Duktape/Object.uno
- Source/Fuse.Scripting.JavaScript/JavaScriptCore/Function.uno
- Source/Fuse.Scripting.JavaScript/JavaScriptCore/Object.uno
- Source/Fuse.Scripting.JavaScript/ModuleInstance.uno
- Source/Fuse.Scripting.JavaScript/V8/Function.uno
- Source/Fuse.Scripting.JavaScript/V8/Object.uno
- Source/Fuse.Scripting/Types.uno
This should unbreak the scripting-API enough to get premiumlibs building again.
I'm not aware of any other breakages, and I tried to vet the code as deeply as I could.
There's also a few other slightly related changes in here.
> Unbreak scripting api

- CHANGELOG.md
- Source/Fuse.Common/Tests/FuseTest/FuseTest.unoproj
- Source/Fuse.Common/Tests/FuseTest/ModelTestBase.uno
- Source/Fuse.Common/Tests/FuseTest/TestBase.uno
- Source/Fuse.Controls.Navigation/NavigationControl.Pages.uno
- Source/Fuse.Controls.Navigation/NavigationControl.uno
- Source/Fuse.Controls.Navigation/Tests/Fuse.Controls.Navigation.Test.unoproj
- Source/Fuse.Controls.Navigation/Tests/NavigatorModel.Test.uno
- Source/Fuse.Controls.Navigation/Tests/PageControl.Test.uno
- Source/Fuse.Controls.Navigation/Tests/UX/NavigatorModel.Nested.js
- Source/Fuse.Controls.Navigation/Tests/UX/NavigatorModel.Nested.ux
- Source/Fuse.Controls.Navigation/Tests/UX/PageControl.PageHistory.ux
- Source/Fuse.Models/Tests/Model.Test.uno
fixes https://github.com/fusetools/fuselibs-public/issues/880
Introduces a `ModelTestBase`
> Fixes rooting issue with Navigator.Pages

- .travis.yml
- Source/Fuse.Common/Internal/DesktopFonts.stuff
- Source/Fuse.Controls.Video/CIL/XamMac.stuff
- Source/Fuse.Elements/Tests/UX/ImageFill.UrlResource.ux
- Source/Fuse.Scripting.JavaScript/V8/.gitignore
- Source/Fuse.Scripting.JavaScript/V8/lib/Android.stuff
- Source/Fuse.Scripting.JavaScript/V8/lib/DotNet.stuff
- Source/Fuse.Scripting.JavaScript/V8/lib/OSX.stuff
- Source/Fuse.Scripting.JavaScript/V8/lib/Windows.stuff
- Source/Fuse.Text/.gitignore
- Source/Fuse.Text/harfbuzz/lib/Android.stuff
- Source/Fuse.Text/harfbuzz/lib/OSX.stuff
- Source/Fuse.Text/harfbuzz/lib/Windows.stuff
- Source/Fuse.Text/harfbuzz/lib/iOS.stuff
- Source/Fuse.Text/icu/iOS.stuff
- Source/Fuse.WebSockets/ios/SocketRocket/SocketRocket-iOS.stuff
Fixes issue #878.
Fixes issue #877.
Fixes issue #497.
Fixes issue #496.
Fixes issue #495.
> Move dependencies to new CDN

- CHANGELOG.md
- Source/Fuse.Controls.Navigation/NavigationControl.Pages.uno
- Source/Fuse.Controls.Navigation/NavigationControl.ScriptClass.uno
- Source/Fuse.Controls.Navigation/Tests/Navigator.Test.uno
- Source/Fuse.Controls.Navigation/Tests/UX/Navigator.PagesNavigationRequest.ux
- Source/Fuse.Navigation/Router.ScriptClass.uno
- Source/Fuse.Navigation/RouterPage.uno
- Source/Fuse.Navigation/RouterRequest.uno
fixes https://github.com/fusetools/fuselibs-public/issues/858
> `$navigationRequest` for `Navigator.Pages`

- Source/Fuse.Scripting.JavaScript/Tests/UX/FindData.ux
- Source/Fuse.Scripting.JavaScript/Tests/Various.Test.uno
hopefully fixes https://github.com/fusetools/fuselibs-public/issues/899
> Fix spurious test failure in FindData

- CHANGELOG.md
- Source/Fuse.Selection/Selection.uno
- Source/Fuse.Selection/Tests/Selection.Test.uno
- Source/Fuse.Selection/Tests/UX/Selection.EventOrder.ux
Fixes https://github.com/fusetools/fuselibs-public/issues/885
> Fixes order of emitted event in Selection

- CHANGELOG.md
- Source/Fuse.Nodes/Node.DataContext.uno
- Source/Fuse.Reactive.Bindings/Tests/UX/With.ContextChange.ux
- Source/Fuse.Reactive.Bindings/Tests/With.Test.uno
fixes https://github.com/fusetools/fuselibs-public/issues/888
> Fix an issue with a {} binding not updating

- CHANGELOG.md
- Source/Fuse.Elements/LayoutFunctions.uno
- Source/Fuse.Elements/Tests/LayoutFunctions.Test.uno
- Source/Fuse.Elements/Tests/UX/LayoutFunctions.LostData.ux
- Source/Fuse.Nodes/Visual.Layout.uno
- Source/Fuse.Nodes/Visual.uno
fixes https://github.com/fusetools/fuselibs-public/issues/747
> Adds lost data to LayoutFunctions, `x`,`y`,`width`, `height`

- CHANGELOG.md
- Source/Fuse.Reactive.Bindings/Instance.uno
- Source/Fuse.Reactive.Bindings/Instantiator.uno
- Source/Fuse.Reactive.Bindings/Tests/Each.Test.uno
- Source/Fuse.Reactive.Bindings/Tests/Instance.Test.uno
- Source/Fuse.Reactive.Bindings/Tests/UX/Each.Null.ux
- Source/Fuse.Reactive.Bindings/Tests/UX/Instance.ItemNull.ux
Simplifies `Instance` for changes in `Instantiator`
Fixes https://github.com/fusetools/fuselibs-public/issues/891
> Simplify instance and fix null context defect

- Source/Fuse.Models/FuseJS/Internal/Model.js
- Source/Fuse.Models/Tests/Model.Test.uno
- Source/Fuse.Models/Tests/UX/ThrowFromGetter.js
- Source/Fuse.Models/Tests/UX/ThrowFromGetter.ux
> Model: Don't silently ignore errors thrown in getters

- CHANGELOG.md
- Source/Fuse.Marshal/Computer.uno
- Source/Fuse.Marshal/Marshal.Compute.uno
- Source/Fuse.Scripting.JavaScript/Tests/UX/Expressions.ux
- Source/Fuse.Scripting.JavaScript/Tests/UXExpressionsTest.uno
This allows doing thing like negating boolean expressions etc, which
can be useful.
This was requested in issue #915.
> implement a basic bool-computer

- CHANGELOG.md
- Source/Fuse.Controls.Native/Interfaces.uno
- Source/Fuse.Controls.Native/iOS/ScrollView.uno
- Source/Fuse.Controls.ScrollView/ScrollView.Native.uno
- Source/Fuse.Controls.ScrollView/ScrollView.ux.uno
> ScrollView: fix native scrolling bugs

- Source/Fuse.Navigation/RouterModify.uno
> Fix broken link in RouterModify docs

- CHANGELOG.md
- Source/Fuse.Elements/LayoutFunctions.uno
- Source/Fuse.Elements/Tests/LayoutFunctions.Test.uno
- Source/Fuse.Elements/Tests/UX/LayoutFunctions.Alternates.ux
- Source/Fuse.Reactive.Expressions/Fuse.Reactive.Expressions.unoproj
- Source/Fuse.Reactive.Expressions/MathFunctions.uno
- Source/Fuse.Reactive.Expressions/Tests/UX/VectorFunctions.XYZW.ux
- Source/Fuse.Reactive.Expressions/Tests/VectorFunctions.Test.uno
- Source/Fuse.Reactive.Expressions/VarArgFunction.uno
- Source/Fuse.Reactive.Expressions/VectorFunctions.uno
Some helpful expression functions. Extracted from my partial curve drawing branch (needed for the complete feature set)
> adding x,y,z,w,atanVector functions

- Source/Fuse.Controls.Primitives/Tests/Image.Layout.Test.uno
- Source/Fuse.Controls.Primitives/Tests/Image.StretchFill.Test.uno
- Source/Fuse.Controls.Primitives/Tests/Image.StretchNone.Test.uno
- Source/Fuse.Controls.Primitives/Tests/Image.StretchUniform.Test.uno
- Source/Fuse.Controls.Primitives/Tests/Image.StretchUniformToFill.Test.uno
- Source/Fuse.Drawing.Primitives/Quad.uno
- Source/Fuse.Elements/Element.Node.uno
These using-statements are needless, so let's get rid of them.
> Remove pointless usings

- CHANGELOG/scripting_names_export.md
- Source/Fuse.Scripting.JavaScript/JavaScript.uno
- Source/Fuse.Scripting.JavaScript/ModuleInstance.uno
- Source/Fuse.Scripting.JavaScript/RootableScriptModule.uno
- Source/Fuse.Scripting.JavaScript/Tests/JavaScriptTest.uno
- Source/Fuse.Scripting.JavaScript/Tests/UX/JavaScript.ExoticNames.ux
- Source/Fuse.Scripting.JavaScript/Tests/UX/JavaScript.Names.ux
- Source/Fuse.Scripting/ScriptModule.Evaluate.uno
- Source/Fuse.Scripting/ScriptModule.Require.uno
fixes https://github.com/fusetools/fuselibs-public/issues/973
> Adds `JavaScript.Names` feature

- CHANGELOG/page_control_crash_binding.md
- Source/Fuse.Controls.Navigation/PageControl.uno
- Source/Fuse.Controls.Navigation/Tests/PageControl.Test.uno
- Source/Fuse.Controls.Navigation/Tests/UX/PageControl.ActiveStringBinding.ux
fixes https://github.com/fusetools/fuselibs-public/issues/955
> Fix Pagecontrol null crash on binding by name

- CHANGELOG/partial_curves.md
- Source/Fuse.Controls.Primitives/Shapes/Curve.uno
- Source/Fuse.Controls.Primitives/Shapes/Path.Surface.uno
- Source/Fuse.Controls.Primitives/Shapes/Path.uno
- Source/Fuse.Controls.Primitives/Shapes/PathExpression.uno
- Source/Fuse.Controls.Primitives/Shapes/SegmentedShape.uno
- Source/Fuse.Controls.Primitives/Shapes/Shape.Surface.uno
- Source/Fuse.Controls.Primitives/Tests/Path.Test.uno
- Source/Fuse.Controls.Primitives/Tests/UX/Path.MeasureMode.ux
- Source/Fuse.Controls.Primitives/Tests/UX/Path.Segment.ux
- Source/Fuse.Drawing.Surface/LineSegment.uno
- Source/Fuse.Drawing.Surface/LineSegments.uno
- Source/Fuse.Drawing.Surface/LineSplitter.uno
- Source/Fuse.Drawing.Surface/SurfaceUtil.uno
- Source/Fuse.Drawing.Surface/Tests/LineSplitter.Test.uno
- Source/Fuse.Nodes/Transform.uno
- Source/Fuse.Reactive.Expressions/ExpressionListener.uno
- Tests/ManualTests/ManualTestingApp/MainView.ux
- Tests/ManualTests/ManualTestingApp/Singles/PartialPaths.ux
Trying the new idea for CHANGELOG in a sub-directory (to avoid merge conflicts)
> Adds the partial curve drawing feature

- CHANGELOG.md
- Source/Fuse.GeoLocation/GeoLocation.uno
- Source/Fuse.Scripting/NativeEvent.uno
- Source/Fuse.Scripting/NativeProperty.uno
> Fuse.Scripting: roll back NativeProperty API change

- CHANGELOG.md
- Source/Fuse.Scripting/Context.uno
> reintroduce `Invoke(Action ..)` to Fuse.Scripting.Context

- Source/Fuse.Models/ModelJavaScript.uno
This cleans up a few parts of `ModelJavaScript.uno`, mostly just reducing noise and being less repetitive.
> Cleanup model bootstrapping

- CHANGELOG.md
- CHANGELOG/data_context_lost.md
- CHANGELOG/page_control_crash_binding.md
- CHANGELOG/partial_curves.md
- CHANGELOG/router_goback_doublepush.md
- CHANGELOG/scripting_names_export.md
- CHANGELOG/textcolor.opacity.md
> merge changelog files

- CHANGELOG/cycle.md
- Source/Fuse.Animations/Cycle.uno
- Source/Fuse.Animations/Tests/Cycle.Test.uno
- Source/Fuse.Animations/Tests/UX/Cycle.Restore.ux
Simple new feature, been requested for a while.
> adding Cycle.Restore

- CHANGELOG/instance_is_enabled_match.md
- Source/Fuse.Reactive.Bindings/Instance.uno
- Source/Fuse.Reactive.Bindings/Instantiator.uno
- Source/Fuse.Reactive.Bindings/Tests/Instance.Test.uno
- Source/Fuse.Reactive.Bindings/Tests/UX/Instance.Defaults.ux
- Source/Fuse.Reactive.Bindings/Tests/UX/Instance.IsEnabled.ux
- Source/Fuse.Reactive.Bindings/Tests/UX/Instance.Match.ux
- Source/Fuse.Triggers/WhileBool.uno
Adds several related features that will ease creating dynamic/adaptive UIs.
> `Instantiator` `IsEnabled` `Match` and `Defaults`

- CHANGELOG.md
> Add FuseJS changes to 1.7 changelog

- CHANGELOG/edgenavigator_model.md
- Source/Fuse.Controls.Navigation/CommonNavigation.uno
- Source/Fuse.Controls.Navigation/CommonNavigationPages.uno
- Source/Fuse.Controls.Navigation/EdgeNavigator.uno
- Source/Fuse.Controls.Navigation/NavigationControl.uno
- Source/Fuse.Controls.Navigation/Navigator.uno
- Source/Fuse.Controls.Navigation/PageControl.uno
- Source/Fuse.Controls.Navigation/Tests/EdgeNavigator.Test.uno
- Source/Fuse.Controls.Navigation/Tests/UX/EdgeNavigator.ModelPages.State.js
- Source/Fuse.Controls.Navigation/Tests/UX/EdgeNavigator.ModelPages.ux
- Source/Fuse.Navigation/EdgeNavigation.uno
- Source/Fuse.Reactive/ObserverMap.uno
Most code removal/additional is moving the code to common files to be shared.
> Improve state model support on EdgeNavigator

- Source/Fuse.Controls.Navigation/EdgeNavigator.uno
- Source/Fuse.Controls.Panels/GraphicsView.ux.uno
- Source/Fuse.Controls.Video/Video.uno
- Source/Fuse.Scripting/Context.uno
- Tests/ManualTests/ManualTestingApp/PointerAndMouse/PointerAndMouse.ux.uno
This reduces the compile-time warning-count a bit...
> Reduce warnings

- CHANGELOG/safe_edge_panel.md
- Source/Fuse.Common/Tests/FuseTest/TestRootNode.uno
- Source/Fuse.Controls.Panels/ClientPanel.uno
- Source/Fuse.Controls.Panels/Docs/SafeLayout.md
- Source/Fuse.Controls.Panels/SafeEdgePanel.uno
- Source/Fuse.Controls.Panels/Tests/SafeEdgePanel.Test.uno
- Source/Fuse.Controls.Panels/Tests/UX/SafeEdgePanel.Basic.ux
- Source/Fuse.Controls.Panels/Window.uno
- Source/Fuse.Platform/Fuse.Platform.unoproj
- Source/Fuse.Platform/SystemUI.uno
> Adding SafeEdgePanel for iPhone X compatible design

- CHANGELOG/keyframe.md
- Source/Fuse.Animations/Keyframe.uno
- Source/Fuse.Animations/Tests/Keyframe.Test.uno
- Source/Fuse.Animations/Tests/UX/Keyframe.Expression.ux
- Source/Fuse.Controls.Primitives/Shapes/Curve.uno
Basic fix for https://github.com/fusetools/fuselibs-public/issues/1037
> Improve Keyframe, add expresison support, Tangent

- CHANGELOG/android_stroke.md
- Source/Fuse.Drawing.Surface/Android/Surface.uno
- Tests/ManualTests/ManualTestingApp/Surface/Components/RootPanel.ux
- Tests/ManualTests/ManualTestingApp/Surface/Singles/CapJoin.ux
fixes https://github.com/fusetools/fuselibs-public/issues/1040
> Fixed Android `Stroke` `Cap` and `Join`

- CHANGELOG/swipe_threshold.md
- Source/Fuse.Gestures/Internal/Swiper.uno
- Source/Fuse.Gestures/Swipe.uno
- Source/Fuse.Gestures/Tests/Swipe.Test.uno
- Source/Fuse.Gestures/Tests/UX/Swipe.Threshold.ux
fixes https://github.com/fusetools/fuselibs-public/issues/1027
> Adds `SwipeGesture.Threshold` and fixes default

- CHANGELOG/grid_layout_metric_default.md
- Source/Fuse.Controls.Panels/Layouts/GridLayout.uno
- Source/Fuse.Controls.Panels/Tests/Grid.Test.uno
- Source/Fuse.Controls.Panels/Tests/UX/Grid.Issue1019.ux
fixes https://github.com/fusetools/fuselibs-public/issues/1019
> Fixes a grid layout issue

- CHANGELOG.md
- Source/Fuse.Controls.Navigation/Tests/Router.Test.uno
- Source/Fuse.Controls.Navigation/Tests/UX/Router.Issue1066.ux
- Source/Fuse.Navigation/Router.uno
fixes https://github.com/fusetools/fuselibs-public/issues/1066
> Fixes Router.GoUp/GoBack crash

- CHANGELOG/color_expressions.md
- Source/Fuse.Marshal/Marshal.Cast.uno
- Source/Fuse.Reactive.Expressions/Color.uno
- Source/Fuse.Reactive.Expressions/Tests/Color.Test.uno
- Source/Fuse.Reactive.Expressions/Tests/UX/Color.Basic.ux
fixes https://github.com/fusetools/fuselibs-public/issues/1065
> adds color expressions

- CHANGELOG.md
- Source/Fuse.Scripting/Context.uno
- Source/Fuse.Scripting/NativeEvent.uno
Seems release-1.6 wasn't merged to master after release. This adds back the fixes needed.
Noticed by @cbaggers!
> Merge missing 1.6 changes

- CHANGELOG/edgenavigator_navigatetoggle.md
- Source/Fuse.Controls.Navigation/Tests/EdgeNavigator.Test.uno
- Source/Fuse.Controls.Navigation/Tests/UX/EdgeNavigator.NavigateToggle.ux
- Source/Fuse.Navigation/TriggerActions.uno
fixes https://github.com/fusetools/fuselibs-public/issues/226
> Fixes how ToggleNavigate locates the navigation

- Source/Fuse.Controls.Native/iOS/Focus.uno
> Remove unnecessary dictionary lookup

- Source/Fuse.Drawing.Surface/LineParser.uno
- Source/Fuse.Drawing.Surface/Tests/LineMetrics.Test.uno
fixes https://github.com/fusetools/fuselibs-public/issues/1028
> Error message for #1028

- CHANGELOG.md
- Source/Fuse.Platform/Android/SystemUI.uno
https://github.com/fusetools/fuselibs-public/issues/1093
~
> workaround for Android warning

- CHANGELOG.md
- Source/Fuse.Drawing.Surface/DotNetSurface.uno
fixes https://github.com/fusetools/fuselibs-public/issues/1078
> Fixes DotNet unclosed path drawing issue

- CHANGELOG/android_layout_zero.md
- Source/Fuse.Android/AndroidApp.uno
- Source/Fuse.Controls.Native/Fuse.Controls.Native.unoproj
- Source/Fuse.Controls.Native/NativeRootViewport.uno
- Source/Fuse.Nodes/RootViewport.uno
- Source/Fuse.Platform/Android/SystemUI.uno
- Source/Fuse.Platform/Fuse.Platform.unoproj
- Tests/ManualTests/ManualTestingApp/InterceptPanel.uno
- Tests/ManualTests/ManualTestingApp/TestApp.ux
- Tests/ManualTests/ManualTestingApp/UnoComponents.unoproj
fixes https://github.com/fusetools/fuselibs-public/issues/1096
> Fixes an empty layout on Android during startup

- Tests/ManualTests/ManualTestingApp/DeviceInfo/DeviceInfo.ux
- Tests/ManualTests/ManualTestingApp/NativeManualTestingApp.unoproj
- Tests/ManualTests/ManualTestingApp/NativeTestApp.ux
It does run, and display stuff. The first major blocker is https://github.com/fusetools/fuselibs-public/issues/1085
I thought merging the basic test is a good place to start.
> Adds a native project for the ManualTestApp

- Source/Fuse.Common/Tests/Fuse.Common.Test/ObjectList.Test.uno
- Source/Fuse.Common/Tests/FuseTest/TestRootNode.uno
- Source/Fuse.Controls.Panels/GraphicsView.ux.uno
- Source/Fuse.Controls.Primitives/TextControls/FallbackTextRenderer/WrappedLine.uno
- Source/Fuse.Controls.Primitives/TextControls/FuseTextEdit.uno
- Source/Fuse.Controls.Primitives/TextControls/FuseTextRenderer/FuseTextRenderer.uno
- Source/Fuse.Controls.Video/Video.uno
- Source/Fuse.Drawing.Surface/DotNetSurface.uno
- Source/Fuse.Elements/Internal/SizingContainer.uno
- Source/Fuse.FileSystem/Tests/FileSystemOperations.Test.uno
- Source/Fuse.Gestures/RotateGesture.uno
- Source/Fuse.Nodes/Visual.Layout.uno
- Source/Fuse.Reactive.Bindings/Tests/PatchList.Test.uno
- Source/Fuse.Reactive.Expressions/MathFunctions.uno
- Source/Fuse.Reactive.Expressions/Tests/MathFunctions.Test.uno
- Source/Fuse.Text/Measure.uno
- Source/Fuse.Text/Shape.uno
This is just a warning clean-up, shouldn't have any behavioral changes.
> Fixup warnings

- CONTRIBUTING.md
- Documentation/CodingStyle.md
This is based on a code-review in the uno-repo (fusetools/uno#1638
for those who have access), but I thought I'd make sure we update
fuselibs as well.
> Improve language in docs

- Source/Fuse.Controls.ScrollView/Tests/ScrollViewPager.Test.uno
Disable test due to fuselibs-public#1125.
> ignore failing test

- CHANGELOG/router_goback.md
- Source/Fuse.Navigation/Router.uno
> Fixes a router back button issue

- CHANGELOG/element_layoutmaster.md
- Source/Fuse.Nodes/Tests/UX/Visual.LayoutRoleChange.ux
- Source/Fuse.Nodes/Tests/Visual.Test.uno
- Source/Fuse.Nodes/Visual.Layout.uno
fixes https://github.com/fusetools/fuselibs-public/issues/713
> Fixes redundant InvalidateLayout in LayoutRole change

- Source/Fuse.Platform/Fuse.Platform.unoproj
Fixes https://fusecommunity.slack.com/archives/C0831U16J/p1521728797000358?thread_ts=1521728750.000734&cid=C0831U16J
> Make Fuse.Platform internals visible to Fuse.Views

- CHANGELOG/wraplayout_invalidate.md
- Source/Fuse.Controls.Panels/Layouts/WrapLayout.uno
- Source/Fuse.Controls.Panels/Tests/UX/UX.WrapPanel.Invalidate.ux
- Source/Fuse.Controls.Panels/Tests/WrapPanel.Test.uno
fixes https://github.com/fusetools/fuselibs-public/issues/1110
> Fixes WrapLayout invalidation defect

- Source/Fuse.Marshal/Tests/Marshal.Test.uno
fixes https://github.com/fusetools/fuselibs-public/issues/1116
> Fix some warnings

- CHANGELOG/mapview_zoom_factor.md
- Source/Fuse.Maps/iOS/MapViewDelegate.m
I changed the way the zoom factor is calculated in order to be more accurate.
I also bring smooth transition while a user is moving the map from a point to another point.
> Fix the zoom issue and bring smooth transition

- CHANGELOG/layout_relative_size.md
- Source/Fuse.Controls.Panels/Tests/DockPanel.Test.uno
- Source/Fuse.Controls.Panels/Tests/UX/DockPanel.RelativeSize.ux
- Source/Fuse.Elements/Element.Layout.uno
fixes https://github.com/fusetools/fuselibs-public/issues/833
> Fixes DockPanel/ScrollView RelativeSize issue

- Source/Fuse.PushNotifications/Docs/AndroidSpecifics.md
This link has changed, so let's update it!
> Fuse.PushNotifications: update link to forum-post

- Source/Fuse.Charting/DataSeries.uno
- Source/Fuse.Charting/DataUtils.uno
- Source/Fuse.Charting/Plot.ScriptClass.uno
- Source/Fuse.Controls.CameraView/Photo.uno
- Source/Fuse.Controls.CameraView/Recording.uno
- Source/Fuse.UXKits.Alive/UXFunctions/ColorFunctions.uno
This eliminates a bunch of deprecation warnings in code imported from premiumlibs.
> Remove warnings

- .teamcity_set_versions.sh
- README.md
- Stuff/Devtools.stuff
- pack.sh
These details were just around to please team-city. There's no
reason to do any of this any more. So let's trim a bit of fat!
> remove all team-city related stuff

- Source/Fuse.CameraRoll/iOS/iOSCameraRoll.uno
Fixes #983. Before accessing the image picker I checked if `PHAuthorizationStatus` was determined. If not then get permissions, if  `PHAuthorizationStatusAuthorized` go for it, else (denied or restricted) return `onFail`.
More info on [PHAuthorizationStatus](https://developer.apple.com/documentation/photokit/phauthorizationstatus?language=objc)
Later, I want to implement `cameraRoll.accessPhotos()` to get user's permissions on demand and if it's false then redirect them to phone settings.
> fix iOS Camera roll permission issue

- Source/Fuse.Controls.CameraView/Android/Camera.uno
- Source/Fuse.Controls.CameraView/Android/CameraImpl.java
- Source/Fuse.Controls.CameraView/Android/CameraView.uno
- Source/Fuse.Controls.CameraView/CameraViewBase.ScriptClass.uno
- Source/Fuse.Controls.CameraView/CameraViewBase.uno
- Source/Fuse.Controls.CameraView/Example/CameraViewExample/.gitignore
- Source/Fuse.Controls.CameraView/Example/CameraViewExample/.unoconfig_example
- Source/Fuse.Controls.CameraView/Example/CameraViewExample/MainView.ux
- Source/Fuse.Controls.CameraView/Nothing.uno
- Source/Fuse.Controls.CameraView/iOS/CameraView.uno
- Source/Fuse.Controls.CameraView/iOS/CameraViewImpl.h
- Source/Fuse.Controls.CameraView/iOS/CameraViewImpl.mm
- added setCameraFocusPoint
- added to example usage
:cake:
> Added "Tap to Focus" to CameraView for iOS and Android

- .vscode/settings.json
This adds workspace settings for Visual Studio Code.
> Add vscode workspace settings

- .appveyor.yml
This makes build artifacts available for download from AppVeyor.
> Publish build artifacts

- Source/Fuse.Controls.CameraView/Nothing.uno
- Source/Fuse.Elements/Triggers/LayoutAnimation.uno
- Source/Fuse.FileSystem/Nothing.uno
- Source/Fuse.Navigation/VisualNavigation.uno
- Source/Fuse.Physics/World.uno
- Source/Fuse.Text/Renderer.uno
This fixes visibility problems detected by https://github.com/fuse-open/uno/pull/140.
> Fix visibility problems

- Source/Fuse.Camera/Android/AndroidCamera.uno
- Source/Fuse.Camera/Android/AndroidCamera.uxl
- Source/Fuse.Camera/Android/CameraFileProvider.java
- Source/Fuse.Camera/Android/android_camera_paths.xml
- Source/Fuse.ImageTools/Android/Image.java
- Source/Fuse.ImageTools/Android/ImageStorageTools.java
- updated with new file permission requirements for newer androids.
- catered for out of memory error
- post photo capture - rotation fix: if out of memory, won't crash but will downsize image to fit memory before adjusting rotation
- fixed android app name
https://medium.com/@andrewq/hello-world-eaa996c594b7
> Camera - Android Updates

- Source/Fuse.Controls.CameraView/VideoTools.uno
- Source/Fuse.FileSystem/FileSystemModule.uno
- Source/Fuse.Scripting.JavaScript/FuseJS/Timer.uno
- Source/Fuse.Storage/StorageModule.uno
This fixes TypeScript compatibilty issues and small clean-ups that were discovered when making #1261.
> FuseJS TypeScript compatibility

- .appveyor.yml
This tests that we can successfully build for Android and Windows/native, and would've caught recent regressions in Fuselibs before ending up on `master`.
> Add more build testing

- Source/Fuse.Scripting.JavaScript/Duktape/duktape.uno
- Source/Fuse.Scripting.JavaScript/Duktape/duktape.uxl
- Source/Fuse.Scripting.JavaScript/JavaScriptCore/3rdparty/JavaScriptCore.cpp.uxl
- Source/Fuse.Scripting.JavaScript/JavaScriptCore/Context.uno
Some clean-ups for the Fuse.Scripting.JavaScript package.
> Fuse.Scripting.JavaScript clean-ups

- Source/Fuse.Controls.Native/Android/Java/FuseScrollView.java
Fix for when content inside native android scrollview can't accept clicked / tapped gesture. this resolve https://github.com/fuse-open/fuselibs/issues/1085
> fix android native scrollview clicked gesture

- Source/Fuse.Scripting.JavaScript/JavaScriptCore/Context.uno
- Source/Fuse.Scripting.JavaScript/JavaScriptCore/JSTypedArrayInclude.h
- Source/Fuse.Scripting.JavaScript/JavaScriptEngine.cpp.uxl
- Source/Fuse.Text/Implementation/Harfbuzz.uno
- Source/Fuse.Text/Implementation/ICU.uno
- Source/Fuse.Text/Implementation/UBidi.uno
- Source/Fuse.Text/Implementation/UBrk.uno
With these changes I'm now able to build and run Fuse apps on Linux.
> Linux support

- index.d.ts
- tools/generator-typescript/Program.cs
This adds TypeScript Definitions for new FuseJS/Sensor module.
> TypeScript: add FuseJS/Sensor module

- Source/Fuse.Controls.Video/CIL/XamMac.stuff
- Source/Fuse.Elements/Internal/ImageContainer.uno
Following up with more minor improvements..
> Various patches 2

- .travis.yml
- Source/AllTests.unoproj
Some build adjustments due to changes in the new Uno version.
> Prepare for new Uno

- package.json
If we're lucky, this might help with instability on AppVeyor.
It worked on the first try when running on my personal AppVeyor at least.
> Use --run-local when running tests

- Source/Fuse.Launcher.InterApp/InterApp/InterAppTrigger.uno
- Source/Fuse.Launcher.InterApp/InterApp/JS.uno
Apple: https://developer.apple.com/ios/universal-links
Android: https://developer.android.com/training/app-links
> InterApp - Added docs for Universal and App Links support

- Source/Fuse.Maps/Android/MapView.uno
> Android Maps fix

- package-lock.json
- package.json
> upgrade Uno

- Source/Fuse.iOS/iOSInterop.uno
Fixed threading issue for the iOS url launcher
> Fixed launcher threading - Fuse.iOS - OpenURL

- Source/Fuse.Common/Docs/Names.md
- Source/Fuse.Triggers/Actions/Toggle.uno
> fix typos in documentation

- CHANGELOG.md
- Source/FuseJS/Environment.uno
add a property to get current locale information
> Get current locale

- Source/Fuse.PushNotifications/iOS/Impl.uno
- updated check to include current user setting in iOS 13
> iOS Push Notifications - IsRegisteredForRemoteNotifications Update

- Source/Fuse.Gestures/Pressed.uno
For data scrolling, sliders, numeric dials, or anything with a range of values there is a common gesture interface of clicking and holding a button. So long as the button is held the value will continue to change. 
This PR implements this feature issue : https://github.com/fuse-open/fuselibs/issues/283
> HoldPress Trigger

- Source/Fuse.Android/AndroidInterop.uno
- Source/Fuse.Launcher.InterApp/InterApp/InterAppLauncher.uno
- Source/Fuse.Launcher.InterApp/InterApp/InterAppTrigger.uno
- Source/Fuse.Launcher.InterApp/InterApp/JS.uno
- added support for launching another app in android via its app package name, iOS still uses custom schemes
> InterApp - Launch App

- Source/Fuse.Triggers/Trigger.uno
Added graceful fail to trigger when its not rooted else it crashes the app with the exception.
> Graceful trigger fail

- Source/Fuse.Camera/Android/AndroidCamera.uno
- Source/Fuse.Camera/Android/CameraFileProvider.java
- Source/Fuse.CameraRoll/Android/AndroidCameraRoll.uno
- Source/Fuse.Controls.Native/Android/TextEdit.uno
- Source/Fuse.GeoLocation/Android/AndroidLocationProvider.uno
- Source/Fuse.PushNotifications/Android/BigPictureStyleHttp.java
- Source/Fuse.PushNotifications/Android/Impl.uno
- Source/Fuse.Share/android/AndroidShareImpl.uno
- Source/Fuse.Share/android/ShareFileProvider.java
- package-lock.json
- package.json
Migrated support libraries to AndroidX
https://developer.android.com/jetpack/androidx/migrate
Requires this PR first: https://github.com/fuse-open/uno/pull/254
> AndroidX Support - Requires corresponding Uno PR

- Source/Fuse.Controls.CameraView/Android/NativePhoto.uno
> Minor CameraView fix

- CHANGELOG.md
- Source/Fuse.Reactive.Expressions/StringFunctions.uno
Added more string functions :
- `trim` function
- `indexOf` function
- `substring` function
- `replace` function
- `insert` function
- `split` function
- `startsWith` function
- `endsWith` function
> String function expressions

- Source/Fuse.Controls.Native/ImageLoader.uno
This is a fix on iOS in `NativeViewHost` environment, the image loaded from Url by the `Image` component is done in the UI Thread
> ImageLoader run on background thread on iOS

- Source/Fuse.GeoLocation/Android/BackgroundService.java
> Android - Geolocation -Minor fix

- Source/Fuse.GeoLocation/Android/BackgroundService.java
> Removed the line that GitHub added

- Source/Fuse.Vibration/Vibration.uno
Add feedback vibration on Android, now we have feature parity with iOS.
> Feature : feedback vibration on android

- Source/Fuse.Controls.Native/Android/TextView.uno
- Source/Fuse.Controls.Native/iOS/TextView.uno
> Implement TextTruncation on NativeViewHost

- Source/Fuse.Controls.Native/iOS/PointerCaptureAdapter.uno
> Compatibility with latest Xcode and iOS13.4 later

- Source/Fuse.Controls.Native/Android/TextView.uno
- Source/Fuse.Controls.Native/iOS/TextView.uno
- Source/Fuse.Controls.Primitives/TextControls/TextControl.Forwarding.uno
this is a regression fix for the feature introduced in #1364 
test case:
```
<App>
<ClientPanel Color="White">
<ScrollView>
<StackPanel ItemSpacing="10">
<Text
Value="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." />
<Text
Value="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud …
```
> Fix text-wrapping in NativeViewHost

- Source/Fuse.Auth/Biometric.uno
- Source/Fuse.Auth/BiometricModule.uno
This adds javascript functionality to access the biometric sensor.
```
<JavaScript>
var Auth = require('FuseJS/Biometric');
var authenticate = function(e) {
if (Auth.isBiometricSupported()) {
Auth.authenticate("We need your biometric data to continue").then(function(result) {
if (result.status) {
// auth success
} else {
console.log(result.message);
}
});
}
}
authenticate
};
</JavaScript>
<Panel>
<Button Text="Sign In" Alignment="Center">
<Clicked Handler="{authenticate}" />
</Button>
</Panel>
```
> Javascript Biometric Module

- CHANGELOG.md
- Source/Fuse.Maps/Android/ForeignHelpers.uno
- Source/Fuse.Maps/Android/FuseMap.java
- Source/Fuse.Maps/Android/MapView.uno
- Source/Fuse.Maps/MapMarker.uno
- Source/Fuse.Maps/MapOverlay.uno
- Source/Fuse.Maps/MapView.ScriptClass.uno
- Source/Fuse.Maps/MapView.uno
- Source/Fuse.Maps/MarkerIconCache.uno
- Source/Fuse.Maps/iOS/MapView.uno
- Source/Fuse.Maps/iOS/MapViewController.m
- Source/Fuse.Maps/iOS/MapViewDelegate.h
- Source/Fuse.Maps/iOS/MapViewDelegate.m
Added two scriptclass functions, `snapshot` for taking an image of the current MapView display and `showAllMarkers` to zoom MapView to the particular position where all of the markers is visible on the MapView
**Examples:**
```
<App>
<ClientPanel>
<JavaScript>
var Observable = require('FuseJS/Observable')
var snapshotImage = new Observable()
var Map = map;
snapshotImage,
showAllMarkers: function(args) {
Map.showAllMarkers();
},
takeSnapshot: function(args) {
Map.snapshot().then(function (path) {
snapshotImage.value = path;
})
}
};
</JavaScript>
<DockLayout />
<NativeViewHost Dock="Top" Height="250">
<MapView ux:Name="map" Zoom="14" Latitude="-6.914742" Longitude="107.609820">
<MapMarker Latitude="-6.914742" Longitude="107.609820" />
<MapMarker Latitude="-6.915850" …
```
> MapView shapshot and show all markers

- Source/Fuse.Maps/Android/ForeignHelpers.uno
- Source/Fuse.Maps/Android/FuseMap.java
- Source/Fuse.Maps/Android/MapView.uno
- Source/Fuse.Maps/MapOverlay.uno
- Source/Fuse.Maps/MapView.uno
- Source/Fuse.Maps/iOS/MapView.uno
- Source/Fuse.Maps/iOS/MapViewDelegate.h
- Source/Fuse.Maps/iOS/MapViewDelegate.m
Added support for clicked/tapped event on `MapOverlay`
**Examples:**
```
<App>
<ClientPanel>
<JavaScript>
module.exports.overlayTapped = function(args) {
console.log("overlay tapped");
}
</JavaScript>
<NativeViewHost Dock="Top" Height="250">
<MapView ux:Name="map" Zoom="14" Latitude="-6.914742" Longitude="107.609820">				
<MapOverlay Radius="60" Type="Circle" FillColor="Red" Tapped="{overlayTapped}"
CenterLatitude="-6.914742" CenterLongitude="107.609820" />
</MapView>
</NativeViewHost>
</ClientPanel>
</App>
```
> implement click event on MapOverlay

- CHANGELOG.md
- Source/Fuse.Controls.Native/Android/ImageView.uno
- Source/Fuse.Controls.Native/Interfaces.uno
- Source/Fuse.Controls.Native/iOS/ImageView.uno
- Source/Fuse.Controls.Primitives/Image.ScriptClass.uno
- Source/Fuse.Controls.Primitives/Image.Visual.uno
- Source/Fuse.Controls.Primitives/Image.uno
- Source/Fuse.Controls.Primitives/Triggers/Actions/LoadImage.uno
- Source/Fuse.Elements/Drawing/ImageFill.uno
- Source/Fuse.Elements/Fuse.Elements.unoproj
- Source/Fuse.Elements/Resources/FileImageSource.uno
- Source/Fuse.Elements/Resources/HttpImageSource.uno
- Source/Fuse.Elements/Resources/ImageBackgroundLoad.uno
- Source/Fuse.Elements/Resources/ImageSource.uno
- Source/Fuse.Elements/Resources/LoadingImageSource.uno
- Source/Fuse.Elements/Resources/ProxyImageSource.uno
- Lazy-load on `Image` component and `ImageFill`. Introduce the `AutoLoad` bool property to control when we fetch the image data. The default value is `true` which means it automatically load the image data and display it whenever it rooted. Set it to `false` to make it lazy-load and using the new `LoadImage` trigger action to actually load the image. You can also change the value to `true` to load the image
- Added `LoadImage` trigger action to load image data for `Image` or `ImageFill`
- Added `TargetSize` property on `HttpImageSource` and `FileImageSource` to resize the image resolution before display. Works on iOS and Android only
```
<App>
<ClientPanel Background="#eee">		
<ScrollView AllowedScrollDirections="Vertical" LayoutMode="PreserveVisual">
<StackPanel Padding="10">
<Panel …
```
> Image enhancements

- Source/Fuse.Reactive.Expressions/Color.uno
Added support for defining color in HSV, using a function expression
Example :
```
<App>
<Rectangle ux:Class="ColorSwatch" MinWidth="200" MinHeight="200" CornerRadius="10">
<float4 ux:Property="Value" />
<Rectangle ux:Class="ColorBox" HitTestMode="LocalBounds">
<Selectable Value="{Property this.Color}" />
<WhileSelected>
<Change this.StrokeColor="White" />
<Change this.StrokeWidth="2" />
<BringToFront />
</WhileSelected>
<Tapped>
<ToggleSelection />
<DebugAction Message="{Property this.Color}" />
</Tapped>
</Rectangle>
<Selection MaxCount="1" MinCount="1" Value="{Property this.Value}" />
<GridLayout RowCount="10" ColumnCount="12" />
<ColorBox Color="hsvColor(0,0,1)" />
<ColorBox Color="hsvColor(0,0,0.921569)" />
<ColorBox Color="hsvColor(0,0,0.839216)" />
<ColorBox …
```
> add hsvColor function

- Source/Fuse.Marshal/Marshal.Cast.uno
Enhancement on `Fuse.Marshal`. Enable to cast from string formatted float4 to float4, now we can convert float4 to string and vice versa ex: "1,1,1,1" to float4(1,1,1,1). This is useful for example if we try to pass the `Color` property value of a `<Rectangle />` to `<Selectable />`. because Selection API (`Fuse.Selection`) only works with a `string` value.
Example:
```
<App>
<Rectangle ux:Class="ColorSwatch" MinWidth="200" MinHeight="200">
<string ux:Property="Value" />
<Rectangle ux:Class="ColorBox" HitTestMode="LocalBounds">
<Selectable Value="{Property this.Color}" />
<WhileSelected>
<Change this.StrokeColor="White" />
<Change this.StrokeWidth="2" />
<BringToFront />
</WhileSelected>
<Tapped>
<ToggleSelection />
<DebugAction Message="{Property this.Color}" />
</Tapped>
</Rectangle> …
```
> Enable cast from string to float4

- Source/Fuse.Controls.Primitives/Behaviors/Glass.uno
We have supported for rendering a glass effect by #1381. But it only works best with `Panel`. Now with this PR, we can apply the `Glass` effect to a `Rectangle` that have a `CornerRadius` or with a `Circle`
```
<Panel>
<Rectangle ux:Name="re" CornerRadius="40" Width="150" Height="70" Alignment="Center">
<Text Value="This is a text" Alignment="Center" Color="White" />
<Glass Background="image" Radius="20" />
<DropShadow />
<Clicked>
<Move Target="re" X="90" Duration="0.5" />
<Move Target="re" X="-180" Delay="0.5" Duration="1" />
</Clicked>
</Rectangle>
<Image ux:Name="image" Alignment="Center" Margin="20" Background="Purple" Url="https://image.freepik.com/free-vector/colorful-palm-silhouettes-background_23-2148541792.jpg" />
</Panel>
```
> Glass effect enhancement

- Source/Fuse.ImageTools/Android/Image.java
- Source/Fuse.ImageTools/iOS/ImageHelper.m
transparency support for images from base64
> transparency support for images from base64

- Source/Fuse.Controls.WebView/Android/FuseWebChromeClient.java
This makes it possible to go fullscreen on YouTube videos, for example.
> WebView (Android): support fullscreen mode

- Source/Fuse.Controls.WebView/Android/WebViewForeign.uno
- Source/Fuse.Controls.WebView/Docs/Guide.md
- Source/Fuse.Controls.WebView/WebView.uno
https-links are more likely to just work out of the box.
Also fixing minor indentation issues in related docs and code.
> WebView: use https in examples

- Source/Fuse.Controls.WebView/Android/FuseWebChromeClient.java
This makes it possible to upload files via WebView on Android.
> WebView (Android): open file picker for file inputs

- Source/Fuse.Storage/StorageModule.uno
This should fix the markup issue in the docs. The docs for site need to be re-generated and published
> added several newlines

- Source/Fuse.Controls.Panels/CollectionPanel.uno
- Source/Fuse.Controls.ScrollView/ScrollViewPager.uno
- Source/Fuse.Drawing.Surface/CoreGraphics/CoreGraphicsSurface.uno
`CollectionPanel` is a new and straightway to create a `Panel` with `ColumnLayout`. All public property of the `ColumnLayout` now accessible on the new `CollectionPanel`
```
<CollectionPanel GroupCount="3">
<Each Count="12">
<Circle Margin="5" Color="Blue" />
</Each>
</CollectionPanel>
```
This PR also enhance the `ScrollViewPager` by creating `Step` property to make it work with the `CollectionPanel` inside `ScrollView`
```
<ScrollView LayoutMode="PreserveVisual">
<CollectionPanel GroupCount="3">
<Each Items="{items}" Reuse="Frame" ux:Name="theEach">
<Panel Color="#AAA">
<Text Value="{title}"/>
</Panel>
</Each>
</CollectionPanel>
<ScrollViewPager Each="theEach" ReachedEnd="{loadMore}" Step="3" />
</ScrollView> 
```
and also this PR fixed small memory leak on iOS on `CoreGraphicsSurface` …
> Introduce new type of Panel: CollectionPanel

- README.md
fix a broken link of VSRedist 2010 on README
> fix broken link of VSRedist 2010

- tools/doc-export/doc-export.unoproj
> doc-export: Add Fuse.Alerts

- Source/Fuse.Scripting/NativePromise.uno
This makes it possible to receive the Context object when implementing native promises, e.g. to call JavaScript functions and other operations available with Context.
> Fuse.Scripting: add Context parameter to NativePromise delegates

- Source/Fuse.Launcher.Phone/Phone/JS.uno
- Source/Fuse.Launcher.Phone/Phone/PhoneLauncher.uno
- Source/Fuse.Launcher.Phone/Phone/PhoneTrigger.uno
- Source/Fuse.Launcher.Phone/Phone/PhoneUriHelper.uno
- Source/Fuse.Launcher/Launcher.uno
- Source/Fuse.Launcher/Tests/PhoneUriHelper.Test.uno
* Add Launcher.LaunchSms(string phoneNumber, string body) method.
* Add sms(phoneNumber: string, body?: string) method to FuseJS/Phone module.
* Add Sms trigger action for UX.
> Fuse.Launcher.Phone: implement SMS launcher

- .appveyor.yml
- package-lock.json
Use nodejs v16 on AppVeyor and upgrade package-lock.json to version 2.
> use nodejs v16

- Source/Fuse.LocalNotifications/Android/Impl.uno
- Source/Fuse.LocalNotifications/Common.uno
- Source/Fuse.LocalNotifications/iOS/Impl.uno
fix compatibility with the latest OS and indentation.
> Local Notification

- Source/Fuse.Controls.Primitives/Tests/Image.Test.uno
- Source/Fuse.Controls.Primitives/Tests/TextControl.Test.uno
- Source/Fuse.Elements/Tests/Caching.Test.uno
- Source/Fuse.Elements/Tests/ElementBatcher.Test.uno
- Source/Fuse.Elements/Tests/Exif.OrientationTest.uno
- Source/Fuse.Elements/Tests/ExifImageTests.uno
- Source/Fuse.Elements/Tests/ImageFill.Test.uno
- Source/Fuse.Elements/Tests/Rendering.Test.uno
- Source/FuseJS/Tests/Base64.Test.uno
- Source/FuseJS/Tests/Environment.Test.uno
These tests hang or fail when run on macOS (dotnet).
> Tests: ignore tests failing on macOS (beta-3.0)

- Source/Fuse.Android.Permissions/AndroidPermissionsInternal.uno
- Source/Fuse.Android.Permissions/AndroidPermissionsInternal.uxl
- Source/Fuse.Android.Permissions/Permissions.uno
- Source/Fuse.Android.Permissions/Permissions.uxl
- Source/Fuse.Camera/Android/AndroidCamera.uno
- Source/Fuse.Camera/Fuse.Camera.unoproj
This makes the Camera and CameraRoll modules work on Android 13.
Closes #1481
> Fuse.Camera: update permissions for Android 13

- .appveyor.yml
- package-lock.json
- package.json
- tools/timeout.js
Sometimes we see something hanging when running tests on CI, and this
commit makes the build terminate faster than waiting 60 mintues for
AppVeyor to time out.
> kill tests after 15 minutes (beta-3.0)

- Source/Fuse.Common/Json.uno
- Source/Fuse.Common/SystemFont.uno
- Source/Fuse.Controls.Panels/GraphicsView.ux.uno
- Source/Fuse.Nodes/VisualBounds.uno
- Source/Fuse.Scripting.JavaScript/Duktape/Function.uno
- Source/Fuse.Scripting.JavaScript/Duktape/Object.uno
- Source/Fuse.Scripting.JavaScript/JavaScriptCore/Function.uno
- Source/Fuse.Scripting.JavaScript/JavaScriptCore/Object.uno
- Source/Fuse.Scripting.JavaScript/V8/Function.uno
- Source/Fuse.Scripting.JavaScript/V8/Object.uno
- Source/Fuse.Scripting/Context.uno
- Source/Fuse.Scripting/ModuleResult.uno
- Source/Fuse.Scripting/NativeEvent.uno
- Source/Fuse.Scripting/Types.uno
This removes a set of methods and properties that have been marked as obsolete since version 1.0 or longer.
> remove obsolete methods and properties (beta-3.0)

- Source/Fuse.Android.Permissions/Permissions.java
- Source/Fuse.ImageTools/Android/Commands.uno
- Source/Fuse.ImageTools/Fuse.ImageTools.unoproj
- Source/Fuse.ImageTools/ImageTools.uno
Another permission fix for compatibility with Android 13 later
> ImageTools permission fix for Android 13

- Source/Fuse.Controls.Native/Android/Java/ScalableType.java
- Source/Fuse.Controls.Native/Android/Java/VideoView.java
- Source/Fuse.Controls.Native/Android/VideoView.uno
- Source/Fuse.Controls.Native/Fuse.Controls.Native.unoproj
- Source/Fuse.Controls.Native/Interfaces.uno
- Source/Fuse.Controls.Native/iOS/VideoPlayerView.h
- Source/Fuse.Controls.Native/iOS/VideoPlayerView.m
- Source/Fuse.Controls.Native/iOS/VideoView.uno
- Source/Fuse.Controls.Video/Video.uno
Make `<Video/>`  component works on `NativeViewHost`
```
<App>
<ClientPanel>
<StackPanel Dock="Bottom">
<Text Value="Progress" />
<Panel Margin="10" Height="10">
<Rectangle >
<Stroke Alignment="Outside" Width="1">
<SolidColor Color="#000" />
</Stroke>
</Rectangle>
<Rectangle Width="0%" ux:Name="_progressBar" Alignment="Left">
<SolidColor Color="#0fc" />
</Rectangle>
</Panel>
<Text Value="Volume" />
<Slider ux:Name="_volume" Minimum="0" Maximum="1" Value="1" />
<Grid DefaultRow="auto" ColumnCount="2">
<Button ux:Name="_playButton" Text="Play">
<Clicked><Play Target="_video" /></Clicked>
</Button>
<Button ux:Name="_pauseButton" Text="Pause" Visibility="Hidden">
<Clicked><Pause Target="_video" /></Clicked>
</Button>
</Grid>
</StackPanel>
<Panel Dock="Fill">
<Panel ux:Name="_loadingMessage" …
```
> Native VIdeo Component

- Source/Fuse.Controls.ScrollView/ScrollView.Native.uno
- Source/Fuse.Controls.ScrollView/ScrollView.uno
Every time scrollview property changes we also push to the native.
> ScrollView push to native for property changes

- Source/Fuse.Controls.Native/Android/Java/FuseScrollView.java
- Source/Fuse.Controls.Native/Android/Java/HorizontalScrollView.java
- Source/Fuse.Controls.Native/Android/Java/VerticalScrollView.java
Android Scrolling detection improvement
> Scrolling detect Improvement
